= jdp-2023-12: Async fetching result set rows

== Status

* Published: 2023-07-04
* Updated: 2024-12-20
* Implemented in: Jaybird 6
* Updated by: https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2024-10-allow-disabling-async-fetch.adoc[jdp-2024-10]

== Type

* Feature-Specification

== Context

The result set implementation in Jaybird currently performs a synchronous fetch of rows, when there are no rows available on `ResultSet.next()`.
Introducing an asynchronous fetch, e.g. when there are __X__% or _N_ rows remaining can improve performance.
Such asynchronous fetching should not occur when using fetch size 1 and/or if a named cursor is set, as that generally indicates use of positioned updates and deletes.

The implementation in fbclient does not allow application controlled asynchronous fetch (though it may perform an asynchronous fetch in the background on its own), so any such feature would be limited to the PURE_JAVA implementation.

== Decision

The `org.firebirdsql.gds.ng.FbStatement` interface is extended as follows:

* `void asyncFetchRows(int fetchSize)` -- suggests to the statement to perform a forward asynchronous fetch for `fetchSize` rows.
+
The request is silently ignored (returns immediately) when:
+
** The implementation does not support asynchronous fetches
** If an asynchronous fetch is already pending
** If `fetchSize` is `1`
** If the statement has a cursor name set
** If current statement has a scrollable cursor (flag `CURSOR_TYPE_SCROLLABLE` set)
* There is no explicit way to complete async processing, other than using a synchronous fetch method.
+
A previous iteration of this JDP had a `completeAsyncFetch()` method, but on further evaluation, making that an implementation detail results in a simpler design.

The behaviour of existing methods is modified as follows:

* `void fetchRows(int fetchSize)` -- if an asynchronous fetch is pending, it will complete that asynchronous fetch instead of its normal fetch logic.
* `void fetchScroll(FetchType fetchType, int fetchSize, int position)` -- if an asynchronous fetch is pending, and `fetchType` is `NEXT`, it will complete that asynchronous fetch instead of its normal fetch logic.
+
If an asynchronous fetch is pending, and the `fetchType` is anything other than `NEXT`, an exception is raised.
This should not occur in practice given the requirement above to not perform async fetch for scrollable cursors.

To simplify tracking the received number of rows per fetch, `org.firebirdsql.gds.ng.listeners.StatementListener` is extended with one method:

* `fetchComplete(FbStatement sender, FetchDirection fetchDirection, int rows)` -- this will be called by the `FbStatement` implementation, for synchronous and asynchronous fetches with the number of rows fetched in a single fetch.
+
For NATIVE, this will be called with `0` or `1` for `rows`, as prefetching happens internally, and each fetch retrieves at most one row.
+
This method will also be called -- with `rows = 0` -- when no rows were fetched, contrary to previous iterations of this JDP.
+
The order in which `fetchComplete` and `afterLast`/`beforeFirst` are called when one or more rows were fetched when reaching end of cursor is undefined, so listeners must be able to handle either order.

Implementations of `FBFetcher` in Jaybird will be modified appropriately to call `asyncFetchRows(int)` where it makes sense.

== Consequences

Async fetch will be added.
This should be transparent for implementations which do not support async fetch.

The implementation will be done in V11, as the necessary infrastructure for processing deferred operations is not available in the V10 implementation.

Modification of `FBFetcher` only seems to make sense for `FBStatementFetcher`, but the behaviour of `FBUpdatableCursorFetcher` must be double-checked as it inherits from `FBStatementFetcher`.
It may also make sense in `FBCachedFetcher`, but this might be harder to do correctly.

The fetcher implementation will track the "`high-water mark`" of rows (the maximum number of rows returned by a single fetch), and evaluate when to async fetch (on the "`low-water mark`").
This JDP does not specify exactly _when_ to fetch, but as a starting point, we'll perform an async fetch at ~33% of the "`high-water mark`" or 10 rows, whichever is higher.
If the "`high-water mark`" is less than 15 rows, we'll not perform an async fetch.
This logic may be modified during evaluation and further testing, and should be considered an implementation detail, not a specification.

Some internal classes, for example `org.firebirdsql.jaybird.xca.FBManagedConnection.DataProvider` may also benefit from using async fetch.
This should be evaluated during implementation of this feature.
