= jdp-2023-07: Native Plugin as Separate Dependency

// SPDX-FileCopyrightText: Copyright 2023 Mark Rotteveel
// SPDX-License-Identifier: LicenseRef-PDL-1.0

== Status

* Published: 2023-05-27
* Implemented in: Jaybird 6

== Type

* Feature-Specification

== Context

The default and -- as far as we are aware -- most common use of Jaybird is as a pure Java (Type 4) JDBC driver.
Jaybird also provides a native (Type 2) protocol which allows use of `fbclient.dll`/`libfbclient.so` as the connection layer to a remote Firebird server, or to a Firebird Embedded instance.

== Decision

The native protocols (`NATIVE` and `EMBEDDED`) are split off to a separate dependency, `jaybird-native`.
The plugin JAR will use automatic module name `org.firebirdsql.jna` in preparation for future modularization.

== Consequences

The main Jaybird dependency -- `org.firebirdsql.jdbc:jaybird` -- will *only* provide the pure Java protocol.
Support for native and embedded will only be available if the `org.firebirdsql.jdbc:jaybird-native` artifact is on the classpath.

The plugin JAR will be included in the distribution zip, together with its sources and javadoc JARs.
Given the javadoc of the plugin is not that interesting, the unpacked javadoc of the plugin will not be included in the `docs` directory.

Given the structure of tests and the test infrastructure, the main Jaybird tests will depend on the `jaybird-native` module, and most -- if not all -- tests for the `jaybird-native` plugin will remain in the main module.
This might be something to change in the future, e.g. by introducing a common module for tests.

[appendix]
== License Notice

The contents of this Documentation are subject to the Public Documentation License Version 1.0 (the “License”);
you may only use this Documentation if you comply with the terms of this License.
A copy of the License is available at https://firebirdsql.org/en/public-documentation-license/.

The Original Documentation is "`jdp-2023-07: Native Plugin as Separate Dependency`".
The Initial Writer of the Original Documentation is Mark Rotteveel, Copyright © 2023.
All Rights Reserved.
(Initial Writer contact(s): mark (at) lawinegevaar (dot) nl).

////
Contributor(s): ______________________________________.
Portions created by ______ are Copyright © _________ [Insert year(s)].
All Rights Reserved.
(Contributor contact(s): ________________ [Insert hyperlink/alias]).
////

The exact file history is recorded in our Git repository;
see https://github.com/FirebirdSQL/jaybird
