= jdp-2023-06: ChaCha64 Support

== Status

* Draft
* Proposed for: Jaybird 6

== Type

* Feature-Specification

== Context

The "`ChaCha`" wire protocol encryption introduced in Firebird 4.0 uses ChaCha20 encryption.
The way ChaCha20 works is that after 256GiB of data, it needs to be re-keyed to prevent key reuse, which could be exploited for cryptological analysis and (partial) decryption.
Unfortunately, the Firebird wire protocol has no method to re-key the wire protocol encryption, and instead a new variant of ChaCha was added in Firebird 4.0.1 and Firebird 5.0.0, "`ChaCha64`".
"`ChaCha64`" uses a 64-bit counter instead of the 32-bit counter used in ChaCha20 as used by the "`ChaCha`" wire protocol encryption.
See also https://github.com/FirebirdSQL/firebird/issues/7065[Firebird#7065].

ChaCha20 is standardized by https://datatracker.ietf.org/doc/html/rfc7539#section-2.4[RFC 7539^] to use 96-bit nonce and a 32-bit counter.
ChaCha with 64-bit counter (and 64-bit nonce) is another variant of ChaCha.

Java includes a cipher _ChaCha20_ (since Java 11), which provides the RFC 7539 specified ChaCha variant (with 32-bit counter).
Java itself does not provide an implementation which supports the 64-bit nonce and 64-bit counter variant.

Bouncy Castle seems to support the 64-bit counter variant of ChaCha (not yet verified).

As a project, we like to minimize dependencies of the driver.

The wire protocol plugin encryption support in Jaybird is not complete, and currently relies on hardcoded plugin names instead of the service loader mechanism.

== Decision

Jaybird will add support for "`ChaCha64`" wire protocol encryption using a separate artifact, `org.firebirdsql.jdbc:chacha64-plugin`, as part of the Jaybird source tree (so not a separate repository).
The implementation will use the Bouncy Castle library.

[NOTE]
====
This decision assumes that Bouncy Castle indeed supports ChaCha with 64-bit counter.

This will be verified by implementing and testing this.
If this assumption is wrong, this JDP will likely be abandoned, or we need to look for a library which does provide ChaCha with 64-bit counter mode.
====

Selective enabling of encryption plugins (e.g. through a connection property) is *not* part of this JDP.

== Consequences

The main Jaybird dependency -- `org.firebirdsql.jdbc:jaybird` -- will not provide "`ChaCha64`" support.
Support will only be available when the `org.firebirdsql.jdbc:chacha64-plugin` artifact is on the classpath.

Wire protocol encryption plugin support in Jaybird needs to be completed so plugins can be loaded using the service loader mechanism, with a fallback to the plugins included in the core _jaybird_ artifact.

We're not sure if we can keep the Jaybird sources in the top-level Gradle module when there is also a submodule for _chacha64-plugin_.
It may be necessary to move the sources within the Jaybird repository to a submodule to accommodate this.
