= jdp-2025-06: Schema Support

// SPDX-FileCopyrightText: Copyright 2025 Mark Rotteveel
// SPDX-License-Identifier: LicenseRef-PDL-1.0

== Status

* Draft
* Proposed for: Jaybird 7, potential partial backport to Jaybird 5

== Type

* Feature-Specification

== Context

Firebird 6.0 introduces support for schemas.
To quote from `README.schemas.md` (of an early snapshot):

____
Firebird 6.0 introduces support for schemas in the database.
Schemas are not an optional feature, so every Firebird 6 database has at least a `SYSTEM` schema, reserved for Firebird system objects (`RDB$*` and `MON$*`).

User objects live in different schemas, which may be the automatically created `PUBLIC` schema or user-defined ones.
It is not allowed (except for indexes) to create or modify objects in the `SYSTEM` schema.
____

Important details related to schemas:

* Search path, defaults to `PUBLIC, SYSTEM`.
The session default can be configured with `isc_dpb_search_path` (string DPB item).
The current search path can be altered with `SET SEARCH_PATH TO ...`.
`ALTER SESSION RESET` reverts to the session default.
* If `SYSTEM` is not on the search path, it is automatically appended to the search path to be searched last
* The "`current`" schema cannot be set separately;
the first valid (i.e. existing) schema listed in the search path is considered the current schema.
* `CURRENT_SCHEMA` and `RDB$GET_CONTEXT('SYSTEM', 'CURRENT_SCHEMA')` return the first valid schema from the search path
* `RDB$GET_CONTEXT('SYSTEM', 'SEARCH_PATH')` returns the current search path
* Objects not qualified with a schema name will be resolved using the current search path.
This is done -- with some exceptions -- at prepare time.
* TPB has new item `isc_tpb_lock_table_schema` to specify the schema of a table to be locked (1 byte length + string data)
* Gbak has additional options to include/exclude (skip) schema data in backup or restore, similar to existing options to include/exclude tables
* Gstat has additional options to specify a schema for operations involving tables
* For validation, `val_sch_incl` and `val_sch_excl` (I don't think we use the related items `val_tab_incl`/`val_tab_excl` in Jaybird, so might not be relevant)
* Stored procedure resolution:
** Unqualified stored procedures (`<name>`) are searched on the search path
** Qualified stored procedures (`<schema-or-package>.<name>`) are first located by schema and name, and if not found, searched on the search path by package and name.
** Scope-specified stored procedures are either only located by schema (`<schema>%SCHEMA.<name>`) or only searched on the search path by package and name (`<package>%PACKAGE.<name>`), not both.
** Fully-qualified packaged stored procedures (`<schema>.<package>.<name>`) are located by schema, package and name

JDBC defines various methods, parameters, and return values or result set columns that are related to schemas.

Jaybird 5 is the "`long-term support`" version for Java 8.

[NOTE]
====
This document is in flux, and will be updated during implementation of the feature.
====

== Decision

Jaybird 7 will implement schema support for Firebird 6.0.
When Jaybird 7 is used on Firebird 5.0 or older, it will behave as before (no schemas at all).

Further details can be found in <<consequences>>.

Schema support will _not_ be backported to Jaybird 6 as the required changes are simply too large.
It would mean that Jaybird 6 would contain most of Jaybird 7, and upgrading to a -- theoretical -- Jaybird 6.1 would have similar risks and compatibility issues as upgrading to Jaybird 7.

Decision on a (partial) backport to Jaybird 5 -- as the "`long-term support`" version for Java 8 -- is still pending (e.g. as a Jaybird 5.1.x), and may be the subject of a separate JDP.
We might only do that on demand and/or when someone is willing to sponsor the work.

[#consequences]
== Consequences

The following changes are made to Jaybird to support schemas when connecting to Firebird 6.0 or higher:

* Connection property `searchPath` (alias `search_path`, `isc_dpb_search_path`) to configure the default session search path.
+
On Firebird 5.0 and older, this will be silently ignored.
* In internal queries in Jaybird, and fully qualified object names, we'll use the regular -- unquoted -- identifier `SYSTEM`, even though `SYSTEM` is a SQL:2023 reserved word, to preserve dialect 1 compatibility.
* `Connection`
** `getSchema()` will return the result of `select CURRENT_SCHEMA from SYSTEM.RDB$DATABASE`;
the connection will not store this value
** `setSchema(String)` will query the current search path, and if not previously called, it will prepend the schema name to the search path, otherwise it will _replace_ the previously prepended schema name.
The schema name is stored _only_ for this replacement operation (i.e. it will not be returned by `getSchema`!)
*** The name must match exactly as is stored in the metadata (it is always case-sensitive!)
*** Jaybird will take care of quoting, and will always quote on dialect 3
*** Existence of the schema is **not** checked, so it is possible the current schema does not change with this operation, as `CURRENT_SCHEMA` reports the first _valid_ schema
*** JDBC specifies that "`__Calling ``setSchema`` has no effect on previously created or prepared Statement objects.__`";
Jaybird cannot honour this requirement for plain `Statement`, as schema resolution is on prepare time (which for plain `Statement` is on execute), and not always for `CallableStatement`, as the implementation may delay actual prepare until execution, though we do try to identify the procedure when the callable statement is created and use that to fully-qualify the procedure.
* Request `isc_info_sql_relation_schema` after preparing a query, record it in `FieldDescriptor`, and return it were relevant for JDBC (e.g. `ResultSetMetaData.getSchemaName(int)`)
** For Firebird 5.0 and older, we need to ensure that JDBC methods continue to report the correct value (i.e. `""` for schema-less objects)
* A Firebird 6.0 variant of the `DatabaseMetaData` and other internal metadata queries needs to be written to address at least the following things:
** Explicitly qualify metadata tables with `SYSTEM`, so the queries will work even if another schema on the search path contains tables with the same names as the system tables.
** Returning schema names, and qualified object names where relevant (e.g. in `DatabaseMetaData` result sets)
** Include schema names in joins to ensure matching the right objects
** Allow searching for schema or schema pattern as specified in JDBC, or were needed for internal metadata queries
** `getCatalogs`;
it is not possible to identify the schema(s) within the confines of JDBC.
+
We considered adding a column that lists the schema(s) that contain the package name, but we don't think it will see use in practice.
* `FirebirdConnection`
** Added method `String getSearchPath()` to obtain the search path as reported by `RBB$GET_CONTEXT('SYSTEM', 'SEARCH_PATH')`, or `null` if schemas are not supported
** Added method `List<String> getSearchPathList()` to obtain the search path as a list of unquoted object names, or empty list if schemas are not supported
** Added methods `setSearchPath(String)` and `setSearchPathList` with overloads `(String...)` and `(List<String>)` to set the search path.
* `FBCallableStatement`
** On creating the instance, the stored procedure is parsed and identified in the database metadata, including selectability, unless `ignoreProcedureType` is `true`
*** Parsing of callable statements is changed to be able to identify schema, package and procedure name, including scope specifiers
** Jaybird emulates the lookup rules as used by Firebird, and -- if found -- records the identified procedure so subsequent internal prepares refer to the same procedure, even if the search path changes;
this fulfills the JDBC requirements that a `CallableStatement` is not sensitive to current schema changes, but only *if* Jaybird is able to identify the procedure, behaviour is undefined if the procedure was not found.
** The API of `StoredProcedureMetaData` (internal API) is changed to not report selectability, but to update the `FBProcedureCall` instance with selectability and other information, like identified schema and/or package.
** For qualified *and* unambiguous procedure reference, the selectability is cached *per connection*, for unqualified or ambiguous procedure reference, the lookup is performed on each `Connection.prepareCall`, to account for search path changes
** Support for packages was missing in the handling of callable statements, and is added, also for older versions
* Effects for management API
** `StatisticsManager`
*** `getTableStatistics` received an overload to also accept a list of schemas (`sts_schema`)
** `FBTableStatisticsManager`/`TableStatistics`
*** Internally `ObjectReference` is used for the table instead of a String
*** The key of the map returned by `getTableStatistics()` is a qualified table reference (i.e. `{<table-name> | <quoted-schema>.<quoted-table-name>}`.
For schemaless tables, the unquoted table name is used as the key for backwards compatibility when used against Firebird 5.0 and older.
*** `TableStatistics` received two extra accessors:
**** `schema()` with the schema, or empty string if schemaless (or not found)
**** `tableReference()` with the qualified table reference (i.e. `[<quoted-schema>.]<quoted-table-name>` (contrary to the key of getTableStatistics, it's always quoted!))
* TODO: Add information to Jaybird manual

Note to self: use `// TODO Add schema support` in places that you identify need to get/improve schema support, while working on schema support elsewhere

[appendix]
== License Notice

The contents of this Documentation are subject to the Public Documentation License Version 1.0 (the “License”);
you may only use this Documentation if you comply with the terms of this License.
A copy of the License is available at https://firebirdsql.org/en/public-documentation-license/.

The Original Documentation is "`jdp-2025-06: Schema Support`".
The Initial Writer of the Original Documentation is Mark Rotteveel, Copyright © 2025.
All Rights Reserved.
(Initial Writer contact(s): mark (at) lawinegevaar (dot) nl).

////
Contributor(s): ______________________________________.
Portions created by ______ are Copyright © _________ [Insert year(s)].
All Rights Reserved.
(Contributor contact(s): ________________ [Insert hyperlink/alias]).
////

The exact file history is recorded in our Git repository;
see https://github.com/FirebirdSQL/jaybird