= jdp-2025-07: Statement Max Field Size

// SPDX-FileCopyrightText: Copyright 2025 Mark Rotteveel
// SPDX-License-Identifier: LicenseRef-PDL-1.0

== Status

* Published: 2025-11-13
* Implemented in: Jaybird 7

== Type

* Feature-Specification

== Context

JDBC defines the methods https://docs.oracle.com/en/java/javase/25/docs/api/java.sql/java/sql/Statement.html#setMaxFieldSize(int)[`setMaxFieldSize`^] and https://docs.oracle.com/en/java/javase/25/docs/api/java.sql/java/sql/Statement.html#getMaxFieldSize()[`getMaxFieldSize`^] on `java.sql.Statement`, with the following in its javadoc:

[quote,,Java 25 API documentation]
____
Sets the limit for the maximum number of bytes that can be returned for character and binary column values in a `ResultSet` object produced by this `Statement` object.
This limit applies only to `BINARY`, `VARBINARY`, `LONGVARBINARY`, `CHAR`, `VARCHAR`, `NCHAR`, `NVARCHAR`, `LONGNVARCHAR` and `LONGVARCHAR` fields.
If the limit is exceeded, the excess data is silently discarded.
For maximum portability, use values greater than `256`.

Parameters: +
`max` - the new column size limit in bytes; zero means there is no limit
____

And in the specification:

[quote,JDBC 4.3 Specification]
____
[discrete]
==== 8.3.1 Silent Truncation

The `Statement.setMaxFieldSize` method allows a maximum size (in bytes) to be set.
This limit applies only to the (JDBC types) `BINARY`, `VARBINARY`, `LONGVARBINARY`, `CHAR`, `VARCHAR`, `LONGVARCHAR`, `NCHAR`, `NVARCHAR`, and `LONGNVARCHAR` data types.
If a limit has been set using `setMaxFieldSize` and there is an attempt to read data that exceeds the limit, any truncation that occurs as a result of exceeding the set limit will _not_ be reported.
____

Firebird doesn't provide a way to restrict the maximum number of bytes returned that will not result in string truncation errors for longer values, or -- for shorter values -- would result in "`wrong`" client-side length derivations of variable length encodings like UTF8 (which would result in excessive truncation).

Jaybird considers `BLOB SUB_TYPE TEXT` to be `LONGVARCHAR` and `BLOB SUB_TYPE BINARY` and other Firebird subtypes to be `LONGVARBINARY`.
Custom subtypes (negative subtypes), are considered `Types.BLOB`

== Decision

Jaybird 7 implements support for `setMaxFieldSize`/`getMaxFieldSize` using client-side truncation.
This will be implemented for `CHAR`, `VARCHAR`, `BINARY`, `VARBINARY`, `LONGVARCHAR` and `LONGVARBINARY`

To avoid problems with `RDB$DB_KEY` columns, implementation must ignore the limit for those columns, as indicated by `FieldDescriptor.isDbKey()`.

Custom blob types (i.e. with a negative subtype) are not affected, as Jaybird considers those `Types.BLOB`.

== Consequences

For `CHAR`, `VARCHAR`, `BINARY`, and `VARBINARY`, truncation is implemented in the `FbStatement` implementations in the GDS-ng layer.
The truncation is done when fetching the data from the server (wire protocol), or from fbclient (native/embedded).

`FbStatement` has an `int` property `maxFieldSize` with a default implementation that ignores the set value and returns `0`.
The actual implementations override this, and use the set value when receiving data from the server or native client.

For `LONGVARCHAR`/`LONGVARBINARY`, this is implemented in the relevant `FBField` implementations and configured from `FBResultSet`.

* For non-cached blobs, the maximum length is applied for `getBytes` and getters relying on `getBytes`, like the getters for string, numeric, Boolean and datetime types, and `getObject` that returns any of those types, but not to getters returning `Blob`, `Clob`, `InputStream`, or `Reader`.
+
In case of `InputStream` and `Reader`, such behaviour doesn't conform to the JDBC requirements, but this avoids complications in the implementation.
We may address this in the future (e.g. maybe if we implement support for `Blob.getBinaryStream(long, long)`).
+
Supporting `Blob` and `Clob` for `LONGVARCHAR` and `LONGVARBINARY` is already a non-standard extension so -- in our opinion -- not subject to these requirements.
* For cached blobs (as used in holdable or emulated scrollable result sets), the maximum length is also applied to methods returning `Blob`, `Clob`, `InputStream`, or `Reader`.

Caveats:

* Given the truncation happens at a set number of bytes, values in a multibyte character set (UTF8) might end in the Unicode replacement character (U+FFFD, '`&#xFFFD;`') due to truncation before the end of the encoded codepoint.
* Jaybird will accept any non-negative value for `maxFieldSize`.
The JDBC apidoc recommends using values greater than `256`.
* A too small `maxFieldSize` may result in "`wrong`" values being returned without error for numeric and Boolean getters;
for datetime getters it may result in missing precision without errors, or parse errors.
* Setting the max field size after execute may not be immediately applied to the current result set for `CHAR`, `VARCHAR`, `BINARY`, and `VARBINARY`:
** For a locally cached result set: never, as the rows were truncated to the `maxFieldSize` on execute.
** Otherwise, already fetched rows are truncated to the `maxFieldSize` on their fetch, and only rows returned by a subsequent fetch will apply the new limit.
* For `LONGVARCHAR`/`LONGVARBINARY`, the value will be truncated on access, with the following caveats:
** For cached blobs, the limit is applied on retrieval, and applies to all methods (as the cached value is truncated).
** The value of a cached blob (holdable result set or emulated scrollable result set) will be truncated to the initial `maxFieldSize`.
Subsequent use of a larger `maxFieldSize` will continue to return the shorter value.
* The detection of `RDB$DB_KEY` columns includes "`normal`" `BINARY`/`CHAR CHARACTER SET OCTETS` columns called `DB_KEY`.

[appendix]
== License Notice

The contents of this Documentation are subject to the Public Documentation License Version 1.0 (the “License”);
you may only use this Documentation if you comply with the terms of this License.
A copy of the License is available at https://firebirdsql.org/en/public-documentation-license/.

The Original Documentation is "`jdp-2025-07: Statement Max Field Size`".
The Initial Writer of the Original Documentation is Mark Rotteveel, Copyright © 2025.
All Rights Reserved.
(Initial Writer contact(s): mark (at) lawinegevaar (dot) nl).

////
Contributor(s): ______________________________________.
Portions created by ______ are Copyright © _________ [Insert year(s)].
All Rights Reserved.
(Contributor contact(s): ________________ [Insert hyperlink/alias]).
////

The exact file history is recorded in our Git repository;
see https://github.com/FirebirdSQL/jaybird