language: java

jdk:
  - openjdk8

before_cache:
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/journal-1/
  - find $HOME/.gradle/caches/ -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew assemble
