# SPDX-FileCopyrightText: Copyright 2025 Mark Rotteveel
# SPDX-License-Identifier: LGPL-2.1-or-later

version = 1
SPDX-PackageName = "Jaybird JDBC Driver"
SPDX-PackageSupplier = "Mark Rotteveel <mark@lawinegevaar.nl>"
SPDX-PackageDownloadLocation = "https://firebirdsql.org/en/jdbc-driver/"

[[annotations]]
path = "LICENSE"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2025 Mark Rotteveel"
SPDX-License-Identifier = "LicenseRef-PDL-1.0"

[[annotations]]
path = "chacha64-plugin/src/main/resources/META-INF/services/org.firebirdsql.gds.ng.wire.crypt.EncryptionPluginSpi"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023 Mark Rotteveel"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "devdoc/formatting/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2015-2024 Mark Rotteveel"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "devdoc/maven-release/instructions.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2012-2023 Mark Rotteveel"
SPDX-License-Identifier = "LicenseRef-PDL-1.0"

[[annotations]]
path = "devdoc/jaybird-icla.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = ["Apache Software Foundation", "Copyright 2015 Mark Rotteveel"]
SPDX-License-Identifier = "LicenseRef-ICLA"

[[annotations]]
path = "gradle/wrapper/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gradle Inc. and/or \"the original authors\""
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "jaybird-native/src/main/resources/META-INF/services/org.firebirdsql.gds.impl.GDSFactoryPlugin"
precedence = "aggregate"
SPDX-FileCopyrightText = [ "Copyright 2005-2006 Roman Rokytskyy", "Copyright 2021-2023 Mark Rotteveel" ]
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "jaybird-native/src/main/resources/META-INF/services/org.firebirdsql.jaybird.props.spi.ConnectionPropertyDefinerSpi"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023 Mark Rotteveel"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "src/docs/theme/fonts/NotoSans-*.ttf"
precedence = "aggregate"
SPDX-FileCopyrightText = "Google Inc. and/or \"the original authors\""
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "src/docs/theme/jaybird-html/firebird.css"
precedence = "aggregate"
SPDX-FileCopyrightText = [ "https://asciidoctor.org", "Copyright 2021-2024 Mark Rotteveel" ]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/docs/theme/jaybird-html/docinfo/docinfo-footer.html"
precedence = "aggregate"
SPDX-FileCopyrightText = [ "https://github.com/tscanlin", "https://github.com/owenh000", "Copyright 2021 Mark Rotteveel" ]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/resources/META-INF/services/java.sql.Driver"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2009 Roman Rokytskyy"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "src/resources/META-INF/services/org.firebirdsql.encodings.EncodingSet"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2013 Mark Rotteveel"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "src/resources/META-INF/services/org.firebirdsql.gds.impl.GDSFactoryPlugin"
precedence = "aggregate"
SPDX-FileCopyrightText = ["Copyright 2005-2006 Roman Rokytskyy", "Copyright 2021-2023 Mark Rotteveel"]
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "src/resources/META-INF/services/org.firebirdsql.gds.ng.wire.auth.AuthenticationPluginSpi"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2018 Mark Rotteveel"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "src/resources/META-INF/services/org.firebirdsql.gds.ng.wire.crypt.EncryptionPluginSpi"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2023 Mark Rotteveel"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = "src/resources/META-INF/services/org.firebirdsql.gds.ng.wire.ProtocolDescriptor"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2013-2025 Mark Rotteveel"
SPDX-License-Identifier = "LGPL-2.1-or-later"
