/*
 * Firebird Open Source J2ee connector - jdbc driver
 *
 * Distributable under LGPL license.
 * You may obtain a copy of the License at http://www.gnu.org/copyleft/lgpl.html
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * LGPL License for more details.
 *
 * This file was created by members of the firebird development team.
 * All individual contributions remain the Copyright (C) of those
 * individuals.  Contributors to this file are either listed here or
 * can be obtained from a CVS history command.
 *
 * All rights reserved.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_firebirdsql_ngds_GDS_0005fImpl */

#ifndef _Included_org_firebirdsql_ngds_GDS_0005fImpl
#define _Included_org_firebirdsql_ngds_GDS_0005fImpl
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: sInstance */
/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    nativeInitilize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_nativeInitilize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    native_isc_create_database
 * Signature: (Ljava/lang/String;Lorg/firebirdsql/gds/isc_db_handle;[B)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1create_1database
  (JNIEnv *, jobject, jstring, jobject, jbyteArray);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    native_isc_attach_database
 * Signature: (Ljava/lang/String;Lorg/firebirdsql/gds/isc_db_handle;[B)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1attach_1database
  (JNIEnv *, jobject, jstring, jobject, jbyteArray);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_database_info
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;I[BI[B)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1database_1info
  (JNIEnv *, jobject, jobject, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_detach_database
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1detach_1database
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_drop_database
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1drop_1database
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    native_isc_start_transaction
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;Lorg/firebirdsql/gds/isc_db_handle;[B)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1start_1transaction
  (JNIEnv *, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_commit_transaction
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1commit_1transaction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_commit_retaining
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1commit_1retaining
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_prepare_transaction
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1prepare_1transaction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_prepare_transaction2
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;[B)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1prepare_1transaction2
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_rollback_transaction
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1rollback_1transaction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_rollback_retaining
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1rollback_1retaining
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_allocate_statement
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;Lorg/firebirdsql/gds/isc_stmt_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1allocate_1statement
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_alloc_statement2
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;Lorg/firebirdsql/gds/isc_stmt_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1alloc_1statement2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_describe
 * Signature: (Lorg/firebirdsql/gds/isc_stmt_handle;I)Lorg/firebirdsql/gds/XSQLDA;
 */
JNIEXPORT jobject JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1describe
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_describe_bind
 * Signature: (Lorg/firebirdsql/gds/isc_stmt_handle;I)Lorg/firebirdsql/gds/XSQLDA;
 */
JNIEXPORT jobject JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1describe_1bind
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_execute
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;Lorg/firebirdsql/gds/isc_stmt_handle;ILorg/firebirdsql/gds/XSQLDA;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1execute
  (JNIEnv *, jobject, jobject, jobject, jint, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_execute2
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;Lorg/firebirdsql/gds/isc_stmt_handle;ILorg/firebirdsql/gds/XSQLDA;Lorg/firebirdsql/gds/XSQLDA;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1execute2
  (JNIEnv *, jobject, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_execute_immediate
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;Lorg/firebirdsql/gds/isc_tr_handle;Ljava/lang/String;ILorg/firebirdsql/gds/XSQLDA;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1execute_1immediate__Lorg_firebirdsql_gds_isc_1db_1handle_2Lorg_firebirdsql_gds_isc_1tr_1handle_2Ljava_lang_String_2ILorg_firebirdsql_gds_XSQLDA_2
  (JNIEnv *, jobject, jobject, jobject, jstring, jint, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_execute_immediate
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;Lorg/firebirdsql/gds/isc_tr_handle;Ljava/lang/String;Ljava/lang/String;ILorg/firebirdsql/gds/XSQLDA;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1execute_1immediate__Lorg_firebirdsql_gds_isc_1db_1handle_2Lorg_firebirdsql_gds_isc_1tr_1handle_2Ljava_lang_String_2Ljava_lang_String_2ILorg_firebirdsql_gds_XSQLDA_2
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jint, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_exec_immed2
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;Lorg/firebirdsql/gds/isc_tr_handle;Ljava/lang/String;ILorg/firebirdsql/gds/XSQLDA;Lorg/firebirdsql/gds/XSQLDA;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1exec_1immed2__Lorg_firebirdsql_gds_isc_1db_1handle_2Lorg_firebirdsql_gds_isc_1tr_1handle_2Ljava_lang_String_2ILorg_firebirdsql_gds_XSQLDA_2Lorg_firebirdsql_gds_XSQLDA_2
  (JNIEnv *, jobject, jobject, jobject, jstring, jint, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_exec_immed2
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;Lorg/firebirdsql/gds/isc_tr_handle;Ljava/lang/String;Ljava/lang/String;ILorg/firebirdsql/gds/XSQLDA;Lorg/firebirdsql/gds/XSQLDA;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1exec_1immed2__Lorg_firebirdsql_gds_isc_1db_1handle_2Lorg_firebirdsql_gds_isc_1tr_1handle_2Ljava_lang_String_2Ljava_lang_String_2ILorg_firebirdsql_gds_XSQLDA_2Lorg_firebirdsql_gds_XSQLDA_2
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jint, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_fetch
 * Signature: (Lorg/firebirdsql/gds/isc_stmt_handle;ILorg/firebirdsql/gds/XSQLDA;I)V
 */
JNIEXPORT jboolean JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1fetch
  (JNIEnv *, jobject, jobject, jint, jobject, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_free_statement
 * Signature: (Lorg/firebirdsql/gds/isc_stmt_handle;I)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1free_1statement
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_prepare
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;Lorg/firebirdsql/gds/isc_stmt_handle;Ljava/lang/String;I)Lorg/firebirdsql/gds/XSQLDA;
 */
JNIEXPORT jobject JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1prepare__Lorg_firebirdsql_gds_isc_1tr_1handle_2Lorg_firebirdsql_gds_isc_1stmt_1handle_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jobject, jobject, jstring, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_prepare
 * Signature: (Lorg/firebirdsql/gds/isc_tr_handle;Lorg/firebirdsql/gds/isc_stmt_handle;Ljava/lang/String;Ljava/lang/String;I)Lorg/firebirdsql/gds/XSQLDA;
 */
JNIEXPORT jobject JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1prepare__Lorg_firebirdsql_gds_isc_1tr_1handle_2Lorg_firebirdsql_gds_isc_1stmt_1handle_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_set_cursor_name
 * Signature: (Lorg/firebirdsql/gds/isc_stmt_handle;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1set_1cursor_1name
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_dsql_sql_info
 * Signature: (Lorg/firebirdsql/gds/isc_stmt_handle;[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1dsql_1sql_1info
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    getSqlCounts
 * Signature: (Lorg/firebirdsql/gds/isc_stmt_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_getSqlCounts
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_vax_integer
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1vax_1integer
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    native_isc_create_blob2
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;Lorg/firebirdsql/gds/isc_tr_handle;Lorg/firebirdsql/gds/isc_blob_handle;[B)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1create_1blob2
  (JNIEnv *, jobject, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    native_isc_open_blob2
 * Signature: (Lorg/firebirdsql/gds/isc_db_handle;Lorg/firebirdsql/gds/isc_tr_handle;Lorg/firebirdsql/gds/isc_blob_handle;[B)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1open_1blob2
  (JNIEnv *, jobject, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_get_segment
 * Signature: (Lorg/firebirdsql/gds/isc_blob_handle;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1get_1segment
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_put_segment
 * Signature: (Lorg/firebirdsql/gds/isc_blob_handle;[B)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1put_1segment
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    isc_close_blob
 * Signature: (Lorg/firebirdsql/gds/isc_blob_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1close_1blob
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    native_isc_blob_info
 * Signature: (Lorg/firebirdsql/gds/isc_blob_handle;[B)V
 */
JNIEXPORT jbyteArray JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1blob_1info
  (JNIEnv *, jobject, jobject, jbyteArray, jint);

/*
 * Class:     org_firebirdsql_ngds_GDS_0005fImpl
 * Method:    native_isc_seek_blob
 * Signature: (Lorg/firebirdsql/gds/isc_blob_handle;)V
 */
JNIEXPORT void JNICALL Java_org_firebirdsql_ngds_GDS_1Impl_native_1isc_1seek_1blob
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

