= Jaybird Frequently Asked Questions
:doctype: book
:docinfo:
:sectanchors:
:forceinclude: true
:keywords: jaybird, firebird, jdbc, sql, database, java
:source-highlighter: prettify
:toc: left
:icons: font
:jaybird6-full-version: 6.0.5
:jaybird6-jna-version: 5.18.1
:jaybird5-full-version: 5.0.12
:jaybird5-template-version: {jaybird5-full-version}.<java>
:jaybird5-example-version: {jaybird5-full-version}.java11
:jaybird5-jna-version: 5.18.1
:firebird-java: https://groups.google.com/g/firebird-java
:issues: https://github.com/FirebirdSQL/jaybird/issues
:jaybird-repo: https://github.com/FirebirdSQL/jaybird
:firebird-conf-ref: https://firebirdsql.org/docs/chunk/en/refdocs/fbconf/fbconf-firebird.html
:jaybird-manual: https://firebirdsql.github.io/jaybird-manual/jaybird_manual.html
:sectnums:
:fb-canonical-html: https://firebirdsql.org/docs/drivers/java/faq.html

////
SPDX-FileCopyrightText: Copyright 2021-2026 Firebird development team and individual contributors
SPDX-FileCopyrightText: Copyright 2002-2004 Rick Fincher
SPDX-FileCopyrightText: Copyright 2013-2026 Mark Rotteveel
SPDX-License-Identifier: LicenseRef-PDL-1.0
////

[#jaybird]
= Jaybird

[#what-is-jaybird]
== What is Jaybird?

Jaybird is a JDBC (Java DataBase Connectivity) driver for the https://firebirdsql.org[Firebird] SQL database management system.
It is _the_ way to connect to Firebird from Java and any other Java Virtual Machine (JVM) based languages.

[#covered-versions]
== What Jaybird versions are covered by this FAQ?

This FAQ covers Jaybird 5 and higher.

Older versions are not covered, as they are no longer supported.
The distribution ZIPs of older versions, as available from {jaybird-repo}/releases[Jaybird GitHub Releases], contains an FAQ and release notes with information for that version.

[#where-do-i-get-jaybird]
== Where do I get Jaybird?

You can find the latest Jaybird releases on:

[#download]
* https://firebirdsql.org/en/jdbc-driver/[Firebird website: Firebird Type 4 JDBC Driver Downloads]
* {jaybird-repo}/releases[Jaybird GitHub Releases]
+
The Jaybird GitHub Releases page is also an archive for all releases since JayBird _[sic]_ 1.0-beta-1.
* Maven Central Repository
** https://central.sonatype.com/artifact/org.firebirdsql.jdbc/jaybird[Maven Central: org.firebirdsql.jdbc:jaybird^]
** https://central.sonatype.com/artifact/org.firebirdsql.jdbc/jaybird-native[Maven Central: org.firebirdsql.jdbc:jaybird-native^]
** https://central.sonatype.com/artifact/org.firebirdsql.jdbc/chacha64-plugin[Maven Central: org.firebirdsql.jdbc:chacha64-plugin^]

[#maven]
=== Maven

We recommend using your favourite build tool -- like Maven or Gradle -- to get Jaybird from Maven Central instead of downloading it manually from our site or GitHub.

[#jaybird-6]
==== Jaybird 6

Jaybird 6 requires Java 17 or higher.
For older Java versions (Java 8 and higher), use <<jaybird-5>>.

Jaybird 6 is available on Maven Central:

[horizontal.compact]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird`
version:: `{jaybird6-full-version}`

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>{jaybird6-full-version}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), add `jaybird-native` as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-native</artifactId>
    <version>{jaybird6-full-version}</version>
</dependency>
----

If -- with Jaybird 5 or older -- you added `net.java.dev.jna:jna` for native or embedded use, you can remove that explicit dependency.
The `jaybird-native` dependency will automatically pull in `net.java.dev.jna:jna-jpms` (the modular variant of `jna`).

For Windows and Linux, you can add the https://github.com/mrotteveel/jaybird-fbclient[`org.firebirdsql.jdbc:fbclient`] dependency on your classpath to provide the native libraries for the `native` protocol.
This dependency does *not* support Firebird embedded.

To enable the "`ChaCha64`" wire encryption support for pure Java connections, add `chacha64-plugin` as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>chacha64-plugin</artifactId>
    <version>{jaybird6-full-version}</version>
</dependency>
----

[#jaybird-5]
==== Jaybird 5

Unless you need to use Java 8 or Java 11, we recommend upgrading to <<jaybird-6>>.

Jaybird 5 is available on Maven Central:

[horizontal.compact]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird`
version:: `{jaybird5-template-version}` (where `<java>` is `java11` or `java8`)

Contrary to Jaybird 4, a Maven relocation artifact with artifact id `jaybird-XX` (with `XX` `jdk17`, `jdk18`) is no longer provided.
Please make sure you use the `jaybird` artifactId.

For example, for Java 11:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>{jaybird5-example-version}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), you need to explicitly include JNA {jaybird5-jna-version} as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>{jaybird5-jna-version}</version>
</dependency>
----

[#jaybird-4]
==== Jaybird 4

Jaybird 4 is end-of-life and will receive no further updates.
We recommend upgrading to <<jaybird-6>>.

////
// Stop showing Jaybird 4 Maven info, but keep available for now
Jaybird 4 is available from Maven Central:

[horizontal.compact]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird`
version:: `4.0.10.<java>` (where `<java>` is `java11`, `java8` or `java7`)

For backwards compatibility, we also provide a Maven relocation artifact with artifact id `jaybird-XX` (with `XX` `jdk17` or `jdk18`.
However, we recommend switching to the `jaybird` artifact.

For example, for Java 11:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>4.0.10.java11</version>
</dependency>
----

If your application is deployed to a Java EE application server, you will need to exclude the `javax.resource:connector-api` dependency, and add it as a provided dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>4.0.10.java11</version>
    <exclusions>
        <exclusion>
            <groupId>javax.resource</groupId>
            <artifactId>connector-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>javax.resource</groupId>
    <artifactId>connector-api</artifactId>
    <version>1.5</version>
    <scope>provided</scope>
</dependency>
----

If you want to use Type 2 support (native, local or embedded), you need to explicitly include JNA 5.5.0 as a dependency:

[source,xml]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>5.5.0</version>
</dependency>
----
////

[#where-can-i-get-the-sourcecode]
== Where can I get the sourcecode?

All Jaybird <<where-do-i-get-jaybird,distribution ZIPs>> contain a `jaybird-<version>-sources.zip` with the sources used for that specific version.
The Maven Central repository also has this `jaybird-<version>-sources.zip`, and your IDE will generally offer to download it for you if you navigate to any Jaybird class.

The full Jaybird sources, including the build files, are available from GitHub in the Jaybird repository, {jaybird-repo}.
Each release is tagged in the repository.

[#how-is-jaybird-licensed]
== How is Jaybird licensed?

The Jaybird JDBC driver is distributed under the GNU Lesser General Public License (LGPL).
Text of the license can be obtained from https://www.gnu.org/copyleft/lesser.html[^].

Using Jaybird (by importing Jaybird's public interfaces in your Java code), and extending Jaybird by subclassing or implementation of an extension interface (but not abstract or concrete class) is considered by the authors of Jaybird to be dynamic linking.
Hence, our interpretation of the LGPL is that the use of the unmodified Jaybird source does not affect the license of your application code.

Even more, all extension interfaces to which an application might want to link are released under a dual LGPL/modified BSD license.
The latter is basically an "AS IS" license that allows any kind of use of that source code.
Jaybird should be viewed as an implementation of those interfaces and the LGPL section for dynamic linking is applicable in this case.

[#which-version-of-the-lgpl-applies]
=== Which version of the LGPL applies?

Starting with Jaybird 7, we explicitly declare use of https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html[LGPL 2.1^] or later. +
Jaybird 6 and older do not explicitly specify an LGPL versionfootnote:[At the time the GNU Lesser General Public License (LGPL) was chosen as the license for Jaybird, LGPL 2.1 was the only version with that name].

This means that you can choose which version of LGPL applies.
Future versions of Jaybird may specify a different version, or be released under a different license.

[#which-java-versions-are-supported]
== Which Java versions are supported?

[#java-jaybird-6]
[discrete]
=== Jaybird 6

Support is limited to Java LTS releases starting with Java 17, and the latest Java release.
Currently, that means Jaybird 6 supports Java 17, Java 21, Java 25, and Java 26.

Jaybird 6 is compiled targeting Java 17.

[#java-jaybird-5]
[discrete]
=== Jaybird 5

Support is limited to Java LTS releases starting with Java 8, and the latest Java release.
Currently, that means Jaybird 5 supports Java 8, Java 11, Java 17, Java 21, Java 25, and Java 26.

Jaybird 5 is compiled targeting Java 8 (version format `5.0.x.java8`) and Java 11 (version format `5.0.x.java11`).
We recommend using the Java 11 build on Java 11 and higher.

Jaybird 5 is the last version to support Java 8 and Java 11, support has been dropped with Jaybird 6, raising the minimum supported version to Java 17.

[NOTE]
====
Jaybird 5 serves as a "`long-term support`" version for Java 8 and Java 11, with maintenance releases at least until the release of Jaybird 7.

See also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2022-03-java-17-minimum-version.md[jdp-2022-03: Java 17 minimum version].

It is possible future maintenance releases of Jaybird 5 stop expanding Java support to include newly released Java versions.
A reason can be -- but is not limited to -- if adding support for a newer Java version results in breaking support for Java 8 or Java 11, or JDBC 4.2 or JDBC 4.3, or require changes that would limit testability on those versions.
We may also simply stop expanding Java support to limit the number of versions we need to test.
====

[#what-is-the-java-9-module-name-for-jaybird]
== What is the Java 9 module name for Jaybird?

Jaybird 6 is modularized.
The available modules are:

`org.firebirdsql.jaybird`::
main Jaybird driver (`jaybird-{jaybird6-full-version}.jar`)

`org.firebirdsql.jaybird.chacha64`::
ChaCha64 wire encryption implementation (`chacha64-plugin-{jaybird6-full-version}.jar`)

`org.firebirdsql.jna`::
native and embedded protocol implementation using JNA (`jaybird-native-{jaybird6-full-version}.jar`)

Jaybird 5 and older are not modularized.
To ensure a stable module name, Jaybird 5 and older, since versions 2.2.14 and 3.0.3, declare the automatic module name `org.firebirdsql.jaybird`.

[#which-firebird-versions-are-supported]
== Which Firebird versions are supported?

[#firebird-jaybird-6]
[discrete]
=== Jaybird 6

Jaybird 6 supports Firebird 3.0, Firebird 4.0, and Firebird 5.0.

.No promises on Firebird 6.0 support
[WARNING#firebird-jaybird-6-fb6]
====
Firebird 6.0 is still in development, and includes changes -- like schema support -- that impact Jaybird.

As a result -- at this time -- we make no promises on the support for Firebird 6.0 by Jaybird 6.
We may delay support for Firebird 6.0 until Jaybird 7, or we may improve support during maintenance releases of Jaybird 6.
====

By default, Jaybird 6 -- using the pure Java protocol -- will not connect to Firebird 2.5 and older.
See <<connection-rejected-by-remote-interface-335544421>> for a workaround.

[#firebird-jaybird-5]
[discrete]
=== Jaybird 5

Jaybird 5 supports Firebird 2.5, Firebird 3.0, Firebird 4.0, and Firebird 5.0.

.No promises on Firebird 6.0 support
[WARNING#firebird-jaybird-5-fb6]
====
Firebird 6.0 is still in development, and includes changes -- like schema support -- that impact Jaybird.

As a result -- at this time -- we make no promises on the support for Firebird 6.0 by Jaybird 5.
We may delay support for Firebird 6.0 until Jaybird 7, or we may improve support during maintenance releases of Jaybird 5 and/or Jaybird 6.
====

Jaybird 5 is the last version to support Firebird 2.5.

[#can-jaybird-connect-to-interbase]
== Can Jaybird connect to Interbase?

Jaybird does not support Interbase.
As far as we know, connecting to Interbase 6.0 and later will fail due to Firebird specific changes in the implementation.

== Can Jaybird be used on Android

Jaybird does not work on Android.
It uses classes and Java features which are not available on Android.

Instead, we recommend building a webservice (e.g. REST-based) to mediate between your Android application and the database.

[#documentation-and-support]
= Documentation and Support

[#where-to-get-more-information-on-jaybird]
== Where to get more information on Jaybird

Apart from this FAQ, you can get additional information from:

* {jaybird-manual}[Jaybird JDBC Driver Java Programmer's Manual] (HTML, https://firebirdsql.github.io/jaybird-manual/jaybird_manual.pdf[PDF version]) (covers Jaybird 4 and higher)
* https://firebirdsql.org/en/jdbc-driver/[Firebird website: Downloads, Connectivity, JDBC Driver]
* https://firebirdsql.org/en/devel-jdbc-driver/[Firebird website: Development, JDBC Driver]
* https://github.com/FirebirdSQL/jaybird/wiki/[Jaybird wiki] ("`archived`")

For version specific details, consult the release notes

* https://firebirdsql.org/docs/drivers/java/6.0.x/release_notes.html[Jaybird 6.0.x release notes]
* https://firebirdsql.org/docs/drivers/java/5.0.x/release_notes.html[Jaybird 5.0.x release notes]

[#where-to-get-help]
== Where to get help

* The {firebird-java}[Firebird-Java group^] and corresponding mailing list firebird-java@googlegroups.com
+
You can subscribe to the mailing list by sending an email to link:mailto:firebird-java+subscribe@googlegroups.com[firebird-java+subscribe@googlegroups.com]
* Looking for professional support of Jaybird?
Jaybird is now part of the https://tidelift.com/subscription/pkg/maven-org-firebirdsql-jdbc-jaybird?utm_source=maven-org-firebirdsql-jdbc-jaybird&utm_medium=referral&utm_campaign=docs[Tidelift subscription^].
* The https://firebirdsql.org[Firebird project home page]
* https://groups.google.com/g/firebird-support[Firebird-support^] and other https://firebirdsql.org/en/mailing-lists/[Firebird mailing lists] for questions not directly related to Jaybird and Java.

[#contributing]
== Contributing

There are several ways you can contribute to Jaybird or Firebird in general:

* Participate on the https://firebirdsql.org/en/mailing-lists/[mailing lists]
* Report bugs or submit patches on the tracker (see <<reporting-bugs>>)
* Create pull requests on GitHub (https://github.com/FirebirdSQL/jaybird)
* Become a developer (for Jaybird contact us on {firebird-java}[firebird-java^], for Firebird in general, use the https://groups.google.com/g/firebird-devel[Firebird-devel^] mailing list)
* Donate to the Firebird Foundation (see https://firebirdsql.org/en/donate/)
* Become a paying Associate, Partner or sponsor of the Firebird Foundation (see https://firebirdsql.org/en/firebird-foundation/)

[#reporting-bugs]
== Reporting Bugs

The developers follow the {firebird-java}[firebird-java Google Group^].
Join the list and post information about suspected bugs.
List members may be able to help out to determine if it is an actual bug, provide a workaround and get you going again, whereas bug fixes might take a while.

You can report bugs in the Jaybird bug tracker, {issues}.

When reporting bugs, please provide a minimal, but complete reproduction, including databases and sourcecode to reproduce the problem.
Patches to fix bugs are also appreciated.
Make sure the patch is against a recent master version of the code.
You can also fork the {jaybird-repo}[Jaybird repository] and create pull requests.

[#connecting-to-firebird]
= Connecting to Firebird

For more in-depth information on connecting to Firebird using Jaybird, see chapter {jaybird-manual}#connection[Obtaining a connection] in the _Jaybird JDBC Driver Java Programmer’s Manual_.

[[jdbc-urls-java.sql.DriverManager]]
== JDBC URLs (`java.sql.DriverManager`)

[#pure-java-default]
=== Pure Java (default)

Default URL format:

[listing]
----
jdbc:firebird://host[:port]/<database>
jdbc:firebirdsql://host[:port]/<database>
----

This will connect to the database using the Type 4 JDBC driver using the Java implementation of the Firebird wire-protocol.
This is best suited for client-server applications with dedicated database server.
Port can be omitted (default value is `3050`), host name must be present.

The `<host>` part is either the hostname, the IPv4 address, or the IPv6 address in brackets (eg `[::1]`).
Use of IPv6 address literals is only supported with Firebird 3.0 or higher.

The `<database>` part should be replaced with the database alias or the path to the database.
In general, it is advisable to use database aliases instead of the path of the database file as it hides implementation details like file locations and OS type.

On Linux the root `/` should be included in the path.
A database located on `/opt/firebird/db.fdb` should use (note the double slash after port!):

[source]
----
jdbc:firebird://host:port//opt/firebird/db.fdb
----

Deprecated, but still supported legacy URL format:

[listing]
----
jdbc:firebird:host[/port]:<database>
jdbc:firebirdsql:host[/port]:<database>
----

The legacy URL format does not support IPv6 address literals.

[#open-officelibre-office-pure-java]
=== OpenOffice/LibreOffice (Pure Java)

Jaybird 5 and earlier can be used together with OpenOffice and LibreOffice Base.
To address some compatibility issues (and differences in interpretation of JDBC specifications) a separate sub-protocol is used:

[listing]
----
jdbc:firebird:oo://host[:port]/<database>
jdbc:firebirdsql:oo://host[:port]/<database>
----

[NOTE]
====
This URL format is deprecated with Jaybird 5 and was removed in Jaybird 6.
As a replacement, use the "`Firebird External`" option in LibreOffice Base.

See also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2022-04-deprecate-ooremote.md[jdp-2022-04: Deprecate OOREMOTE (OpenOffice/LibreOffice driver) for removal].
====

[#native-using-firebird-client-library]
=== Native (using Firebird client library)

Default URL format:

[listing]
----
jdbc:firebird:native://host[:port]/<database>
jdbc:firebirdsql:native://host[:port]/<database>
----

Legacy URL format:

[listing]
----
jdbc:firebird:native:host[/port]:<database>
jdbc:firebirdsql:native:host[/port]:<database>
----

Type 2 driver, will connect to the database using client library (`fbclient.dll` on Windows, and `libfbclient.so` on Linux).
Requires correct installation of the client library and the JNA jar file.

[NOTE]
====
As of Jaybird 5, the separate "`LOCAL`" protocol implementation has been removed.
The JDBC URL sub-protocols `jdbc:firebird:local` and `jdbc:firebirdsql:local` are still supported but are now aliases for "```native```".
====

[#embedded-server]
=== Embedded Server

[listing]
----
jdbc:firebird:embedded:<database>
jdbc:firebirdsql:embedded:<database>
----

Similar to the Firebird client library, however `fbembed.dll` on Windows and `libfbembed.so` on Linux are used, falling back to `fbclient.dll`/`libfbclient.so` under the assumption it provides Embedded functionality.
Requires correctly installed and configured Firebird embedded library and the JNA jar file.

[#character-sets]
== Character sets

[#how-can-i-specify-the-connection-character-set]
=== How can I specify the connection character set?

Jaybird provides two connection properties to specify the connection character set:

* `charSet` with a Java character set name (aliases: `localEncoding`, `charset`)
+
The Java character set name must map to an equivalent Firebird character set.

* `encoding` with a Firebird character set name (alias: `lc_ctype`)
+
The Firebird character set name -- except `NONE` -- must map to an equivalent Java character set.

For most applications, use only *one* of these two properties, *not* both.

For special situations, it is possible to specify both `charSet` and `encoding` to convert/reinterpret a character set into another character set;
This is usually only necessary to fix data problems.

To phrase differently:

* `encoding=<firebird charset>`: use connection encoding `<firebird charset>` and interpret in the equivalent Java character set
* `charSet=<java charset>`: use Firebird equivalent of `<java charset>` as connection encoding and interpret in `<java charset>`
* `encoding=<firebird charset>&charSet=<java charset>`: use connection encoding `<firebird charset>`, but interpret in `<java charset>`

The handling of Firebird character set `NONE` is slightly different, see below.

[#how-does-character-set-none-work]
=== How does character set `NONE` work?

The Firebird character set `NONE` is a special case, it essentially means "`no character set`".
You can store anything in it, but conversions to or from this character set are not defined.

Using character set `NONE` can result in incorrect character set handling when the database is used from different locales.

When used as a connection character set, Jaybird handles `NONE` as follows:

* `encoding=NONE` means connection encoding `NONE` and interpret columns with character set `NONE` using the default JVM encoding, and interpret columns with an explicit character set in their equivalent Java character set
* `encoding=NONE&charSet=ISO-8859-1` the same, but instead of the JVM default, use `ISO-8859-1`

[#what-happens-if-no-connection-character-set-is-specified]
=== What happens if no connection character set is specified?

When no character set has been specified explicitly, Jaybird defaults to connection character set `NONE`.
See <<how-does-character-set-none-work>> for details on character set `NONE`.

It is possible to override the default connection character set by specifying system property `org.firebirdsql.jdbc.defaultConnectionEncoding` with a valid Firebird character set name.

The system property `org.firebirdsql.jdbc.requireConnectionEncoding` -- when set to `true` -- will reject connections without a character set.

[#how-can-i-solve-the-error-connection-rejected-no-connection-character-set-specified]
=== How can I solve the error "Connection rejected: No connection character set specified"

If no character set has been set, Jaybird may reject the connection with an `SQLNonTransientConnectionException` with message _"Connection rejected: No connection character set specified (property lc_ctype, encoding, charSet or localEncoding).
Please specify a connection character set (e.g. property charSet=utf-8) or consult the Jaybird documentation for more information."_

This error will only be thrown if system property {jaybird-manual}#systemproperties-charset[`org.firebirdsql.jdbc.requireConnectionEncoding`] has been set to `true`.

To address this error, you can set the default connection character set using one of the following options:

* Use connection property `encoding` (alias: `lc_ctype`) with a Firebird character set name.
+
Use `encoding=NONE` for the default behaviour (with some caveats, see <<how-does-character-set-none-work,How does character set `NONE` work?>>).
* Use connection property `charSet` (aliases: `localEncoding`, `charset`) with a Java character set name.
* Use a combination of `encoding` and `charSet`, if you want to reinterpret a Firebird character set in a Java character set other than the default mapping.
* By providing a default Firebird character set with system property {jaybird-manual}#systemproperties-charset[`org.firebirdsql.jdbc.defaultConnectionEncoding`].
Jaybird will apply the specified character set as the default when no character set is specified in the connection properties.
+
This property only supports Firebird character set names.
+
Use `-Dorg.firebirdsql.jdbc.defaultConnectionEncoding=NONE` to revert to the default behaviour (with some caveats, see <<how-does-character-set-none-work>>).
However, it is better to just not set system property `org.firebirdsql.jdbc.requireConnectionEncoding` if you want to apply `NONE` as the default.

[#how-can-i-enable-the-windows-tcp-loopback-fast-path-introduced-in-firebird-3-0-2]
== How can I enable the Windows "TCP Loopback Fast Path" introduced in Firebird 3.0.2?

[CAUTION]
====
Microsoft has deprecated the `SIO_LOOPBACK_FAST_PATH` and recommends not to use it.

Support was removed in Firebird 5.0.
====

Firebird 3.0.2 added support for "`TCP Loopback Fast Path`" (`SIO_LOOPBACK_FAST_PATH` socket option);
support was removed in Firebird 5.0.
This is available in Windows 8 / Windows Server 2012 and higher.
This feature enables performance optimizations when connecting through localhost (127.0.0.1 / ::1).
It requires support on both client and server side.

Java support for "`TCP Loopback Fast Path`" was introduced in Java 8 update 60, it can be enabled by specifying the system property `jdk.net.useFastTcpLoopback` with value `true` (e.g. specify `-Djdk.net.useFastTcpLoopback=true` in your Java commandline).

Unfortunately, Java only has an 'all-or-nothing' support for the "`TCP Loopback Fast Path`", so Jaybird cannot enable this for you: you must specify this property on JVM startup.
On the other hand, this has the benefit that this works for all Jaybird versions, as long as you use Java 8 update 60 or higher (and Firebird 3.0.2 or higher, but before 5.0.0).

[#common-connection-errors]
== Common connection errors

[#error-isc-login]
=== Your user name and password are not defined. Ask your database administrator to set up a Firebird login. (335544472) [[your-user-name-and-password-are-not-defined-ask-your-database-administrator-to-set-up-a-firebird-login.-335544472]] [

This error means that the user does not exist, or that the specified password is not correct.

The following are common causes authentication can fail with the same error even if the username and password are correct.

==== Cause: authentication plugin mismatch

When connecting to Firebird 3.0 and higher, this error can also mean that the user does exist (with that password), but not for the authentication plugins tried for this connection.
The list of authentication plugins tried is the conjunction of the plugins offered by the client (connection property {jaybird-manual}#ref-auth-plugins-config[`authPlugins`]) and the {firebird-conf-ref}#fbconf-auth-server[`AuthServer`] setting in _firebird.conf_.

For example, Jaybird -- by default -- only connects using the _Srp256_ and _Srp_ authentication plugins, which means only users created with the _Srp_ user manager can be authenticated, and users created with _Legacy_UserManager_ cannot be authenticated.
The recommended solution is to create the user for the _Srp_ user manager (e.g. see https://firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref50/fblangref50-security-user.html#fblangref50-security-user-create[Firebird 5.0 `CREATE USER`^], specifically the `USING PLUGIN ...` clause).
Alternatively, you can set connection property `authPlugins` to `Srp256,Srp,Legacy_Auth` to also try legacy authentication, see also {jaybird-manual}#ref-auth-plugins[Authentication plugins] in the Jaybird manual.

You can check -- as `SYSDBA`, or with `RDB$ADMIN` in the security database -- what user manager(s) were used to create a user in the `SEC$USERS` virtual table.

==== Cause: case-sensitive username

With Firebird 3.0 and higher, this error can also be the result of using a case-sensitive username (i.e. the username was quoted, e.g. `CREATE USER "lowercaseuser" ...`).

To login, you must surround the username with quotes so it's handled case-sensitive.
In a Java string literal, that means using `"\"lowercaseuser\""` instead of `"lowercaseuser"`.

[#error-isc-wirecrypt-incompatible]
=== Incompatible wire encryption levels requested on client and server (335545064) [[incompatible-wire-encryption-levels-requested-on-client-and-server-335545064]]

This error means that you have requested a connection with a mismatch in encryption settings.
For example, you specified connection property {jaybird-manual}#ref-wirecrypt[`wireCrypt=required`] while Firebird is set to `WireCrypt = Disabled` (or vice versa).

[#error-isc-connect-reject]
=== connection rejected by remote interface (335544421) [[connection-rejected-by-remote-interface-335544421]]

In general this error means that Jaybird requested a connection with properties not supported by Firebird.
It can have other causes than described below.

[#cause-username-or-password-is-null]
==== Cause: username or password is null

With -- no longer supported -- Jaybird 3 and Jaybird 4 connecting to Firebird 3.0 or higher, leaving username or password null will lead to Jaybird not trying any authentication plugin, and as a result Firebird will reject the connection.

In supported Jaybird versions, this situation will yield error "`Your user name and password are not defined. Ask your database administrator to set up a Firebird login.`"

[#cause-wirecrypt-required]
==== Cause: wirecrypt required

With -- no longer supported -- Jaybird 2.2.x connecting to Firebird 3.0 or higher, this usually means that the setting {firebird-conf-ref}#fbconf-wire-crypt[`WireCrypt`] is set to its (default) value of `Required`.

Relax this setting (in `firebird.conf`) to `WireCrypt = Enabled`.

See also https://github.com/FirebirdSQL/jaybird/wiki/Jaybird-and-Firebird-3[Jaybird Wiki -- Jaybird and Firebird 3].

Make sure you check the other settings mentioned in that article, otherwise you'll get another error (<<error-occurred-during-login-please-check-server-firebird-log-for-details-335545106>>).

[#cause-unsupported-protocol]
==== Cause: unsupported protocol version

Since Jaybird 6, protocol versions of unsupported Firebird versions are no longer tried by default with pure Java connections.
Connecting to an unsupported Firebird version with the pure Java protocol can result in this error.

There are two options to address this:

. Specify connection property {jaybird-manual}#ref-enable-protocol[`enableProtocol`] with a list of unsupported protocol versions to try in addition to the supported protocol versions, or `"{asterisk}"` to try all available protocol versions (e.g. `enableProtocol=12` to try protocol 12 (Firebird 2.5) or `enableProtocol={asterisk}` to try all unsupported protocols).
. Use a native connection instead of a pure Java connection.

Be aware that Jaybird is not guaranteed to function correctly on unsupported Firebird versions.

[#error-isc-login-error]
=== Error occurred during login, please check server firebird.log for details (335545106) [[error-occurred-during-login-please-check-server-firebird-log-for-details-335545106]]

If the logging contains something like

[listing]
----
SERVER	Sat Oct 28 10:07:26 2017
	Authentication error
	No matching plugins on server
----

With -- no longer supported -- Jaybird 2.2 connecting to Firebird 3.0 or higher, this means that the setting {firebird-conf-ref}#fbconf-auth-server[`AuthServer`] does not include the `Legacy_Auth` plugin.
Enable `Legacy_Auth` (in `firebird.conf`) by adding this value to the property  `AuthServer`, for example: `AuthServer = Srp, Legacy_Auth`.
You also need to make sure your user is created with the legacy user manager, see https://github.com/FirebirdSQL/jaybird/wiki/Jaybird-and-Firebird-3[Jaybird Wiki -- Jaybird and Firebird 3] for details.

With supported Jaybird versions, this can also mean that none of the default authentication plugins, or those specified using connection property {jaybird-manual}#ref-auth-plugins-config[`authPlugins`], are listed in the `AuthServer` setting.
Either revise the Firebird configuration, or explicitly configure connection property `authPlugins` with authentication plugins that are configured in Firebird.

[#error-jb-crypt-invalid-key]
=== Encryption key did not meet algorithm requirements of Symmetric/Arc4 (337248282) [[encryption-key-did-not-meet-algorithm-requirements-of-symmetricarc4-337248282]]

If the exception cause is "`__java.security.InvalidKeyException: Illegal key size or default parameters__`", this means that your Java installation applies a security policy that does not allow ARCFOUR encryption with a 160 bit encryption key.

If {jaybird-manual}#ref-wirecrypt[`wireCrypt=ENABLED`] (the default), this is just logged as a warning.
The connection will succeed, but it does mean that the connection will not be encrypted.
If `wireCrypt=REQUIRED`, this is thrown as an exception, and the connection will fail.

This could indicate that your Java version applies the limited strength Cryptographic Jurisdiction Policy (this was the default in Java 8 Update 152 and earlier).
Alternatively, it has been explicitly configured to apply the limited policy, or has a custom security policy to restrict the cryptographic key size.

Solutions and workarounds:

* Apply the unlimited Cryptographic Jurisdiction Policy, see https://stackoverflow.com/a/3864276/466862[this Stack Overflow answer]
* Relax your custom security policy to allow 160 bit keys for ARCFOUR
* Disable wire encryption for Firebird by setting `WireCrypt = Disabled` in `firebird.conf`
* Set `wireCrypt=DISABLED` in the connection properties

[#jdbc-support]
= JDBC Support

Supported Jaybird versions -- Jaybird 5 and Jaybird 6 -- support the following JDBC Specification versions:

* https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index2.html[JDBC 4.2^] (Java 8) -- Jaybird 5 onlyfootnote:[Jaybird 6 doesn't support JDBC 4.2 as it doesn't support Java 8, but everything defined in JDBC 4.2 is also defined in JDBC 4.3.]
* https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index3.html[JDBC 4.3^] (Java 9 - Java 23)
* https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index4.html[JDBC 4.4^] (Java 24 - Java 25) -- see caveats in <<jdbc44-support>>
* https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index5.html[JDBC 4.5^] (Java 26 and higher) -- see also <<jdbc45-support>>

[#jdbc44-support]
== Is JDBC 4.4 supported?

Yes, https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index4.html[JDBC 4.4^] is supported by Jaybird 5 and Jaybird 6, with some minor caveats. +
No -- for Jaybird 4 and older.

JDBC 4.4 was introduced with Java 24.
The only change in JDBC 4.4 was the removal of the requirement for `SQLPermission` checks, given `SecurityManager` support was removed in Java 24.

There are two caveats to this support:

* Jaybird still has the code for performing the permission checks to be compliant with the https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index3.html[JDBC 4.3 Specification^] on Java 23 and older.
+
As such, the JDBC 4.4 compliance of Jaybird currently relies on Java 24 and higher still having the `SQLPermission` class, and `System.getSecurityManager()` always returning `null`.
This may break and need additional work once a Java version is released where this class or this method are removed.
* Jaybird 6.0.0 - 6.0.2 are broken on Java 24 and higher due to the way the permission check is performed in those versions.
+
This is fixed in Jaybird 6.0.3 and higher (see https://github.com/FirebirdSQL/jaybird/issues/890[#890]).

[#jdbc45-support]
== Is JDBC 4.5 supported?

Yes, https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index5.html[JDBC 4.5^] is supported by Jaybird 5.0.12 and higher, and Jaybird 6.0.5 and higher.
No -- for Jaybird 5.0.11 and older, and Jaybird 6.0.4 and older.

JDBC 4.5 was introduced with Java 26.

Notable changes -- for Jaybird and Firebird -- are:

* Introduction of `java.sql.JDBCType.DECFLOAT` and `java.sql.Types.DECFLOAT` (value `2015`).
* Introduction of new methods on `java.sql.Connection` -- `enquoteIdentifier`, `enquoteLiteral`, `enquoteNCharLiteral`, and `isSimpleIdentifier`
* The JDBC escape to selectively disable escape processing ([.nowrap]`++{\ ... \}++`)

[#how-much-of-jdbc-is-supported-by-jaybird]
== How much of JDBC is supported by Jaybird?

*WARNING* The information in this section is not 100% up-to-date

Jaybird 6 follows the https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index3.html[JDBC 4.3 Specification^], https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index4.html[JDBC 4.4 Specification^]footnote:[JDBC 4.4 was only a Java/javadoc change, and has no published Specification document, refer to JDBC 4.3 for that], and https://jcp.org/aboutJava/communityprocess/mrel/jsr221/index5.html[JDBC 4.5 Specification^]footnote:[The full specification document has not been published yet, refer to JDBC 4.3 for that] with some features and methods not implemented as they are not supported by Firebird.

Implemented features:

* Most useful JDBC functionality ("`useful`" in the opinion of the developers).
* XA transactions with true two phase commit when used via `javax.sql.XADataSource` implementation `org.firebirdsql.ds.FBXADataSource`.
* `ObjectFactory` implementation `org.firebirdsql.ds.DataSourceFactory` for use in environments with JNDI but no `TransactionManager`.
* `DataSource` implementation `org.firebirdsql.ds.FBSimpleDataSource` (no pooling).
* `ConnectionPoolDataSource` implementation `org.firebirdsql.ds.FBConnectionPoolDataSource` (please be aware, contrary to suggested by the naming, this does not provide connection pooling, this is intended as a factory of connections for use by a connection pool, e.g. as provided by a Java EE/Jakarta EE application server)
* Complete access to all Firebird database parameter block and transaction parameter block settings.

[#what-parts-of-jdbc-are-not-supported-by-jaybird]
== What parts of JDBC are NOT supported by Jaybird?

*WARNING* The information in this section is outdated

The following optional features are NOT supported:

The following optional features and the methods that support it are not implemented:

* Ref and Array types.
** `java.sql.PreparedStatement`
*** `setRef(int i, Ref x)`
*** `setArray(int i, Array x)`
** `java.sql.ResultSet`
*** `getArray(int i)`
*** `getArray(String columnName)`
*** `getRef(int i)`
*** `getRef(String columnName)`
* User Defined Types/Type Maps.
** `java.sql.ResultSet`
*** `getObject(int i, java.util.Map map)`
*** `getObject(String columnName, java.util.Map map)`
** `java.sql.Connection`
*** `getTypeMap()`
*** `setTypeMap(java.util.Map map)`

Excluding the unsupported features, the following methods are not implemented:

* `java.sql.Blob`
** `position(byte pattern[], long start)`
** `position(Blob pattern, long start)`
** `getBinaryStream(long pos, long length)`
** `truncate(long len)`
* `java.sql.Clob`
** `length()`
** `truncate(long len)`
** `position(String searchstr, long start)`
** `position(Clob searchstr, long start)`
** `getCharacterStream(long pos, long length)`

The following methods are implemented, but do not work as expected:

* `java.sql.Statement`
** `get/setMaxFieldSize` -- Does nothing (support will be introduced in Jaybird 7)
* `java.sql.PreparedStatement`
** `setObject(index,object,type)` -- This method is implemented but behaves as `setObject(index,object)`
** `setObject(index,object,type,scaleOrLength)` -- This method is implemented ,but behaves as `setObject(index,object)`, except if `object` is a `Reader` or `InputStream`, then it is directed to the `setBinaryStream` or `setCharacterStream` method accepting a length.
* `java.sql.CallableStatement`
** `getBigDecimal(index,scale)` -- This method is implemented but behaves as `getBigDecimal(index)`.
The method is deprecated, and we suggest using `getBigDecimal(index)` and adjust the scale of the returned `BigDecimal` using `BigDecimal.setScale(newScale,roundingMode)`
* `java.sql.ResultSetMetaData`
** `isReadOnly(i)` -- always returns `false`
** `isWritable(i)` -- always returns `true`
** `isDefinitivelyWritable(i)` -- always returns `true`
* `java.sql.ResultSet`
** `getBigDecimal(index,scale)` -- This method is implemented but behaves as `getBigDecimal(index)`.
The method is deprecated, and we suggest using `getBigDecimal(index)` and adjust the scale of the returned `BigDecimal` using `BigDecimal.setScale(newScale,roundingMode)`

[#features]
= Features

[#does-jaybird-support-connection-pooling]
== Does Jaybird support connection pooling?

No, Jaybird itself no longer provides connection pooling.
Earlier versions had a `DataSource` implementation with connection pooling, but this implementation had severe bugs.
This implementation (and all other classes in `org.firebirdsql.pool`) was deprecated in Jaybird 2.2 and removed in Jaybird 3.

Jaybird provides:

a basic `DataSource`::
`org.firebirdsql.ds.FBSimpleDataSource`
an `XADataSource`::
`org.firebirdsql.ds.FBXADataSource`
a `ConnectionPoolDataSource`::
`org.firebirdsql.ds.FBConnectionPoolDataSource`

Contrary to suggested by its name, the latter *does not provide a connection pool*!
It is intended to be used by a connection pool (as implemented in an application server) to create connections _for_ a connection pool.

If your application is built on a Java EE/Jakarta EE application server, we suggest you use the connection pooling provided by the application server using the `javax.sql.ConnectionPoolDataSource` implementation `org.firebirdsql.ds.FBConnectionPoolDataSource`, or using the `javax.sql.XADataSource` implementation `org.firebirdsql.ds.FBXADataSource`.

If you develop standalone applications, or you use an application server without connection pooling, we suggest you use third-party libraries like:

* https://github.com/brettwooldridge/HikariCP[HikariCP^]
* https://www.mchange.com/projects/c3p0/[c3p0^]
* https://commons.apache.org/proper/commons-dbcp/[Apache DBCP^]

[#compatibility-notes]
= Compatibility notes

[#wildfly]
== Wildfly

The minimal `module.xml` to use Jaybird 3 under Wildfly is:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.firebirdsql">
  <resources>
    <resource-root path="jaybird-3.0.x.jar"/>
  </resources>
  <dependencies>
    <module name="javax.api"/>
    <module name="javax.transaction.api"/>
    <module name="javax.resource.api"/>
  </dependencies>
</module>
----

With Jaybird 3.0.4 and higher for Java 7 (but not Java 8!) in Wildfly (or JBoss), you will need to add the module `javax.xml.bind.api` to your module:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.firebirdsql">
  <resources>
    <resource-root path="jaybird-3.0.x.jar"/>
  </resources>
  <dependencies>
    <module name="javax.api"/>
    <module name="javax.transaction.api"/>
    <module name="javax.resource.api"/>
    <module name="javax.xml.bind.api"/> <!-- Add this -->
  </dependencies>
</module>
----

Alternatively, use Jaybird for Java 8 (or higher).

[appendix#license-notice]
== License Notice

The contents of this Documentation are subject to the Public Documentation License Version 1.0 (the “License”);
you may only use this Documentation if you comply with the terms of this License.
A copy of the License is available at https://firebirdsql.org/en/public-documentation-license/.

The Original Documentation is "`Jaybird Frequently Asked Questions`".
The Initial Writer of the Original Documentation is Mark Rotteveel, Copyright © 2013-2026.
All Rights Reserved.
(Initial Writer contact(s): mark (at) lawinegevaar (dot) nl).

Contributor(s): Rick Fincher. +
Portions created by Rick Fincher are Copyright © 2002-2004.
All Rights Reserved.
(Contributor contact(s): _unknown_).

The exact file history is recorded in our Git repository;
see https://github.com/FirebirdSQL/jaybird
