= Jaybird Frequently Asked Questions
:doctype: book
:docinfo:
:sectanchors:
:forceinclude: true
:keywords: jaybird, firebird, jdbc, sql, database, java
:source-highlighter: prettify
:toc: left
:icons: font
:jaybird5-full-version: 5.0.3
:jaybird5-template-version: {jaybird5-full-version}.<java>
:jaybird5-example-version: {jaybird5-full-version}.java11
:jaybird4-full-version: 4.0.10
:jaybird4-template-version: {jaybird4-full-version}.<java>
:jaybird4-example-version: {jaybird4-full-version}.java11
:jaybird3-full-version: 3.0.12
:sectnums:

[#jaybird]
= Jaybird

[#where-do-i-get-jaybird]
== Where do I get Jaybird?

[#maven]
=== Maven

[#jaybird-5]
==== Jaybird 5

Jaybird 5 is available on Maven Central:

[horizontal]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird`,
version:: `{jaybird5-template-version}` (where `<java>` is `java11` or `java8`)

Contrary to Jaybird 4, a Maven relocation artifact with artifact id `jaybird-XX` (with `XX` `jdk17`, `jdk18`) is no longer provided.
Please make sure you use the `jaybird` artifactId.

For example, for Java 11:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>{jaybird5-example-version}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), you need to explicitly include JNA 5.12.1 as a dependency:

[source,xml]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>5.12.1</version>
</dependency>
----

[#jaybird-4]
==== Jaybird 4

Jaybird 4 is end-of-life and will receive no further updates.
We recommend upgrading to <<jaybird-5>>.

Jaybird 4 is available from Maven Central:

[horizontal]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird`
version:: `{jaybird4-template-version}` (where `<java>` is `java11`, `java8` or `java7`)

For backwards compatibility, we also provide a Maven relocation artifact with artifact id `jaybird-XX` (with `XX` `jdk17` or `jdk18`.
However, we recommend switching to the `jaybird` artifact.

For example, for Java 11:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>{jaybird4-example-version}</version>
</dependency>
----

If your application is deployed to a Java EE application server, you will need to exclude the `javax.resource:connector-api` dependency, and add it as a provided dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>{jaybird4-example-version}</version>
    <exclusions>
        <exclusion>
            <groupId>javax.resource</groupId>
            <artifactId>connector-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>javax.resource</groupId>
    <artifactId>connector-api</artifactId>
    <version>1.5</version>
    <scope>provided</scope>
</dependency>
----

If you want to use Type 2 support (native, local or embedded), you need to explicitly include JNA 5.5.0 as a dependency:

[source,xml]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>5.5.0</version>
</dependency>
----

[#jaybird-3-0]
==== Jaybird 3

// For GitHub markdown compatibility

+++<a name="jaybird-3.0">++++++</a>+++

Jaybird 3 is end-of-life and will receive no further updates.
We recommend upgrading to <<jaybird-5>>.

////
// Stop showing Jaybird 3 Maven info, but keep available for now
Jaybird 3 is available from Maven Central:

[horizontal]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird-XX` (where `XX` is `jdk18` or `jdk17`)
version:: `{jaybird3-full-version}`

For ease of use, we also provide a Maven relocation artifact with artifact id `jaybird`.
For Jaybird 3 this relocation artifact points to `jaybird-jdk18`.

For example, for Java 8:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-jdk18</artifactId>
    <version>{jaybird3-full-version}</version>
</dependency>
----

If your application is deployed to a Java EE application server, you will need to exclude the `javax.resource:connector-api` dependency, and add it as a provided dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-jdk18</artifactId>
    <version>{jaybird3-full-version}</version>
    <exclusions>
        <exclusion>
            <groupId>javax.resource</groupId>
            <artifactId>connector-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>javax.resource</groupId>
    <artifactId>connector-api</artifactId>
    <version>1.5</version>
    <scope>provided</scope>
</dependency>
----

If you want to use Type 2 support (native, local or embedded), you need to  explicitly include JNA 4.4.0 as a dependency:

[source,xml]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>4.4.0</version>
</dependency>
----

////

[#jaybird-2-2]
==== Jaybird 2.2

Jaybird 2.2 is end-of-life and will receive no further updates.
We recommend upgrading to <<jaybird-5>>.

////
// Stop showing Jaybird 2.2 Maven info, but keep available for now
Jaybird 2.2 is available on Maven, with a separate artifact for each supported Java version.

[horizontal]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird-XX` (where `XX` is `jdk16`, `jdk17` or `jdk18`)
version:: `2.2.15`

For ease of use, we also provide a Maven relocation artifact with artifact id `jaybird`.
For Jaybird 2.2 this relocation artifact points to `jaybird-jdk17`.

For example:

[source,xml]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-jdk18</artifactId>
    <version>2.2.15</version>
</dependency>
----

When deploying to a JavaEE environment, exclude the `javax.resource connector-api` dependency as this will be provided by the application server.
////

[#download]
=== Download

Firebird can be downloaded from the Firebird website, under Downloads, https://www.firebirdsql.org/en/jdbc-driver/[JDBC Driver].

Alternatively, you can go directly to GitHub and download Jaybird from the https://github.com/FirebirdSQL/jaybird/releases[jaybird releases].

[#where-can-i-get-the-sourcecode]
== Where can I get the sourcecode?

All Jaybird distribution zips contain a `jaybird-<version>-sources.zip` with the sources used for that specific version.
The full Jaybird sourcecode is also available from GitHub in the jaybird repository:

https://github.com/FirebirdSQL/jaybird

Each release is also tagged in the repository.

[#how-is-jaybird-licensed]
== How is Jaybird licensed?

Jaybird JDBC driver is distributed under the GNU Lesser General Public License (LGPL).
Text of the license can be obtained from http://www.gnu.org/copyleft/lesser.html.

Using Jaybird (by importing Jaybird's public interfaces in your Java code), and extending Jaybird by subclassing or implementation of an extension interface (but not abstract or concrete class) is considered by the authors of Jaybird to be dynamic linking.
Hence, our interpretation of the LGPL is that the use of the unmodified Jaybird source does not affect the license of your application code.

Even more, all extension interfaces to which an application might want to link are released under dual LGPL/modified BSD license.
Latter is basically "AS IS" license that allows any kind of use of that source code.
Jaybird should be viewed as an implementation of that interfaces and the LGPL section for dynamic linking is applicable in this case.

[#which-version-of-the-lgpl-applies]
=== Which version of the LGPL applies?

Current releases of Jaybird do not explicitly specify an LGPL version.
This means that you can choose which version applies.
Future versions of Jaybird may specify an explicit version, or be released under a different license.

[#which-java-versions-are-supported]
== Which Java versions are supported?

[#java-jaybird-5]
[discrete]
=== Jaybird 5

Jaybird 5 supports Java 8, 11, 17 and 21.
Support for Java 9 and higher is limited to Java 8, 11, 17, 21 and the most recent LTS version after Java 21 and the latest Java release.

Jaybird 5 is the last version to support Java 8 and 11, support will be dropped with Jaybird 6, raising the minimum supported version to Java 17.

[NOTE]
====
Jaybird 5 will serve as a form of long-term support for Java 8 and 11, with maintenance releases guaranteed at least until the release of Jaybird 7.

See also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2022-03-java-17-minimum-version.md[jdp-2022-03: Java 17 minimum version].
====

[#java-jaybird-4]
[discrete]
=== Jaybird 4

Jaybird 4 supports Java 7, 8, 11, 17 and 21.
Support for Java 9 and higher is limited to Java 11, 17 and 21.

Jaybird 4 is the last version to support Java 7, support will be dropped with Jaybird 5.
Jaybird 4.0.10 is the last release of Jaybird 4, and is end-of-life.
We recommend upgrading to Jaybird 5.

[#java-jaybird-3-0]
[discrete]
=== Jaybird 3

Jaybird 3 supports Java 7 and 8 and has basic support for Java 9 and higher using the Java 8 version of the driver.
Support for Java 9 and higher is limited to Java 11 and 17, but in practice Jaybird should work on all Java 9+ versions upto Java 17 (versions after Java 17 have not been tested).
Jaybird 3.0.12 is the last release of Jaybird 3, and is end-of-life.
We recommend upgrading to Jaybird 5.

[#java-jaybird-2-2]
[discrete]
=== Jaybird 2.2

Jaybird 2.2 supports Java 6, 7 and 8.
Jaybird 2.2.15 is that last release of Jaybird 2.2, and is end-of-life.
We recommend upgrading to Jaybird 5.

Jaybird 2.2.4 added basic support for Java 8 (JDBC 4.2), although not all JDBC 4.2 features are supported or fully implemented.

Jaybird 2.2.7 is the last version to support Java 5, support has been dropped with Jaybird 2.2.8.

Jaybird 2.2 is the last version to support Java 6, support has been dropped with Jaybird 3.

[#what-is-the-java-9-module-name-for-jaybird]
== What is the Java 9 module name for Jaybird?

Jaybird itself is not (yet) modularized.
To ensure a stable module name, Jaybird, since 2.2.14 and 3.0.3, declares the automatic module name `org.firebirdsql.jaybird`.

Jaybird 6 will be modular.

[#which-firebird-versions-are-supported]
== Which Firebird versions are supported?

[#firebird-jaybird-5]
[discrete]
=== Jaybird 5

Jaybird 5 supports Firebird version 2.5, 3.0 and 4.0, and provides tentative support for Firebird 5.0.
Firebird 5.0 will become fully supported in the first release after Firebird 5.0.0.

Jaybird 5 is the last version to support Firebird 2.5.
Future versions of Jaybird are not guaranteed to work with version 2.5 and earlier.

[#firebird-jaybird-4]
[discrete]
=== Jaybird 4

Jaybird 4 supports Firebird version 2.5, 3.0 and 4.0, and introduces support for Firebird 4.0 types `DECLOAT`, extended precision of `NUMERIC` and `DECIMAL`, and time zone types (`TIME WITH TIME ZONE` and `TIMESTAMP WITH TIME ZONE`).

Jaybird 4 only provides partial support for Firebird 5.0, and the generated-keys support does not work in all cases due to Firebird 5.0 now supporting multi-row `RETURNING`.
Full Firebird 5.0 support is available in Jaybird 5.

[#firebird-jaybird-3-0]
[discrete]
=== Jaybird 3

Jaybird 3 supports Firebird versions 2.0 - 4.0.
Support for Firebird 4.0 is limited to the Firebird 3.0 feature set.
Formally, Firebird 5.0 is not supported, though in practice the problems are similar as for Jaybird 4.

Jaybird 3 is the last version to support Firebird 2.0 and 2.1.
Future versions of Jaybird are not guaranteed to work with version 2.1 and earlier.

[#firebird-jaybird-2-2]
[discrete]
=== Jaybird 2.2

Jaybird 2.2 supports Firebird versions 1.0 - 4.0.
Jaybird 2.2.4 added support for new features of Firebird 3.0 (e.g. `BOOLEAN` support).
Support for Firebird 4 is limited to the Firebird 3.0 feature set.

Jaybird 2.2 is the last version to support Firebird 1.0 and 1.5.
Future versions of Jaybird are not guaranteed to work with these versions.

[#can-jaybird-connect-to-interbase]
== Can Jaybird connect to Interbase?

Jaybird does not support Interbase, and as far as we know connecting to Interbase 6.0 and later will fail due to Firebird specific changes in the implementation.

== Can Jaybird be used on Android

Jaybird does not work on Android.
It uses classes and Java features which are not available on Android.

Instead, we recommend building a webservice (e.g. REST-based) to mediate between your Android application and the database.

[#documentation-and-support]
= Documentation and Support

[#where-to-get-more-information-on-jaybird]
== Where to get more information on Jaybird

Apart from this FAQ, you can get additional information from:

* https://firebirdsql.github.io/jaybird-manual/jaybird_manual.html[Jaybird JDBC Driver Java Programmer's Manual] (HTML, https://firebirdsql.github.io/jaybird-manual/jaybird_manual.pdf[PDF version]) (covers Jaybird 2.2 and higher)
* https://www.firebirdsql.org/en/devel-jdbc-driver/[Firebird Website: Development, JDBC Driver]
* https://github.com/FirebirdSQL/jaybird/wiki/[Jaybird wiki]

For version specific details, consult the release notes

* https://www.firebirdsql.org/file/documentation/drivers_documentation/java/5.0.x/release_notes.html[Jaybird 5.0.x release notes]
* https://www.firebirdsql.org/file/documentation/drivers_documentation/java/4.0.x/release_notes.html[Jaybird 4.0.x release notes]
* https://www.firebirdsql.org/file/documentation/drivers_documentation/java/3.0.x/release_notes.html[Jaybird 3.0.x release notes]
* https://www.firebirdsql.org/file/documentation/drivers_documentation/java/2.2.x/release_notes.html[Jaybird 2.2.x release notes]

[#where-to-get-help]
== Where to get help

* On https://stackoverflow.com/[Stack Overflow], please tag your questions with _jaybird_ and _firebird_
* The https://groups.google.com/g/firebird-java[Firebird-Java group] and corresponding mailing list firebird-java@googlegroups.com
+
You can subscribe to the mailing list by sending an email to link:mailto:firebird-java+subscribe@googlegroups.com[firebird-java+subscribe@googlegroups.com]

* Looking for professional support of Jaybird?
Jaybird is now part of the https://tidelift.com/subscription/pkg/maven-org-firebirdsql-jdbc-jaybird?utm_source=maven-org-firebirdsql-jdbc-jaybird&utm_medium=referral&utm_campaign=docs[Tidelift subscription].
* The https://www.firebirdsql.org[Firebird project home page]
* Firebird support and other https://www.firebirdsql.org/en/mailing-lists/[Firebird mailing lists] for questions not directly related to Jaybird and java.

[#contributing]
== Contributing

There are several ways you can contribute to Jaybird or Firebird in general:

* Participate on the mailing lists (see https://www.firebirdsql.org/en/mailing-lists/)
* Report bugs or submit patches on the tracker (see <<reporting-bugs,Reporting Bugs>>)
* Create pull requests on GitHub (https://github.com/FirebirdSQL/jaybird)
* Become a developer (for Jaybird contact us on firebird-java, for Firebird in general, use the Firebird-devel mailing list)
* Donate to the Firebird Foundation (see https://www.firebirdsql.org/en/donate/)
* Become a paying member or sponsor of the Firebird Foundation (see https://www.firebirdsql.org/en/firebird-foundation/)

[#reporting-bugs]
== Reporting Bugs

The developers follow the https://groups.google.com/g/firebird-java[firebird-java Google Group].
Join the list and post information about suspected bugs.
List members may be able to help out to determine if it is an actual bug, provide a workaround and get you going again, whereas bug fixes might take a while.

You can report bugs in the Firebird bug tracker, https://github.com/FirebirdSQL/jaybird/issues/.

When reporting bugs, please provide a minimal, but complete reproduction, including databases and sourcecode to reproduce the problem.
Patches to fix bugs are also appreciated.
Make sure the patch is against a recent master version of the code.
You can also fork the jaybird repository and create pull requests.

[#connecting-to-firebird]
= Connecting to Firebird

[[jdbc-urls-java.sql.DriverManager]]
== JDBC URLs (`java.sql.DriverManager`)

[#pure-java-default]
=== Pure Java (default)

Default URL format:

 jdbc:firebirdsql://host[:port]/<database>

This will connect to the database using the Type 4 JDBC driver using the Java implementation of the Firebird wire-protocol.
This is best suited for client-server applications with dedicated database server.
Port can be omitted (default value is `3050`), host name must be present.

The `<host>` part is either the hostname, the IPv4 address, or the IPv6 address  in brackets (eg `[::1]`).
Use of IPv6 address literals is only supported in  Jaybird 3 or newer with Firebird 3 or newer.

The `<database>` part should be replaced with the database alias or the path to the database.
In general, it is advisable to use database aliases instead of the path of the database file as it hides implementation details like file locations and OS type.

On Linux the root `/` should be included in the path.
A database located on `/opt/firebird/db.fdb` should use (note the double slash after port!):

 jdbc:firebirdsql://host:port//opt/firebird/db.fdb

Deprecated, but still supported legacy URL format:

 jdbc:firebirdsql:host[/port]:<database>

The legacy URL format does not support IPv6 address literals.

Jaybird 4 and higher also support:

 jdbc:firebird://host[:port]/<database>
 jdbc:firebird:host[/port]:<database>

[#open-officelibre-office-pure-java]
=== Open Office/Libre Office (Pure Java)

Jaybird 5 and earlier can be used together with OpenOffice and LibreOffice Base.
To address some compatibility issues (and differences in interpretation of JDBC specifications) a separate sub-protocol is used:

 jdbc:firebirdsql:oo://host[:port]/<database>

Jaybird 4 and higher also support:

 jdbc:firebird:oo://host[:port]/<database>

[NOTE]
====
This URL format is deprecated with jaybird 5 and will be removed in Jaybird 6.
As a replacement, use the "`Firebird External`" option in LibreOffice Base.

See also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2022-04-deprecate-ooremote.md[jdp-2022-04: Deprecate OOREMOTE (OpenOffice/LibreOffice driver) for removal].
====

[#native-using-firebird-client-library]
=== Native (using Firebird client library)

Default URL format:

 jdbc:firebirdsql:native://host[:port]/<database>

Legacy URL format:

 jdbc:firebirdsql:native:host[/port]:<database>

Type 2 driver, will connect to the database using client library (`fbclient.dll` on Windows, and `libfbclient.so` on Linux).
Requires correct installation of the client library and -- for Jaybird 2.2 or earlier -- the Jaybird native library, or -- for Jaybird 3 and higher -- the JNA jar file.

 jdbc:firebirdsql:local:<database>

Type 2 driver in local mode.
Uses client library as in previous case, however will not use socket communication, but rather access database directly.
Requires correct installation of the client library and -- for Jaybird 2.2 or earlier --  the Jaybird native library, or -- for Jaybird 3 and higher -- the JNA jar file.

Jaybird 4 and higher also support:

 jdbc:firebird:native://host[:port]/<database>
 jdbc:firebird:native:host[/port]:<database>
 jdbc:firebird:local:<database>

[NOTE]
====
As of Jaybird 5, the separate "`LOCAL`" protocol implementation has been removed.
The JDBC URL sub-protocol `jdbc:firebirdsql:local` and `jdbc:firebird:local` are still supported but are now simply aliases for "```native```".
====

[#embedded-server]
=== Embedded Server

 jdbc:firebirdsql:embedded:<database>

Similar to the Firebird client library, however `fbembed.dll` on Windows and `libfbembed.so` on Linux are used, falling back to `fbclient.dll`/`libfbclient.so` under the assumption it provides Embedded functionality.
Requires correctly installed and configured Firebird embedded library and -- for Jaybird 2.2 or earlier -- the Jaybird native  library, or -- for Jaybird 3 and higher -- the JNA jar file.

Jaybird 4 and higher also support:

 jdbc:firebird:embedded:<database>

[#character-sets]
== Character sets

[#how-can-i-specify-the-connection-character-set]
=== How can I specify the connection character set?

Jaybird provides two connection properties to specify the connection character set:

* `charSet` with a Java character set name (alias: `localEncoding`)
+
The Java character set name must map to an equivalent Firebird character set.

* `encoding` with a Firebird character set name (alias: `lc_ctype`)
+
The Firebird character set name -- except `NONE` -- must map to an equivalent Java character set.

For most applications, use only one of these two properties.

For special situations it is possible to specify both `charSet` and `encoding` to convert/reinterpret a character set into another character set, this is usually only necessary to fix data problems.

To phrase differently:

* `encoding=<firebird charset>`: use connection encoding `<firebird charset>` and interpret in the equivalent Java character set
* `charSet=<java charset>`: use Firebird equivalent of `<java charset>` as connection encoding and interpret in `<java charset>`
* `encoding=<firebird charset>&charSet=<java charset>`: use connection encoding  `<firebird charset>`, but interpret in `<java charset>`

The handling of Firebird character set `NONE` is slightly different, see below.

[#how-does-character-set-none-work]
=== How does character set `NONE` work?

The Firebird character set `NONE` is a special case, it essentially means "`no character set`".
You can store anything in it, but conversions to or from this character set are not defined.

Using character set `NONE` can result in incorrect character set handling when the database is used from different locales.

When used as a connection character set, Jaybird handles `NONE` as follows:

[#none-jaybird3]
==== Jaybird 3 and higher

* `encoding=NONE` means connection encoding `NONE` and interpret columns with character set `NONE` using the default JVM encoding, and interpret columns with an explicit character set in their equivalent Java character set
* `encoding=NONE&charSet=ISO-8859-1` the same, but instead of the JVM default, use `ISO-8859-1`

[#none-jaybird2-2]
==== Jaybird 2.2 and earlier

* `encoding=NONE` means use connection encoding `NONE` and interpret everything using the default JVM encoding
* `encoding=NONE&charSet=ISO-8859-1` the same, but instead of the JVM default, use `ISO-8859-1`

[#what-happens-if-no-connection-character-set-is-specified]
=== What happens if no connection character set is specified?

When no character set has been specified explicitly, Jaybird 2.2 and earlier, and Jaybird 3.0.2 and higher default to connection character set `NONE`.
See  <<how-does-character-set-none-work,How does character set `NONE` work?>> for details on character set `NONE`.

Jaybird 3.0.0 and 3.0.1, however, will reject the connection, see <<how-can-i-solve-the-error-connection-rejected-no-connection-character-set-specified,How can I solve the error "Connection rejected: No connection character set specified">>.

In Jaybird 3 it is possible to override the default connection character set by specifying system property `org.firebirdsql.jdbc.defaultConnectionEncoding` with a valid Firebird character set name.

Jaybird 3.0.2 introduces the system property `org.firebirdsql.jdbc.requireConnectionEncoding`, which -- when set to `true` -- will reject connections without a character set (which  was the default behavior in Jaybird 3.0.0 and 3.0.1).

[#how-can-i-solve-the-error-connection-rejected-no-connection-character-set-specified]
=== How can I solve the error "Connection rejected: No connection character set specified"

If no character set has been set, Jaybird 3 will reject the connection with an `SQLNonTransientConnectionException` with message _"Connection rejected: No connection character set specified (property lc_ctype, encoding, charSet or localEncoding).
Please specify a connection character set (e.g. property charSet=utf-8) or consult the Jaybird documentation for more information."_

In Jaybird 3.0.0 and 3.0.1 this error will be thrown if the character set has not been set explicitly.
In Jaybird 3.0.2 and higher this error will only be thrown if system property `org.firebirdsql.jdbc.requireConnectionEncoding` has been set to `true`.

To address this error, you can set the default connection character set using one of the following options:

* Use connection property `encoding` (alias: `lc_ctype`) with a Firebird character set name.
+
Use `encoding=NONE` for the default behavior (with some caveats, see  <<how-does-character-set-none-work,How does character set `NONE` work?>>).

* Use connection property `charSet` (alias: `localEncoding`) with a Java character set name.
* Use a combination of `encoding` and `charSet`, if you want to reinterpret a Firebird character set in a Java character set other than the default  mapping.
* By providing a default Firebird character set with system property  `org.firebirdsql.jdbc.defaultConnectionEncoding`.
Jaybird will apply the specified character set as the default when no character set is specified in the connection properties.
+
This property only supports Firebird character set names.
+
Use `-Dorg.firebirdsql.jdbc.defaultConnectionEncoding=NONE` to revert to the default behavior (with some caveats, see <<how-does-character-set-none-work,How does character set `NONE` work?>>).
With Jaybird 3.0.2 or higher, it is better to just not set system property  `org.firebirdsql.jdbc.requireConnectionEncoding` if you want to apply `NONE`.

[#how-can-i-enable-the-windows-tcp-loopback-fast-path-introduced-in-firebird-3-0-2]
== How can I enable the Windows "TCP Loopback Fast Path" introduced in Firebird 3.0.2?

[CAUTION]
====
Microsoft has deprecated the `SIO_LOOPBACK_FAST_PATH` and recommends not to use it.

Support was removed in Firebird 5.0.
====

Firebird 3.0.2 adds support for "`TCP Loopback Fast Path`" (`SIO_LOOPBACK_FAST_PATH` socket option);
support was removed in Firebird 5.0.
This is available in Windows 8 / Windows Server 2012 and higher.
This feature enables performance optimizations when connecting through localhost (127.0.0.1 / ::1).
It requires support on both client and server side.

Java support for "TCP Loopback Fast Path" was introduced in Java 8 update 60, it can be enabled by specifying the system property `jdk.net.useFastTcpLoopback` with value `true` (e.g. specify `-Djdk.net.useFastTcpLoopback=true` in your Java commandline).

Unfortunately, Java only has an 'all-or-nothing' support for the "`TCP Loopback Fast Path`", so Jaybird cannot enable this for you: you must specify this  property on JVM startup.
On the other hand, this has the benefit that this works for all Jaybird versions, as long as you use Java 8 update 60 or higher (and Firebird 3.0.2 or higher, but before 5.0.0).

[#common-connection-errors]
== Common connection errors

[[your-user-name-and-password-are-not-defined-ask-your-database-administrator-to-set-up-a-firebird-login.-335544472]]
=== Your user name and password are not defined. Ask your database administrator to set up a Firebird login. (335544472)

This error means that the user does not exist, or that the specified password is not correct.

When connecting to Firebird 3.0 and higher, this error can also mean that the user does exist (with that password), but not for the authentication plugins tried for this connection.

For example, Jaybird 2.2.x and earlier only support legacy authentication, if you try to log in as a user created for SRP authentication, you will get the same error.

[#incompatible-wire-encryption-levels-requested-on-client-and-server-335545064]
=== Incompatible wire encryption levels requested on client and server (335545064)

With Jaybird 3.0.0 - 3.0.3 connecting to Firebird 3.0 or higher, this usually means that the setting `WireCrypt` is set to its (default) value of `Required`.

Upgrade to Jaybird 3.0.4 or higher, or relax this setting (in `firebird.conf`) to `WireCrypt = Enabled`.

See also https://github.com/FirebirdSQL/jaybird/wiki/Jaybird-and-Firebird-3[Jaybird Wiki -- Jaybird and Firebird 3].

With Jaybird 3.0.4 or higher, or Jaybird 4, this error means that you have requested a connection with a mismatch in encryption settings.
For example, you specified connection property `wireCrypt=required` while Firebird is set to `WireCrypt = Disabled` (or vice versa).

[#connection-rejected-by-remote-interface-335544421]
=== connection rejected by remote interface (335544421)

In general this error means that Jaybird requested a connection with properties not supported by Firebird.
It can have other causes than described below.

[#cause-username-or-password-is-null]
==== Cause: username or password is null

With Jaybird 3 and Jaybird 4 connecting to Firebird 3.0 or higher, leaving username or password null will lead to Jaybird not trying any authentication plugin, and as a result Firebird will reject the connection.

With Firebird 2.5 and earlier, or Jaybird 2.2 or earlier, or Jaybird 5 or higher, this situation will yield error "`Your user name and password are not defined. Ask your database administrator to set up a Firebird login.`"

[#cause-wirecrypt-required]
==== Cause: wirecrypt required

With Jaybird 2.2.x connecting to Firebird 3.0 or higher, this usually means that the setting `WireCrypt` is set to its (default) value of `Required`.

Relax this setting (in `firebird.conf`) to `WireCrypt = Enabled`.

See also https://github.com/FirebirdSQL/jaybird/wiki/Jaybird-and-Firebird-3[Jaybird Wiki -- Jaybird and Firebird 3].

Make sure you check the other settings mentioned in that article, otherwise you'll get the next error.

[#cause-unsupported-protocol]
==== Cause: unsupported protocol version

Since Jaybird 6, protocol versions of unsupported Firebird versions are no longer tried by default with pure Java connections.
Connecting to unsupported Firebird versions with the pure Java protocol can result in this error.

There are two options to address this:

. Specify connection property `enableProtocol` with a list of unsupported protocol versions to try in addition to the supported protocol versions, or `"{asterisk}"` to try all available protocol versions (e.g. `enableProtocol=12` or `enableProtocol={asterisk}`).
. Use a native connection instead of a pure Java connection.

[#error-occurred-during-login-please-check-server-firebird-log-for-details-335545106]
=== Error occurred during login, please check server firebird.log for details (335545106)

If the logging contains something like

----
SERVER	Sat Oct 28 10:07:26 2017
	Authentication error
	No matching plugins on server
----

With Jaybird 2.2 connecting to Firebird 3.0 or higher, this means that the setting `AuthServer` does not include the `Legacy_Auth` plugin.

Enable `Legacy_Auth` (in `firebird.conf`) by adding this value to the property  `AuthServer`, for example: `AuthServer = Srp, Legacy_Auth`.

With Jaybird 4 and higher, this can also mean that none of the default authentication plugins, or those specified using connection property  `authPlugins`, are listed in the `AuthServer` setting.
Either revise the Firebird configuration, or explicitly configure connection property `authPlugins` with authentication plugins that are configured in Firebird.

You also need to make sure your user is created with the legacy user manager, see https://github.com/FirebirdSQL/jaybird/wiki/Jaybird-and-Firebird-3[Jaybird Wiki -- Jaybird and Firebird 3] for details.

[#encryption-key-did-not-meet-algorithm-requirements-of-symmetricarc4-337248282]
=== Encryption key did not meet algorithm requirements of Symmetric/Arc4 (337248282)

If the exception cause is _java.security.InvalidKeyException: Illegal key size or default parameters_, this means that your Java installation applies a security policy that does not allow ARCFOUR with a 160 bit encryption key.

If `wireCrypt=ENABLED` (the default), this is just logged as a warning.
The connection will succeed, but it does mean that the connection will not be encrypted.
If `wireCrypt=REQUIRED`, this is thrown as an exception, and the connection will fail.

This could indicate that your Java version applies the limited strength Cryptographic Jurisdiction Policy (this was the default in Java 8 Update 152 and earlier), or has been explicitly configured to apply the limited policy, or has a custom security policy to restrict the cryptographic key size.

Solutions and workarounds:

* Apply the unlimited Cryptographic Jurisdiction Policy, see https://stackoverflow.com/a/3864276/466862[this Stack Overflow answer]
* Relax your custom security policy to allow 160 bit keys for ARCFOUR
* Disable wire encryption for Firebird by setting `WireCrypt = Disabled` in `firebird.conf`
* Set `wireCrypt=DISABLED` in the connection properties

Be aware that the first two options may have legal implications depending on the local law in your country regarding cryptography.

[#jdbc-support]
= JDBC Support

[#how-much-of-jdbc-is-supported-by-jaybird]
== How much of JDBC is supported by Jaybird?

*WARNING* The information in this section is not 100% up-to-date

Jaybird 4 follows the JDBC 4.3 specification with some features and methods not implemented as they are not supported by Firebird.

Implemented features:

* Most useful JDBC functionality ("`useful`" in the opinion of the developers).
* XA transactions with true two phase commit when used via `javax.sql.XADataSource` implementation `org.firebirdsql.ds.FBXADataSource`.
* `ObjectFactory` implementation `org.firebirdsql.ds.DataSourceFactory` for use in environments with JNDI but no `TransactionManager`.
* `DataSource` implementation `org.firebirdsql.ds.FBSimpleDataSource` (no pooling).
* `ConnectionPoolDataSource` implementation `org.firebirdsql.ds.FBConnectionPoolDataSource` (please be aware, contrary to suggested by the naming, this does not provide connection pooling, this is intended as a factory of connections for use by a connection pool, e.g. as provided by a Java EE/Jakarta EE application server)
* Complete access to all Firebird database parameter block and transaction parameter block settings.
* JMX mbean for database management (so far just database create and drop).

[#what-parts-of-jdbc-are-not-supported-by-jaybird]
== What parts of JDBC are NOT supported by Jaybird?

*WARNING* The information in this section is outdated

The following optional features are NOT supported:

The following optional features and the methods that support it are not implemented:

* Ref and Array types.
** `java.sql.PreparedStatement`
*** `setRef(int i, Ref x)`
*** `setArray(int i, Array x)`
** `java.sql.ResultSet`
*** `getArray(int i)`
*** `getArray(String columnName)`
*** `getRef(int i)`
*** `getRef(String columnName)`
* User Defined Types/Type Maps.
** `java.sql.ResultSet`
*** `getObject(int i, java.util.Map map)`
*** `getObject(String columnName, java.util.Map map)`
** `java.sql.Connection`
*** `getTypeMap()`
*** `setTypeMap(java.util.Map map)`

Excluding the unsupported features, the following methods are not yet implemented:

* `java.sql.Blob`
** `getBytes(long pos, int length)`
** `position(byte pattern[], long start)`
** `position(Blob pattern, long start)`
** `getBinaryStream(long pos, long length)`
** `truncate(long len)`
** Methods with a position (`pos`) parameter with a value greater than 1
* `java.sql.Clob`
** `length()`
** `truncate(long len)`
** `position(String searchstr, long start)`
** `position(Clob searchstr, long start)`
** `getCharacterStream(long pos, long length)`
** Methods with a position (`pos`) parameter with a value greater than 1

The following methods are implemented, but do not work as expected:

* `java.sql.Statement`
** `get/setMaxFieldSize` does nothing
** `get/setQueryTimeout` supported since Jaybird 4 with Firebird 4.0 and higher
* `java.sql.PreparedStatement`
** `setObject(index,object,type)` This method is implemented but behaves as `setObject(index,object)`
** `setObject(index,object,type,scale)` This method is implemented but behaves as `setObject(index,object)`
* `java.sql.CallableStatement`
** `getBigDecimal(index,scale)` This method is implemented but behaves as `getBigDecimal(index)`.
The method is deprecated, and we suggest using `getBigDecimal(index)` and adjust the scale of the returned `BigDecimal` using `BigDecimal.setScale(newScale,roundingMode)`
* `java.sql.ResultSetMetaData`
** `isReadOnly(i)` always returns false
** `isWritable(i)` always returns true
** `isDefinitivelyWritable(i)` always returns true
* `java.sql.ResultSet`
** `getBigDecimal(index,scale)` This method is implemented but behaves as `getBigDecimal(index)`.
The method is deprecated, and we suggest using `getBigDecimal(index)` and adjust the scale of the returned `BigDecimal` using `BigDecimal.setScale(newScale,roundingMode)`

[#features]
= Features

[#does-jaybird-support-connection-pooling]
== Does Jaybird support connection pooling?

Jaybird itself no longer provides connection pooling.
Earlier versions had a `DataSource` implementation with connection pooling, but this implementation had severe bugs.
This implementation (and all other classes in `org.firebirdsql.pool`) was deprecated in Jaybird 2.2 and dropped in Jaybird 3.

Jaybird provides a basic `DataSource` implementation and a `ConnectionPoolDataSource` implementation.
Contrary to its name the latter *does not provide a connection pool*, but is intended to be used by a connection pool (as implemented in an application server) to create connections _for_ the connection pool.

If your application is built on a Java EE/Jakarta EE application server, we suggest you use the connection pooling provided by the application server using the `javax.sql.ConnectionPoolDataSource` implementation `org.firebirdsql.ds.FBConnectionPoolDataSource`, or using the `javax.sql.XADataSource` implementation `org.firebirdsql.ds.FBXADataSource`.

If you develop standalone applications, or you use an application server without connection pooling, we suggest you use third-party libraries like:

* https://github.com/brettwooldridge/HikariCP[HikariCP]
* https://www.mchange.com/projects/c3p0/[c3p0]
* http://commons.apache.org/proper/commons-dbcp/[Apache DBCP]

[#compatibility-notes]
= Compatibility notes

[#wildfly]
== Wildfly

The minimal `module.xml` to use Jaybird 3 under Wildfly is:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.firebirdsql">
  <resources>
    <resource-root path="jaybird-3.0.x.jar"/>
  </resources>
  <dependencies>
    <module name="javax.api"/>
    <module name="javax.transaction.api"/>
    <module name="javax.resource.api"/>
  </dependencies>
</module>
----

With Jaybird 3.0.4 and higher for Java 7 (but not Java 8!) in Wildfly (or JBoss), you will need to add the module `javax.xml.bind.api` to your module:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.firebirdsql">
  <resources>
    <resource-root path="jaybird-3.0.x.jar"/>
  </resources>
  <dependencies>
    <module name="javax.api"/>
    <module name="javax.transaction.api"/>
    <module name="javax.resource.api"/>
    <module name="javax.xml.bind.api"/> <!-- Add this -->
  </dependencies>
</module>
----

Alternatively, use Jaybird for Java 8 (or higher).
