= Jaybird {version_wo_target} Release Notes
:doctype: book
:docinfo:
:sectanchors:
:forceinclude: true
:keywords: jaybird, firebird, jdbc, sql, database, java
:source-highlighter: prettify
:toc: left
:icons: font
:sectnums:
:bc-version: 1.79
:jna-version: 5.16.0
:jaybird-fbclient-version: 5.0.1.1
:firebird-java: https://groups.google.com/g/firebird-java
:issues: https://github.com/FirebirdSQL/jaybird/issues
:jaybird-repo: https://github.com/FirebirdSQL/jaybird
:fb-canonical-html: https://firebirdsql.org/docs/drivers/java/6.0.x/release_notes.html

ifeval::["{version_tag}" != ""]
[WARNING]
====
Jaybird {version_wo_target} is still in development, and intended for testing and evaluation purposes.
We do not recommend this version for use in production environments.

If you come across any issues when using this version, please report them on {issues}[^].
====
endif::[]

[#jaybird-7-0-x-changelog]
== Jaybird 7.0.x changelog

Changes per Jaybird 7 release.
See also <<whats-new-in-jaybird-7>>.
For known issues, consult <<known-issues>>.

...

[#known-issues]
== Known issues

* Using a native connection with a Firebird 3.0 or higher client library to a Firebird 2.5 or older server may be slow to connect.
+
Possible workarounds:
+
--
** Use a native URL with the Firebird INET4 protocol (e.g. for `DriverManager` `++jdbc:firebird:native:inet4://<serverName>[:<portNumber>/<databaseName>++`).
** Use the IPv4 address instead of the host name in the connection string
** Use a Firebird 2.5 or earlier `fbclient`.
--
+
This is caused by https://github.com/FirebirdSQL/firebird/issues/4971[firebird#4971]

[#general-notes]
== General Notes

Jaybird is a JDBC driver suite to connect to Firebird database servers from Java and other Java Virtual Machine (JVM) languages.

This driver does not work on Android, because it uses classes and features not available in Android.

[#about-this-version]
=== About this version

The major changes and new features in Jaybird 7 are:

* ...

Upgrading from Jaybird 6 should be straightforward, but please make sure to read <<compatibility-changes>> before using Jaybird 7.
See also <<upgrading-from-jaybird-6-to-jaybird-7>>.

Bug reports about undocumented changes in behavior are appreciated.
Feedback can be sent to the {firebird-java}[Firebird-java mailing list] or reported on the issue tracker {issues}[^].

[#supported-firebird-versions]
=== Supported Firebird versions

Jaybird {version_wo_target} was tested against Firebird 3.0.12, Firebird 4.0.5, Firebird 5.0.1 and a recent snapshot of Firebird 6.0, but should also support other Firebird versions from 3.0 and up.
Firebird 2.5 and older are not supported.

Firebird 6.0 is currently also not considered supported (see also <<firebird-support>> in <<whats-new-in-jaybird-7>>).

Jaybird 7 will -- by default -- not connect to Firebird 2.5 or older.

This driver does not support InterBase.

[#supported-java-versions]
=== Supported Java versions

Jaybird 7 supports Java 17 and higher (JDBC 4.3).
Support for earlier Java versions has been dropped.

Given the limited support period for Java 9 and higher versions, we limit support to Java 17, the most recent LTS version after Java 17, and the latest Java release.
Currently, that means we support Java 17, Java 21, and Java 23.

[NOTE]
====
Jaybird 5 will serve as a "`long-term support`" version for Java 8 and 11, with maintenance releases at least until the release of Jaybird 7.
====

Jaybird 7 provides libraries compiled for Java 17.

Jaybird 7 is modularized.
The available modules are:

`org.firebirdsql.jaybird`::
main Jaybird driver (`jaybird-{version_example}.jar`)

`org.firebirdsql.jaybird.chacha64`::
ChaCha64 wire encryption implementation (`chacha64-plugin-{version_example}.jar`)

`org.firebirdsql.jna`::
native and embedded protocol implementation using JNA (`jaybird-native-{version_example}.jar`)

See also <<java-support>> in <<whats-new-in-jaybird-7>>.

[#specification-support]
=== Specification support

Jaybird supports the following specifications:

|===
| Specification | Notes

| JDBC 4.3
| All JDBC 4.3 methods for features supported by Firebird.

| JTA 1.0.1
| Implementation of `javax.transaction.xa.XAResource` interface via `XADataSource` implementation.
|===

[#support]
== Support

If you need support with Jaybird, join the {firebird-java}[Firebird-Java Google Group] and mailing list.
You can subscribe by sending an email to link:mailto:firebird-java+subscribe@googlegroups.com[firebird-java+subscribe@googlegroups.com].

Looking for professional support of Jaybird?
Jaybird is now part of the https://tidelift.com/subscription/pkg/maven-org-firebirdsql-jdbc-jaybird?utm_source=maven-org-firebirdsql-jdbc-jaybird&utm_medium=referral&utm_campaign=docs[Tidelift subscription].

For a more complete list, see the next section.

[#where-to-get-help]
=== Where to get help

* On https://stackoverflow.com/[Stack Overflow], please tag your questions with _jaybird_ and _firebird_
* The {firebird-java}[Firebird-Java group] and corresponding mailing list firebird-java@googlegroups.com
+
You can subscribe to the mailing list by sending an email to link:mailto:firebird-java+subscribe@googlegroups.com[firebird-java+subscribe@googlegroups.com]
* Looking for professional support of Jaybird?
Jaybird is now part of the https://tidelift.com/subscription/pkg/maven-org-firebirdsql-jdbc-jaybird?utm_source=maven-org-firebirdsql-jdbc-jaybird&utm_medium=referral&utm_campaign=docs[Tidelift subscription].
* The https://firebirdsql.org[Firebird project home page]
* https://groups.google.com/g/firebird-support[Firebird-support] and other https://firebirdsql.org/en/mailing-lists/[Firebird mailing lists] for questions not directly related to Jaybird and Java.

[#contributing]
=== Contributing

There are several ways you can contribute to Jaybird or Firebird in general:

* Participate on the https://firebirdsql.org/en/mailing-lists/[mailing lists]
* Report bugs or submit patches on the tracker (see <<reporting-bugs>>)
* Create pull requests on GitHub (https://github.com/FirebirdSQL/jaybird)
* Become a developer (for Jaybird contact us on {firebird-java}[firebird-java], for Firebird in general, use the https://groups.google.com/g/firebird-devel[Firebird-devel] mailing list)
* Donate to the Firebird Foundation (see https://firebirdsql.org/en/donate/)
* Become a paying Associate, Partner or sponsor of the Firebird Foundation (see https://firebirdsql.org/en/firebird-foundation/)

[#reporting-bugs]
=== Reporting bugs

The developers follow the {firebird-java}[firebird-java Google Group].
Join the list and post information about suspected bugs.
List members may be able to help out to determine if it is an actual bug, provide a workaround and get you going again, whereas bug fixes might take a while.

You can also report bugs in the Jaybird bug tracker, {issues}.

When reporting bugs, please provide a minimal, but complete reproduction, including databases and sourcecode to reproduce the problem.
Patches to fix bugs are also appreciated.
Make sure the patch is against a recent master version of the code.
You can also fork the {jaybird-repo}[jaybird repository] and create pull requests.

[#getting-jaybird-7]
== Getting Jaybird 7

[#jaybird-version_wo_target]
=== Jaybird {version_wo_target}

[#maven]
==== Maven

ifeval::["{version_tag}" != "-SNAPSHOT"]
Jaybird {version_wo_target} is available on Maven Central.
endif::[]
ifeval::["{version_tag}" == "-SNAPSHOT"]
Jaybird {version_wo_target} is available on the Sonatype snapshot repository.

NOTE: SNAPSHOT releases are only available from the Sonatype snapshot repository, https://oss.sonatype.org/content/repositories/snapshots
endif::[]

[horizontal.compact]
groupId:: `org.firebirdsql.jdbc`
artifactId:: `jaybird`
version:: `{version_example}`

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>{version_example}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), you need to explicitly add `jaybird-native` as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-native</artifactId>
    <version>{version_example}</version>
</dependency>
----

For Windows and Linux, you can add the `org.firebirdsql.jdbc:fbclient` dependency on your classpath to provide the native libraries for the `native` protocol.
Be aware that this dependency does not support `embedded`.

See also <<type-2-native-and-embedded-driver>>.

To enable the "`ChaCha64`" wire encryption support for pure Java connections, also add:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>chacha64-plugin</artifactId>
    <version>{version_example}</version>
</dependency>
----

[#gradle]
==== Gradle

See also <<maven>>.

Examples:

.Main Jaybird artifact
[source,groovy,subs="verbatim,attributes"]
----
implementation 'org.firebirdsql.jdbc:jaybird:{version_example}'
----

.Jaybird native artifact (native and embedded protocol)
[source,groovy,subs="verbatim,attributes"]
----
implementation 'org.firebirdsql.jdbc:jaybird-native:{version_example}'
----

.ChaCha64 wire encryption plugin
[source,groovy,subs="verbatim,attributes"]
----
implementation 'org.firebirdsql.jdbc:chacha64-plugin:{version_example}'
----

[#download]
==== Download

You can download the release of Jaybird from https://firebirdsql.org/en/jdbc-driver/

At minimum, Jaybird 7 requires `jaybird-{version_example}.jar`.

For native or embedded support, also add `jaybird-native-{version_example}.jar` and `jna-jpms-{jna-version}.jar` on your classpath or modulepath.
See also <<type-2-native-and-embedded-driver>>.

For "`ChaCha64`" wire-encryption support with pure Java connections, also add `chacha64-plugin-{version_example}.jar`, and `bcprov-jdk18on-{bc-version}.jar` from the `lib` directory of the distribution zip.

[#upgrading-from-jaybird-6-to-jaybird-7]
== Upgrading from Jaybird 6 to Jaybird 7

Please make sure to read <<compatibility-changes,Compatibility changes>> before upgrading to Jaybird 7.

[#maven-2]
=== Maven

Change the version of the dependency to `{version_example}`.

For more detailed instructions, see also the information on Maven in <<getting-jaybird-7>>.

If you use native or embedded, you need to explicitly add `jaybird-native` as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-native</artifactId>
    <version>{version_example}</version>
</dependency>
----

If you use native or embedded, make sure to update your JNA dependency to version `{jna-version}` and artifact id `jna-jpms`, or remove it altogether as the dependencies will now be pulled in through the `jaybird-native` artifact.

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna-jpms</artifactId>
    <version>{jna-version}</version>
</dependency>
----

[WARNING]
====
Jaybird 5 and older used `artifactId` `jna` instead of `jna-jpms`.
Although both artifacts are nearly identical, the `jna-jpms` artifact provides a `module-info.class`, while the `jna` artifact does not.
If you want to use Jaybird as a module, and use `jaybird-native`, make sure to use the `jna-jpms` artifact.
====

[#manual-install]
=== Manual install

If you manage your dependencies manually, you need to do the following:

. Replace the Jaybird 6 library with the Jaybird 7 version
** `jaybird-6.0.x.<java>.jar` with `jaybird-{version_example}.jar`
. If you use the NATIVE or EMBEDDED protocols, replace the following JARs to the classpath or modulepath
** `jaybird-native-6.0.x.<java>.jar` with `jaybird-native-{version_example}.jar`
** older `jna` or `jna-jpms` versions with `jna-jpms-{jna-version}.jar` from the `lib` directory of the distribution zip
. To enable "`ChaCha64`" wire encryption support replace the following JARs to the classpath or modulepath
** `chacha64-plugin-6.0.x.<java>.jar` with `chacha64-plugin-{version_example}.jar`
** older `bcprov-jdk18on` with `bcprov-jdk18on-{bc-version}.jar` from the `lib` directory of the distribution zip

[#gotchas]
=== Gotcha's

If you find a problem while upgrading, or other bugs, please report it on {issues}[^] (see also <<reporting-bugs>>).

For known issues, consult <<known-issues>>.

[#whats-new-in-jaybird-7]
== What's new in Jaybird 7

For a full list of changes, see milestone https://github.com/FirebirdSQL/jaybird/milestone/9?closed=1["`v7-initial`"].

[#java-support]
=== Java support

[NOTE]
====
At this point in the Jaybird 7 development, information about supported Java versions is tentative.

We may decide to change the minimum supported Java version before the final release of Jaybird 7.
====

Jaybird 7 supports Java 17 and higher (JDBC 4.3).
Most of the JDBC 4.3 features have been implemented (in as far as they are supported by Firebird).

Given the limited support period for Java 17 and higher versions, not all Java releases are formally supported, see <<supported-java-versions>> for details.

[#firebird-support]
=== Firebird support

[NOTE]
====
At this point in the Jaybird 7 development, information about supported Firebird versions is tentative.

We may decide to change the minimum supported Firebird version before the final release of Jaybird 7.
====

Jaybird 7 supports Firebird 3.0, Firebird 4.0, and Firebird 5.0.

.No promises on Firebird 6.0 support
[WARNING]
====
Firebird 6.0 is still in its early stages of development, and is expected to include changes -- like schema support -- that may impact Jaybird.

As a result -- at this time -- we make no promises on the support for Firebird 6.0 by Jaybird 7.
====

Jaybird 7 will -- by default -- not connect to unsupported versions (that is, Firebird 2.5 or older) using the pure Java protocol.

// TODO add major changes

[#other-fixes-and-changes]
=== Other fixes and changes

* ...

[#compatibility-changes]
== Compatibility changes

Jaybird 7 introduces some changes in compatibility and announces future breaking changes.

*The list might not be complete, if you notice a difference in behavior that is not listed, please {issues}[report it as bug^].*
It might have been a change we forgot to document, but it could just as well be an implementation bug.

// TODO Document compatibility issues

[#removal-of-classes-packages-and-methods-without-deprecation]
=== Removal of classes, packages and methods without deprecation

Below list of removals may look daunting, but if you use Jaybird only as a JDBC driver, through the JDBC API, you're likely unaffected.
Although we list them as removed without deprecation, some were marked as deprecated retroactively in Jaybird 5.0.3 or later.

This section does not include all changes to packages or classes considered internal API.

[#removal-of-packages-without-deprecation]
==== Removal of packages without deprecation

The following packages have been removed in Jaybird 7 without deprecation:

* ...

[#removal-of-methods-without-deprecation]
==== Removal of methods without deprecation

The following methods have been removed in Jaybird 7 without deprecation:

* ...

[#removal-of-classes-without-deprecation]
==== Removal of classes without deprecation

The following classes have been removed in Jaybird 7 without deprecation:

* ...

[#removal-of-constants-without-deprecation]
==== Removal of constants without deprecation

The following constants have been removed in Jaybird 7 without deprecation:

* ...

[#removal-of-deprecated-classes-packages-and-methods]
=== Removal of deprecated classes, packages and methods

Below list of removals may look daunting, but if you use Jaybird only as a JDBC driver, through the JDBC API, you're likely unaffected.

[#removal-of-deprecated-packages]
==== Removal of deprecated packages

The following packages have been removed in Jaybird 7:

* ...

[#removal-of-deprecated-methods]
==== Removal of deprecated methods

The following methods have been removed in Jaybird 7:

* `GDSFactoryPlugin` (semi-internal API)
** `getTypeAliases()` -- use `getTypeAliasList()`
** `getSupportedProtocols` -- use `getSupportedProtocolList()`
* `GDSHelper` (internal API)
** `startTransaction(TransactionParameterBuffer)` -- use `FbDatabase.startTransaction(TransactionParameterBuffer)` followed by `GDSHelper.setCurrentTransaction(FbTransaction)`
* `FirebirdStatement`
** `getCurrentResultSet()` -- use `getResultSet()`
* `SqlCountHolder` (internal API)
** `getLongUpdateCount()` -- use `updateCount()`
** `getLongDeleteCount()` -- use `deleteCount()`
** `getLongInsertCount()` -- use `insertCount()`
** `getLongSelectCount()` -- use `selectCount()`

[#removal-of-deprecated-classes]
==== Removal of deprecated classes

The following classes have been removed in Jaybird 7:

* `GDSException`;
use `SQLException` or one of its (normal) subclasses
* `FBSQLException`;
use `SQLException`

[#removal-of-deprecated-constants]
==== Removal of deprecated constants

The following constants have been removed in Jaybird 7:

* `ISCConstants`
** `isc_isc_sql_dialect_conflict_num`;
use `isc_sql_dialect_conflict_num`
** `isc_err_max`;
there is no replacement
* `JaybirdErrorCodes`
** `jb_stmtInErrorRequireCLose`;
use `jb_stmtInErrorRequireClose`
* `QuoteStrategy`
** `NO_QUOTES`;
use `DIALECT_1`
** `QUOTES`;
use `DIALECT_3`
* `SQLStateConstants`
** `SQL_STATE_CONNECTION_CLOSED` (`08003`);
use `SQL_STATE_CONNECTION_FAILURE` (`08006`).
* `ServiceManager`
** `getHost`/`setHost`;
use `getServerName`/`setServerName`
** `getPort`/`setPort`;
use `getPortNumber`/`setPortNumber`

[#breaking-changes-internal-api]
=== Breaking changes internal API

The following breaking changes were made to the internal API, like the GDS-ng API in `org.firebirdsql.gds.ng` and sub-packages.
These changes are primarily interesting for implementers of custom GDS-ng implementations or forks of Jaybird, or people using these low-level APIs directly.

[NOTE]
====
Only changes we think are relevant to driver implementers or (internal) API users are documented.
This means there may be undocumented changes to internal API.
If you are confronted with such a change, let us know on {firebird-java}[firebird-java], so we can take this into account when documenting future changes.
====

* ...

[#breaking-changes-unlikely]
=== Unlikely breaking changes

The following changes might cause issues, though we think this is unlikely:

// TODO Document unlikely breaking changes, or remove section

[#breaking-changes-for-jaybird-8]
=== Breaking changes for Jaybird 8

With Jaybird 8 the following breaking changes will be introduced.

[#removal-of-deprecated-classes-packages-and-methods-8]
==== Removal of deprecated classes, packages and methods

[#removal-of-deprecated-methods-8]
===== Removal of deprecated methods

The following methods will be removed in Jaybird 8:

* ...

[#removal-of-deprecated-classes-8]
===== Removal of deprecated classes

The following classes have been deprecated and will be removed in Jaybird 8:

* ...

[#removal-of-deprecated-constants-8]
==== Removal of deprecated constants

The following constants have been deprecated and will be removed in Jaybird 8:

* ...

[#compatibility-notes]
== Compatibility notes

[#type-2-native-and-embedded-driver]
=== Type 2 (native) and embedded driver

Since Jaybird 6, the native and embedded part of the driver has been moved to a separate artifact, `jaybird-native`.
The Jaybird Native GDS Factory plugin uses JNA to access the client library.
If you want to use the Type 2 driver, or Firebird embedded, then you need to include `jaybird-native-{version_example}` and `jna-jpms-{jna-version}.jar` on the classpath.

When using Maven, you need to specify the dependency on `jaybird-native`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-native</artifactId>
    <version>{version_example}</version>
</dependency>
----

The `fbclient.dll`, `fbembed.dll`, `libfbclient.so`, or `libfbembed.so` need to be on the path, or the location needs to be specified in the system property `jna.library.path` (as an absolute or relative path to the directory/directories containing the library file(s)).

For Windows and Linux, you can add the `org.firebirdsql.jdbc:fbclient` dependency on your classpath to provide the native libraries for the `native` and `local` protocol.
Be aware that this dependency does not support `embedded`.

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>fbclient</artifactId>
    <version>{jaybird-fbclient-version}</artifactId>
</dependency>
----

For more information about this library, see https://github.com/mrotteveel/jaybird-fbclient[^].

In the future we may provide JARs with the embedded libraries of a specific Firebird version.
