= Jaybird {version_wo_target} Release Notes
:doctype: book
:docinfo:
:sectanchors:
:forceinclude: true
:keywords: jaybird, firebird, jdbc, sql, database, java
:source-highlighter: prettify
:toc: left
:icons: font
:sectnums:
:bc-version: 1.73
:jna-version: 5.13.0

ifeval::["{version_tag}" != ""]
[WARNING]
====
Jaybird {version_wo_target} is still in development, and intended for testing and evaluation purposes.
We do not recommend this version for use in production environments.

If you come across any issues when using this version, please report them on https://github.com/FirebirdSQL/jaybird/issues.
====
endif::[]

[#jaybird-6-0-x-changelog]
== Jaybird 6.0.x changelog

Changes per Jaybird 6 release.
See also <<whats-new-in-jaybird-6>>.
For known issues, consult <<known-issues>>.

[#known-issues]
== Known issues

* Using a native connection with a Firebird 3.0 or higher client library to a Firebird 2.5 or older server may be slow to connect.
+
Possible workarounds:
+
--
** Use a native URL with the Firebird INET4 protocol (e.g. for `DriverManager` `++jdbc:firebird:native:inet4://<serverName>[:<portNumber>/<databaseName>++`).
** Use the IPv4 address instead of the host name in the connection string
** Use a Firebird 2.5 or earlier `fbclient`.
--
+
This is caused by https://github.com/FirebirdSQL/firebird/issues/4971[firebird#4971]

[#support]
== Support

If you need support with Jaybird, join the https://groups.google.com/g/firebird-java[Firebird-Java Google Group] and mailing list.
You can subscribe by sending an email to link:mailto:firebird-java+subscribe@googlegroups.com[firebird-java+subscribe@googlegroups.com].

Looking for professional support of Jaybird?
Jaybird is now part of the https://tidelift.com/subscription/pkg/maven-org-firebirdsql-jdbc-jaybird?utm_source=maven-org-firebirdsql-jdbc-jaybird&utm_medium=referral&utm_campaign=docs[Tidelift subscription].

See also https://www.firebirdsql.org/file/documentation/drivers_documentation/java/faq.html#where-to-get-help[Where to get help]

[#general-notes]
== General Notes

Jaybird is a JDBC driver suite to connect to Firebird database servers from Java and other Java Virtual Machine (JVM) languages.

This driver does not work on Android, because it uses classes and features not available in Android.

[#about-this-version]
=== About this version

// TODO Describe Jaybird 6

The major changes and new features in Jaybird 5 are:

// TODO List Jaybird 6 changes

Upgrading from Jaybird 5 to 6 should be simple, but please make sure to read <<compatibility-changes>> before using Jaybird 6.
See also <<upgrading-from-jaybird-5-to-jaybird-6>>.

Bug reports about undocumented changes in behavior are appreciated.
Feedback can be sent to the https://groups.google.com/g/firebird-java[Firebird-java mailing list] or reported on the issue tracker https://github.com/FirebirdSQL/jaybird/issues.

[#supported-firebird-versions]
=== Supported Firebird versions

Jaybird {version_wo_target} was tested against Firebird 3.0.10, and 4.0.2 and a recent snapshot of Firebird 5.0, but should also support other Firebird versions from 3.0 and up.

Jaybird 6 will -- by default -- not connect to Firebird 2.5 or older.

This driver does not support InterBase servers due to Firebird-specific changes in the protocol and database attachment parameters that are sent to the server.

[#supported-java-versions]
=== Supported Java versions

Jaybird 6 supports Java 17 and higher (JDBC 4.3).
Support for earlier Java versions has been dropped.

Given the limited support period for Java 9 and higher versions, we limit support to Java 17 and the most recent LTS version after Java 17 and the latest Java release.
Currently, that means we support Java 17 and 20.

[NOTE]
====
Jaybird 5 will serve as a "`long-term support`" version for Java 8 and 11, with maintenance releases at least until the release of Jaybird 7.
====

Jaybird 6 provides libraries for Java Java 17.

Jaybird 6 is not modularized, but all versions declare the automatic module name `org.firebirdsql.jaybird`.

See also <<java-support>> in <<whats-new-in-jaybird-6>>.

[#specification-support]
=== Specification support

Jaybird supports the following specifications:

|===
| Specification | Notes

| JDBC 4.3
| All JDBC 4.3 methods for features supported by Firebird;
Java 9 and higher supported using the Java 17 driver.

| JTA 1.0.1
| Implementation of `javax.transaction.xa.XAResource` interface via `XADataSource` implementation.
|===

[#getting-jaybird-6]
== Getting Jaybird 6

[#jaybird-version_wo_target]
=== Jaybird {version_wo_target}

[#maven]
==== Maven

Jaybird {version_wo_target} is available on Maven Central:

groupId: `org.firebirdsql.jdbc`, +
artifactId: `jaybird`, +
version: `{version_wo_target}`

ifeval::["{version_tag}" == "-SNAPSHOT"]
NOTE: SNAPSHOT releases are only available from the Sonatype snapshot repository, https://oss.sonatype.org/content/repositories/snapshots
endif::[]

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>{version_example}</version>
</dependency>
----

To enable the "`ChaCha64`" wire encryption support, also add:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>chacha64-plugin</artifactId>
    <version>{version_example}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), you need to explicitly add `jaybird-native` as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-native</artifactId>
    <version>{version_example}</version>
</dependency>
----

For Windows and Linux, you can add the `org.firebirdsql.jdbc:fbclient` dependency on your classpath to provide the native libraries for the `native` protocol.
Be aware that this dependency does not support `embedded`.

See also <<type-2-native-and-embedded-driver>>.

[#download]
==== Download

You can download the latest versions from https://www.firebirdsql.org/en/jdbc-driver/

At minimum Jaybird 6 requires `jaybird-{version_wo_target}.jar`.

For "`ChaCha64`" support, also add `chacha64-plugin.jar` and `bcprov-jdk18on-{bc-version}.jar`.

For native or embedded support, you will need to include `jna-jpms-{jna-version}.jar` on your classpath or modulepath.
See also <<type-2-native-and-embedded-driver>>.

[#upgrading-from-jaybird-5-to-jaybird-6]
== Upgrading from Jaybird 5 to Jaybird 6

Please make sure to read <<compatibility-changes,Compatibility changes>> before upgrading to Jaybird 6.

[#maven-2]
=== Maven

Change the version of the dependency to `{version_wo_target}`.
If you're still using the artifact id `jaybird-jdkXX`, change it to `jaybird`.

When your Jaybird dependency defines the exclusion for `javax.resource:connector-api` (see below), you can remove it.

[source,xml]
----
<exclusions>
    <exclusion>
        <groupId>javax.resource</groupId>
        <artifactId>connector-api</artifactId>
    </exclusion>
</exclusions>
----

For more detailed instructions, see also the information on Maven in <<getting-jaybird-6>>.

If you use native or embedded, you now need to explicitly add `jaybird-native` as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-native</artifactId>
    <version>{version_example}</version>
</dependency>
----

If you use native or embedded, make sure to update your JNA dependency to version {jna-version}, or remove it altogether as the dependencies will be pulled in through the `jaybird-native` artifact.

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna-jpms</artifactId>
    <version>{jna-version}</version>
</dependency>
----

[WARNING]
====
Previous versions used `artifactId` `jna` instead of `jna-jpms`.
Although both artifacts are nearly identical, the `jna-jpms` artifact provides a `module-info.class`, while the `jna` artifact does not.
If you want to use Jaybird as a module, and use `jaybird-native`, make sure to use the `jna-jpms` artifact.
====

[#manual-install]
=== Manual install

If you manage your dependencies manually, you need to do the following:

. Replace the Jaybird 5 library with the Jaybird 6 version
** `jaybird-5.0.x.<java>.jar` with `jaybird-{version_wo_target}.jar`
. If you use the NATIVE or EMBEDDED protocols, add the following JARs to the classpath or modulepath
** `jaybird-native-{version_wo_target}.jar`
** `jna-jpms-{jna-version}.jar` (if you have an older version of JNA or a `jna-{jna-version}` instead of `jna-jpms-{jna-version}`, replace it)
. To enable "`ChaCha64`" wire encryption support add the following JARs to the classpath or modulepath
** `chacha64-plugin-{version_wo_target}.jar`
** `bcprov-jdk18on-{bc-version}.jar` from the `lib` directory of the distribution zip

[#gotchas]
=== Gotcha's

If you find a problem while upgrading, or other bugs: please report it on https://github.com/FirebirdSQL/jaybird/issues.

For known issues, consult <<known-issues>>.

[#whats-new-in-jaybird-6]
== What's new in Jaybird 6

For a full list of changes, see https://github.com/FirebirdSQL/jaybird/issues?q=label%3A%22fix-version%3A+Jaybird+6%22[Firebird tracker for Jaybird 6].

[#jaybird-version-numbering]
=== Changes in version numbering

Jaybird 6 uses Java 17 as the minimum supported version.
Our expectation is that Java version specific artifacts are no longer needed.
As a consequence, the Java version has been dropped from the version number.
The full version and naming convention is documented in https://github.com/FirebirdSQL/jaybird/blob/v5.0.0-beta-1/devdoc/jdp/jdp-2023-01-version-number-and-naming-scheme.md[jdp-2023-01: Version Number and Naming Scheme^]

As a result of these new naming conventions, the following has been changed:

* Maven version: `6.0.0` (was `5.0.0.java8`)
* Distribution zip: `jaybird-6.0.0.zip` (was `jaybird-5.0.0.java8.zip`)
* Jaybird: `jaybird-6.0.0.jar` (was `jaybird-5.0.0.java8.jar`)
* Jaybird sources: `jaybird-6.0.0-sources.jar` (was `jaybird-5.0.0.java8-sources.jar`)
* Jaybird javadoc: `jaybird-6.0.0-javadoc.jar` (was `jaybird-5.0.0.java8-javadoc.jar`)

Furthermore, the client name reported to Firebird 2.5 and higher has been changed from `Jaybird jaybird-5.0.0.java8` to `Jaybird jaybird-6.0.0`.

[#java-support]
=== Java support

[#java-before-17]
==== Java version before 17 no longer supported

Support of Java versions before Java 17 was dropped.

See also https://github.com/FirebirdSQL/jaybird/blob/v5.0.0-beta-1/devdoc/jdp/jdp-2022-03-java-17-minimum-version.md[jdp-2022-03: Java 17 minimum version^]

[#java-17-and-higher]
==== Java 17 and higher

Jaybird 6 supports Java 17 and higher (JDBC 4.3).
Most of the JDBC 4.3 features have been implemented (in as far as they are supported by Firebird).

Given the limited support period for Java 17 and higher versions, not all Java releases are supported, see <<supported-java-versions>> for details.

For compatibility with Java 9 modules, Jaybird defines the automatic module name `org.firebirdsql.jaybird`, and the `chacha64-plugin` uses `org.firebirdsql.jaybird.chacha64`.
This guarantees a stable module name for Jaybird, and allows for future modularization of Jaybird.

[#firebird-support]
=== Firebird support

Support for Firebird 2.5 has been dropped.
See also <<support-for-firebird-25-dropped>>.

Jaybird 6 supports Firebird version 3.0, 4.0, and provides tentative support for Firebird 5.0.

[#native-plugin]
=== NATIVE and EMBEDDED support moved to separate artifact

The NATIVE (JDBC URL prefix `++jdbc:firebird[sql]:native:++`) and EMBEDDED (JDBC URL prefix `++jdbc:firebird[sql]:embedded:++`) protocol implementations have been moved to a separate artifact, `org.firebirdsql.jdbc:jaybird-native`.

If you use native or embedded connections using Jaybird, you will need to explicitly add the appropriate Maven dependency (or `jaybird-native-{version_wo_target}.jar` and `jna-jpms-{jna-version}.jar`) to your classpath.

See also <<getting-jaybird-6>>.

[#ooremote-removed]
=== OOREMOTE (OpenOffice/LibreOffice driver) removed

The OOREMOTE protocol (JDBC URL prefix `++jdbc:firebird[sql]:oo:++`) has been removed in Jaybird 6.

See also https://github.com/FirebirdSQL/jaybird/tree/master/devdoc/jdp/jdp-2022-04-deprecate-ooremote.md[jdp-2022-04: Deprecate OOREMOTE (OpenOffice/LibreOffice driver) for removal^].

The recommended replacement is to use LibreOffice and the builtin "`Firebird External`" connection option in LibreOffice Base, instead of the "`JDBC`" option with Jaybird on the classpath of LibreOffice.

[#report-actual-pid]
=== Report actual process ID (pid)

The pure Java implementation will now report the actual process ID (pid) in connection property `isc_dpb_process_id`.
The native implementation already did this.

For pure Java connections, the reported process ID can be overridden using the connection property `processId` or the system property `org.firebirdsql.jdbc.pid`.
This feature is retained for backwards compatibility.

When a `SecurityManager` is installed, the entire call-chain needs to have the `RuntimePermission("manageProcess")` to obtain the process ID in pure Java connections.
If this permission check fails, Jaybird will silently ignore it and not set the `isc_dpb_process_id` based on the actual process ID.

[#wire-buffer-sizes]
=== Configurable buffer sizes for the wire protocol

The sizes of a number of buffers used in the wire protocol were increased from 512 bytes to 8192 bytes.
This specifically concerns:

* wire compression -- deflate (compression)
* wire compression -- inflate (decompression)
* wire encryption -- decrypt
+
There is no such buffer for the reverse (encryption), as this is already handled by the general output buffer.

This change might not be desirable in all situations as it increases the total amount of memory per connection, or there can be reasons to further increase these buffers.
To address this, we have added _system properties_ to configure a number of buffers which were previously not configurable:

`org.firebirdsql.wire.deflateBufferSize`::
Buffer size in bytes for deflate (compression).
Has a minimum size of 512 and a default value of 8192.

`org.firebirdsql.wire.inflateBufferSize`::
Buffer size in bytes for inflate (decompression).
Has a minimum size of 512 and a default value of 8192.

`org.firebirdsql.wire.decryptBufferSize`::
Buffer size in bytes for decryption.
Has a minimum size of 512 and a default value 8192.
+
[NOTE]
====
As the decryption input buffer determines the size of the decryption output buffer, the actual allocation is up to twice the specified value.
====

`org.firebirdsql.wire.inputBufferSize`::
Buffer size in bytes for reading data from the socket.
Has a minimum size of 1024 and a default value of 16384.
+
[CAUTION]
====
This property should not be confused with the socket buffer size (configurable with the `socketBufferSize` _connection property_).
Setting this value higher than `socketBufferSize` is unlikely to have any benefits.
====

`org.firebirdsql.wire.outputBufferSize`::
Buffer size in bytes for writing data.
Has a minimum size of 1024 and a default value of 32767.
+
[CAUTION]
====
This property should not be confused with the socket buffer size (configurable with the `socketBufferSize` _connection property_).
Contrary to the input buffer size, setting it higher than `socketBufferSize` might have performance benefits.
====

These properties need to be set before Jaybird is loaded and used (e.g. on the commandline with `-D<propertyName>=<propertyValue`).

[NOTE]
====
The minimum sizes and default values should be considered an implementation detail and might change in a future major version.

The "`deflate`" and "`inflate`" buffers are only used when wire compression is enabled.
The "`decrypt`" buffer is only applied when wire encryption is used (the default with Firebird 3.0 and higher).
====

The order of buffers for input is as follows:

[subs="normal"]
----
Jaybird <= [inflate <=] [decrypt <=] input <= socket
----

The order of buffers for output is as follows:

[subs="normal"]
----
Jaybird => output [=> deflate] => socket
----

A future version may introduce connection properties to control this per connection.

[#event-manager-broken-connection]
=== Broken connection detection for event manager

The event manager now attempts to detect if the underlying database connection is broken.
Once a broken connection is detected, the event manager will attempt to close or forcibly disconnect itself and report itself as not _connected_.

For proper detection of some types of network problems in a timely manner, it may be necessary to configure the `soTimeout` of the event manager _before_ connecting.
When the `createFor(Connection)` method has been used, this can be configured through the `soTimeout` connection property, or -- for pure Java connections only -- the `setNetworkTimeout` method of the `Connection` object.

This detection depends on actual activity, like an event posting a new count, or a new event registration.

[#unsupported-protocol]
=== Pure Java will not connect to unsupported Firebird version by default

The pure Java protocol will by default no longer try the wire protocol versions of unsupported Firebird versions.
This means that -- by default -- only protocol version 13 -- 18 are tried (if there is an implementation of such version).
Attempts to connect to Firebird 2.5 or earlier will result in error _"`connection rejected by remote interface`"_ (`335544421` or `isc_connect_reject`).

As a workaround, the connection property `enableProtocol` can enable unsupported protocols, assuming a suitable protocol implementation is available on the classpath.

This connection property can have the following values:

* A comma-separated list of additional protocol versions to try (e.g. `"11,12"`).
The listed versions are tried in addition to the supported protocol versions.
Non-integer values or unknown protocol versions are silently ignored.
+
It is possible to use the "`masked`" protocol version (e.g. `"32780"` for protocol version 12).
However, we recommend using the unmasked version (e.g. `"12"` for protocol version 12).
* `"*"` -- enable all available protocol versions
* `null` or empty string (`++""++`) -- default behaviour, only use supported protocols

[WARNING]
====
Given these protocol versions and their Firebird version are not supported, there is no guarantee that the driver will function correctly when an unsupported protocol is enabled this way.
Especially things like database metadata could use features that are not supported by older Firebird versions.
We recommend upgrading your Firebird version, or downgrading to a Jaybird version which still supports your Firebird version.

For maximum compatibility, it is recommended to either use `"*"`, or to make sure to include the maximum protocol version of your Firebird version.

Unsupported protocol versions may be removed in future releases of Jaybird.
====

.Firebird versions and protocol versions
[cols="1,1",options="header",]
|===
|Firebird version
|Maximum protocol

|1.0 -- 2.0
|10

|2.1
|11

|2.5
|12

|3.0
|15footnote:[since Firebird 3.0.2, version 13 for 3.0.0 and 3.0.1]footnote:[Jaybird has no protocol 14 implementation]

|4.0
|16footnote:[Jaybird no protocol 17 implementation]

|5.0
|18

|===

[#logging]
=== Logging facade removed

The package `org.firebirdsql.logging` has been removed.
The logging facade from this package has been replaced with the Java Platform Logging API (https://openjdk.org/jeps/264[JEP 264^]).

The Java Platform Logging API by default logs to `java.util.logging`, but it is possible to plugin different logging platforms.
For example, Log4j provides the `log4j-jpl` dependency which will replace the default binding to `java.util.logging` with one to Log4j.

With this change, Jaybird no longer provides an option to specify a custom logger implementation, so the system property `org.firebirdsql.jdbc.loggerImplementation` is no longer supported.
If you need a custom logger, you will need to implement `java.lang.System.Logger` and `java.lang.System.LogFinder` and provide the necessary service loader definition (see the Java documentation for details).

The system properties `org.firebirdsql.jdbc.forceConsoleLogger` and `org.firebirdsql.jdbc.disableLogging` are also no longer supported.
Equivalent behaviour is achieved by configuring the active logging library

[#chacha64]
=== Support for ChaCha64 wire encryption

Support for the "`ChaCha64`" wire encryption -- introduced in Firebird 4.0.1 -- was added for the `PURE_JAVA` protocol.
Given this requires a dependency on the Bouncy Castle provider (`bcprov-jdk18on`), the plugin is made available as a separate artifact: `org.firebirdsql.jdbc:chacha64-plugin` on Maven or `chacha64-plugin-{version_wo_target}.jar` in the distribution zip.

When deploying manually, please make sure to also include the `bcprov-jdk18on-{bc-version}.jar` from the `lib` directory of the distribution zip on the class path.

.Limitations of ChaCha lead to introduction of ChaCha64
[sidebar]
****
The "`ChaCha`" wire encryption introduced in Firebird 4.0 and Jaybird 5 uses a 96-bit nonce and 32-bit counter.
This 32-bit counter limits the amount of data you can transfer to a maximum of 256GiB.
As the Firebird wire protocol doesn't support "`re-keying`" the encryption plugin, this means the connection breaks if 256GiB has been sent or received.
This breaking is done to prevent key re-use, which could make the data stream vulnerable to certain types of cryptological analysis.

To address this, Firebird 4.0.1 added the "`ChaCha64`" wire encryption, which uses a 64-bit nonce and 64-bit counter.
****

As part of this change, Jaybird is now capable of loading `EncryptionPluginSpi` instances using the service loader mechanism.
The API of `EncryptionPluginSpi` and `EncryptionPlugin` and other classes and interfaces in package `org.firebirdsql.gds.ng.wire.crypt` should still be considered unstable and internal API, so use it at your own risk to implement your own plugins.
If you want to use it for implementing your own encryption plugins, let us know on https://groups.google.com/g/firebird-java[firebird-java^].
We can then look at stabilizing the API and considering it formally a public API.

See also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2023-06-chacha64-support.adoc[jdp-2023-06: ChaCha64 Support^]

[#native-library-path]
=== Connection property to specify native library path

A connection property `nativeLibraryPath` was added to specify the _directory_ where `fbclient` (for native connections), or `fbembed` or `fbclient` (for embedded connections) can be loaded.
If a file path is used instead of a directory path, the parent directory will be used for the search path.
In other words, it is not possible to use it load a differently named library.

[CAUTION]
====
This property comes with a very important caveat: it only works for the first native or embedded connection (to a database or service) made within a JVM.
Once any library is loaded, that library is used for all subsequent native and embedded connections.
====

This property is only exposed as a JDBC property.
For data sources, it needs to be set with `setProperty(String, String)` or `setNonStandardProperty(String)`.

The primary use case for this property is for situations where configuring the system property `jna.library.path` is not easy to do (e.g. in third-party applications).

For embedded connections, if there is a valid `FirebirdEmbeddedProvider` on the classpath, it will be used instead of the location specified by `nativeLibraryPath`.

[#package-metadata]
=== Opt-in feature for package information in DatabaseMetaData

Firebird 3.0 added packages, which can contain stored procedures and functions.
The JDBC API does not provide a "`standard`" way of accessing information about packages, or the routines defined in packages.
Instead of adding additional Jaybird-specific metadata methods, we've added an "`opt-in`" feature that provides access through normal metadata methods, using the "`catalog`" to report packages.

This feature can be enabled by setting the connection property `useCatalogAsPackage` to `true`.
When this connection property is enabled, the `DatabaseMetaData` of that connection will have the following changes in behaviour:

* `getCatalogs()` lists packages, with package names in `TABLE_CAT`.
* `getFunctions`, `getFunctionColumns`, `getProcedures`, and `getProcedureColumns` include information on procedures or functions in packages
** Columns `FUNCTION_CAT`/`PROCEDURE_CAT` will report:
*** For packaged procedures and functions -- the package name
*** For normal (non-package) procedures and functions -- an empty string instead of `null` (because of the following rule)
** If parameter `catalog` is `++""++` (empty string), only normal stored procedures or stored functions are reported.
** If parameter `catalog` is `null`, both packaged and normal stored procedures or stored functions are reported.
** For other values of parameter `catalog`, these metadata methods will only return procedures, functions, or their columns of the specified package (exact match, case-sensitive; not a `LIKE` pattern)
** For normal (non-package) procedures and functions, the `SPECIFIC_NAME` column will be the unquoted function or procedure name (same as when `useCatalogAsPackage` is not enabled), and for packaged procedures and functions, it will be `__quoted-package-name__ + '.' + __quoted-routine-name__` (e.g. ``"SOME_PACKAGE"."SOME_FUNCTION"``)
* `getCatalogSeparator()` returns `"."` (string with period).
* `getCatalogTerm()` returns `"PACKAGE"`.
* `isCatalogAtStart()` returns `true`.
* `getMaxCatalogNameLength()` returns 31 or 63 depending on the max identifier length of the database.
* `supportsCatalogsInDataManipulation()` returns `true` (i.e. access selectable stored procedures and functions from packages).
* `supportsCatalogsInProcedureCalls()` returns `true`.
* The other `supportsCatalogsIn__type__()` methods continue to return `false`.
* Other metadata methods with a `catalog` parameter continue to ignore it, just like they do when `useCatalogAsPackage` is disabled.

The `useCatalogAsPackage` connection property does not result in any other behaviour.

Keep in mind, that this is non-standard behaviour, and standard JDBC tools or libraries may not work correctly when this property is enabled.
This feature may be discontinued and removed in the future if Jaybird needs to implement "`real`" catalogs (e.g. because Firebird started supporting catalogs).

See also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2023-09-use-catalog-as-package.adoc[jdp-2023-08: Use Catalog as Package^]

[#client-info]
=== Rewritten client info properties support

Client info properties were introduced in JDBC 4.0 and implemented in Jaybird 2.2.
This support has been rewritten to correct some limitations and problems with the previous implementation.

The new implementation discerns two types of property names:

. without context;
_get_/_set_ in `USER_SESSION` context of `RDB$GET/SET_CONTEXT`
. with context, when the name ends in `@USER_SESSION`, `@USER_TRANSACTION` or `@SYSTEM`;
_get_/_set_ _without_ that suffix in the specified context.
Properties with multiple contexts (e.g. `property@SYSTEM@USER_SESSION`) are not allowed to prevent ambiguity.
Everything else is a property without context.

A property named `<name>@USER_SESSION` is handled identical to `<name>`.
The "`without context`" name is preferred and recommended for `USER_SESSION` properties, and `Connection.getClientInfo()` will use the "`without context`" name as the key for `USER_SESSION` properties.

A property named `<name>@USER_TRANSACTION` is _set_ and _get_ as `<name>` in context `USER_TRANSACTION`.
When a connection is in auto-commit mode, attempts to _set_ or _get_ `USER_TRANSACTION` properties are ignored (nothing is stored, and `null` is returned without accessing the database).

A property named `<name>@SYSTEM` is retrieved as `<name>` in the context `SYSTEM`.
Properties in the `SYSTEM` context are read-only, so they cannot be _set_.
For `Connection.setClientInfo(String, String)`, attempts to _set_ a `SYSTEM` property result in a `SQLClientInfoException`, for `Connection.setClientInfo(Properties)`, `SYSTEM` properties are silently ignored.

Attempts to retrieve non-existent properties, even from `SYSTEM` will return `null` and will not result in an exception.

A connection registers properties known to that specific connection.
By default, only the JDBC-specified properties `ApplicationName`, `ClientUser` and `ClientHostName` (see also below) are known.
A successful _get_ or _set_ of a property will register that property as a known property for the current connection only.

The method `Connection.getClientInfo()` will retrieve only known properties (the default properties and those registered for the current connection).
It will not attempt to query or identify other variables registered in any context.

The method `Connection.setClientInfo(Properties)` clears (sets to `NULL`) known properties in `USER_SESSION` and -- if not in auto-commit -- `USER_TRANSACTION` if they are not included in the `Properties` object.

`DatabaseMetaData.getClientInfoProperties()` reports the JDBC-specified properties only;
it will not report the additional properties registered for the current connection.

The JDBC-specified properties are:

[quote,,JDBC API documentation of java.sql.Connection]
____
`ApplicationName`::
The name of the application currently utilizing the connection
`ClientUser`::
The name of the user that the application using the connection is performing work for.
This may not be the same as the user name that was used in establishing the connection.
`ClientHostname`::
The hostname of the computer the application using the connection is running on.
____

All JDBC-specified properties are _get_ and _set_ in `USER_SESSION`.
On _get_ of `ApplicationName`, if this property is not currently set in `USER_SESSION`, it falls back to _get_ the value from `CLIENT_PROCESS@SYSTEM`.
The `CLIENT_PROCESS@SYSTEM` value can be specified using the connection property `processName` or system property `org.firebirdsql.jdbc.processName`.
The `ClientUser` and `ClientHostname` properties are considered application-specific and have no default value or fallback.

Compared to the previous implementation, the important differences are:

* `Connection.getClientInfo()` now reports properties;
the previous implementation always returned an empty `Properties` object.
* `Connection.getClientInfo(String)` with a property name without context now queries only `USER_SESSION`;
the previous implementation queried `USER_TRANSACTION`, and if not set, fell back to the value from `USER_SESSION`.
To retrieve from `USER_TRANSACTION` in the new implementation, use `<name>@USER_TRANSACTION`.
* `Connection.setClientInfo(Properties)` now clears known properties not included in the `Properties` object;
the previous implementation only _set_ the included properties.
* Successful _get_ or _set_ of a property registers it as known property of the connection and influences behaviour of subsequent calls to `getClientInfo()` and `setClientInfo(Properties)` on that connection
* `DatabaseMetaData.getClientInfoProperties` now reports the JDBC-specified properties, and nothing else;
the previous implementation always returned an empty result set.

.Connection pools and known connection properties
****
If you use a connection pool populated from `org.firebirdsql.ds.FBConnectionPoolDataSource` or `org.firebirdsql.ds.FBXADataSource`, the known properties are reset each time the connection is handed out by the pool.
This assumes the pool uses `getConnection()` from `PooledConnection`/`XAConnection` each time it hands out the connection.
This reset only removes the property name from the list of known properties, it does not clear the property values from `USER_SESSION`.
If properties contain _sensitive_ values you will need to explicitly clear them.

This reset is not applied when using a connection pool which is populated by different means (e.g. from `DriverManager` or from a normal `javax.sql.DataSource` like `org.firebirdsql.ds.FBSimpleDataSource`).
If your connection pool implementation supports custom code to reset a connection, and you need known properties to reset when a connection is reused, make it call `FirebirdConnection.resetKnownClientInfoProperties()`, or call it yourself:

[source,java]
----
if (connection.isWrapperFor(FirebirdConnection.class)) {
    connection.unwrap(FirebirdConnection.class)
            .resetKnownClientInfoProperties();
}
----

In the future, Jaybird may be changed to also perform this reset in `Connection.beginRequest()` and/or `Connection.endRequest()`.
****

See also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2023-11-new-design-client-info-properties.adoc[jdp-2023-11: New design client info properties^]

[#async-fetch]
=== Asynchronous fetching

For pure Java connections, forward-only result sets now perform asynchronous fetches.
Asynchronous fetches are implemented for protocol implementation version 11 and higher (i.e. Firebird 2.1 or higher), but are formally only supported for protocol version 13 and higher (i.e. Firebird 3.0 or higher).

In normal usage of a result set, the first fetch will be a normal synchronous fetch.
If certain conditions are met, subsequent fetches will be performed asynchronously.

The conditions for using asynchronous fetch are considered an implementation detail and may change in point releases.
In Jaybird 6.0.0, the condition to enable asynchronous fetching are:

. The result set has type `FORWARD_ONLY`.
. The result set does not have cursor name set.
. Any synchronous fetch on the statement cursor retrieved at least 15 rows.
Be aware that the server may return fewer rows than the configured fetch size (default is 400), depending on Firebird version, row size and other factors.

When the asynchronous fetch is triggered is also an implementation detail and may change in point releases.
In Jaybird 6.0.0, the condition to perform an asynchronous fetch is:

* Size of the row buffer is equal to the "`low-water mark`".
+
This "`low-water mark`" is calculated as ~33% of the maximum number of rows returned by previous fetches, with a minimum of 10 rows.
+
As a consequence of this condition, reducing the fetch size equal to or less than the "`low-water mark`" may cause asynchronous fetches to stop being triggered, as the buffer size may remain smaller than the "`low-water mark`" (this effect may be reduced if there is other activity on the connection after the asynchronous fetch was performed).
In that case a synchronous fetch is triggered when the buffer is empty.
* Fetch size at time of async fetch is larger than 1.
This may be the configured fetch size, or the fetch size derived taking into account the configured maximum row count.

Native connections do not support this type of asynchronous fetching, but `fbclient` itself provides a different form of internal asynchronous fetching for native connections.

[#modules]
=== Modularization of Jaybird

Jaybird now uses real Java modules.

The available modules are:

* `org.firebirdsql.jaybird` -- main Jaybird driver
* `org.firebirdsql.jaybird.chacha64` -- ChaCha64 wire encryption implementation
* `org.firebirdsql.jna` -- native and embedded protocol implementation using JNA

We've tried to be liberal with exporting the packages from Jaybird, but we have decided not to export some packages because we think they shouldn't normally be accessed by users of Jaybird.
If you run into problems with packages not being exported, please report this on https://groups.google.com/g/firebird-java[firebird-java^] or on https://github.com/FirebirdSQL/jaybird/issues[GitHub^].
Please include an explanation why you need to access a specific package.
As a workaround, you can also add exports yourself with the `--add-exports` commandline option of `java` and `javac` and the `Add-Exports` manifest entry of your application (similar options exist for _opens_).

When the Jaybird JAR files are on the classpath, they should behave as before.
For modular applications, once added to the modulepath instead of the classpath, they will behave in a more restricted fashion.

If you use Jaybird only as a JDBC driver (through `java.sql.DriverManager`), having the driver on the modulepath and having `requires java.sql` in the `module-info.java` of your application should be sufficient.
If your code uses classes and other types from Jaybird, use `requires org.firebirdsql.jaybird`.

The ChaCha64 plugin, `org.firebirdsql.jaybird.chacha64`, will just need to be present on the modulepath to be loaded.

The same goes for the native protocol module, `org.firebirdsql.jna`, but only add it to the modulepath if you actually need native or embedded access.
You also need to replace any `jna-<version>.jar` with `jna-jpms-{jna-version}.jar` (the modular variant of JNA).

If you use `org.firebirdsql.jna` to implement a Firebird embedded provider, you'll need to add `requires org.firebirdsql.jna` and an appropriate `provides org.firebirdsql.jna.embedded.spi.FirebirdEmbeddedProvider with <classname>` in your `module-info.java`.
For compatibility with use on the classpath, it is recommended to also provide the `META-INF/services/org.firebirdsql.jna.embedded.spi.FirebirdEmbeddedProvider` file.

For more information, see also https://github.com/FirebirdSQL/jaybird/blob/master/devdoc/jdp/jdp-2023-13-modularization-of-jaybird.adoc[jdp-2023-13: Modularization of Jaybird^].

[#timestamp-localdate-localtime]
=== `TIMESTAMP` fields now accept `LocalDate` and `LocalTime`

The JDBC specification does not specify support for `LocalDate` and `LocalTime` on `TIMESTAMP` (without time zone).
However, when we introduced support for the `java.time` types, we implemented support for getting `LocalDate` and `LocalTime` (through `getObject`), but did not provide support for setting values of those types (through `setObject`) on `TIMESTAMP`.

We have now addressed this inconsistency, by also introducing support for setting these types on `TIMESTAMP` with the following behaviour:

* `setObject(..., localTime)` sets a `LocalDateTime` derived as `LocalDate.EPOCH.atTime(localTime)` (i.e. on 1970-01-01)
* `setObject(..., localDate)` sets a `LocalDateTime` derived as `localDate.atStartOfDay()` (i.e. at 00:00:00)

// TODO add major changes

[#potentially-breaking-changes]
=== Potentially breaking changes

Jaybird 6 contains a number of changes that might break existing applications.

See also <<compatibility-changes>> for details.

[#other-fixes-and-changes]
=== Other fixes and changes

* Improvement: Setting oversized strings on `CHAR` or `VARCHAR` parameters with character set UTF8 will now throw a `DataTruncation` exception on `setString` (and not set a value) instead of a `SQLException` with a "`string right truncation`" error on execute (https://github.com/FirebirdSQL/jaybird/issues/396[jaybird#396])
+
With this change, the behaviour for UTF8 is now consistent with that of single-byte character sets.
For UTF8, the `DataTruncation` reports the transfer size and data size in Unicode codepoints.
For other multibyte character sets, the `DataTruncation` reports those sizes in bytes.
This change is not applied to UNICODE_FSS, as Firebird 3.0 and earlier do not enforce character length limits for this character set, only byte length limits.
+
The `setBytes` method on `CHAR` and `VARCHAR` parameters only check the byte length limit.
* Improvement: Implemented `java.sql.Connection.abort(Executor)` to forcibly abort a connection (https://github.com/FirebirdSQL/jaybird/issues/496[jaybird#496])
+
The `java.sql.Connection` is marked closed immediately, after which the executor is used to mark client-side statements and result sets as closed, and then closes the actual physical connection.
The close of the physical connection is not a clean close and may result in "`connection reset by peer`" errors (e.g. error 10054 on Windows, error 104 on Linux) logged in `fiebird.log`.
Active transactions may not be rolled back immediately;
this will be delayed until the server detects that the connection was closed.
It is possible that some listeners are not informed of the connection, statement or result set close.
When a security manager is active, calling `abort` requires the `SQLPermission` "`callAbort`".
* Changed: `DatabaseMetaData.getTypeInfo()` column `FIXED_PREC_SCALE` (column 11) now returns `false` for all data types except `NUMERIC` and `DECIMAL` (https://github.com/FirebirdSQL/jaybird/issues/551[jaybird#551])
+
This was done because of the stated requirement "`__can it be a money value__`".
Previously almost all types returned `true` (including -- for example -- `BOOLEAN` and `TIMESTAMP`, which are definitely not money types).
* Consistent use of `BigDecimal.valueOf(double)` instead of a combination of `new BigDecimal(double)` and `BigDecimal.valueOf(double)` (https://github.com/FirebirdSQL/jaybird/issues/553[jaybird#553])
* Switched blob identification in message BLR from `blr_quad` to `blr_blob2` (https://github.com/FirebirdSQL/jaybird/issues/726[jaybird#726])
* Removed `finalize()` methods and -- where it made sense -- replaced them with use of `Cleaner` (https://github.com/FirebirdSQL/jaybird/issues/727[jaybird#727])
* Fixed: `FBResultSetMetaData.getPrecision` would always estimate the precision of `NUMERIC` or `DEICMAL` columns instead of obtaining the actual precision if the column position was 71 or higher (https://github.com/FirebirdSQL/jaybird/issues/731[jaybird#731])
* Optimized the query to retrieve extended field info for `ResultSetMetaData.getPrecision` to only retrieve columns of type `NUMERIC` or `DECIMAL` (https://github.com/FirebirdSQL/jaybird/issues/732[jaybird#732])
* Added methods `List<String> getTypeAliasList()` and `List<String> getSupportedProtocolList()` to `GDSFactoryPlugin`, and deprecated `String[] getTypeAliases()` and `String[] getSupportedProtocols()` for removal in Jaybird 7 or later
* Fixed formatting of `isc_formatted_exception` to not repeat the original parameters of the exception (https://github.com/FirebirdSQL/jaybird/issues/749[jaybird#749])
* Added aliases `ApplicationName` and `applicationName` for connection property `processName` (https://github.com/FirebirdSQL/jaybird/issues/751[jaybird#751])

[#removal-of-deprecated-classes-and-packages]
=== Removal of deprecated classes and packages

See <<removal-of-deprecated-classes-packages-and-methods,Removal of deprecated classes, packages and methods>> in <<compatibility-changes,Compatibility changes>> for more details.

[#compatibility-changes]
== Compatibility changes

Jaybird 6 introduces some changes in compatibility and announces future breaking changes.

*The list might not be complete, if you notice a difference in behavior that is not listed, please https://github.com/FirebirdSQL/jaybird/issues[report it as bug].*
It might have been a change we forgot to document, but it could just as well be an implementation bug.

[#support-for-firebird-25-dropped]
=== Support for Firebird 2.5 dropped

Jaybird 6 has dropped support for Firebird 2.5 (see also https://github.com/FirebirdSQL/jaybird/tree/master/devdoc/jdp/jdp-2021-03-drop-firebird-2-5-support.md[jdp-2021-03: Drop Firebird 2.5 support^]).
In general, we expect the driver to remain functional, but chances are certain metadata -- e.g. `DatabaseMetaData` -- will break if we use features introduced in newer versions.

[[unsupported-protocols-disabled]]
=== Unsupported protocol version disabled by default

The wire protocol versions for Firebird 2.5 and earlier are disabled by default to disallow connection for the pure Java protocol.
Attempts to connect to Firebird 2.5 or earlier will result in error _"`connection rejected by remote interface`"_ (`335544421` or `isc_connect_reject`).
You can use connection property `enableProtocol=*` or -- for example -- `enableProtocol=10,11,12` to re-enable these protocols, or use the native protocol to connect instead.

See also <<unsupported-protocol>>.

[#support-for-java-before-17-dropped]
=== Support for Java versions before Java 17 dropped

Jaybird 5 does not support Java versions before Java 17.
You will need to upgrade to Java 17 or higher, or remain on Jaybird 5.

Jaybird 5 will serve as a form of "`long-term support`" for Java 8 and 11, with maintenance releases at least until the release of Jaybird 7.

[#support-native-embedded]
=== Native and embedded require extra artifact

The main `jaybird` artifact no longer provides native and embedded support.
Add the `jaybird-native` artifact if you use native or embedded (JDBC URL prefix `++jdbc:firebird[sql]:native:++` or `++jdbc:firebird[sql]:embedded:++`).

See also <<native-plugin>>.

[#support-ooremote-dropped]
=== Support for jdbc:firebirdsql:oo: (OpenOffice/LibreOffice driver) dropped

The OOREMOTE protocol (JDBC URL prefix `++jdbc:firebird[sql]:oo:++`) has been removed in Jaybird 6.

The recommended replacement is to use LibreOffice and the builtin "`Firebird External`" connection option in LibreOffice Base, instead of the "`JDBC`" option with Jaybird on the classpath of LibreOffice.

[#removed-prop-timestampuseslocaltmezone]
=== Removed connection property timestampUsesLocalTimezone

The connection property `timestampUsesLocalTimezone` has been removed.
The exact semantics and usage of this property were unclear.
It was previously deprecated in Jaybird 5 for removal in Jaybird 6 or later.

Other code associated with this property was also removed.

[#client-info-compat]
=== Differences in client info property behavior

The rewritten client info properties implementation may result in the following incompatibilities:

* `setClientInfo(Properties)` will now clear all known properties of `USER_SESSION` and -- if not in auto-commit -- `USER_TRANSACTION` which are not included in the `Properties` object;
Jaybird 5 and earlier only set properties listed in the `Properties` object.
The recommended approach is to use `getClientInfo()`, modify the returned `Properties` object (update values, add new properties, and remove properties which should be cleared), and call `setClientInfo(Properties)` with that object.
* Initially, a connection only knows the properties `ApplicationName`, `ClientUser` and `ClientHostname`.
Other properties are registered _for the current connection_ when getting or setting properties.
* `getClientInfo(String)` with a name without context will now always return the value from `USER_SESSION`;
Jaybird 5 and earlier returned the value in `USER_TRANSACTION` and fell back to `USER_SESSION` if the property did not exist in `USER_TRANSACTION`.
To get the value from `USER_TRANSACTION`, use `<name>@USER_TRANSACTION`.
* If the property `ApplicationName` in `USER_SESSION` has no value, it falls back to `CLIENT_PROCESS` in `SYSTEM` (which reports the value of the `processName` connection property);
Jaybird 5 and earlier reported `null` without falling back.

See also <<client-info>>.

[#operation-aware-type-compat]
=== New Operation.Type value for async fetch

With the introduction of async fetch, the `org.firebirdsql.gds.ng.monitor.Operation.Type` enum has two new values added:

[horizontal]
`STATEMENT_ASYNC_FETCH_START`::
Start of async fetch.
Covers sending of the fetch request.
This operation is cancellable.
`STATEMENT_ASYNC_FETCH_COMPLETE`::
Completion of async fetch.
Covers processing the responses of the fetch request.
This operation is not cancellable.
Attempts to cancel this operation will throw an exception.

If you're currently using the `OperationAware` interface to monitor and/or cancel fetches, make sure to also process `STATEMENT_ASYNC_FETCH_START` and/or `STATEMENT_ASYNC_FETCH_COMPLETE` as appropriate.

[#datetime-conversion-changes]
=== Changes in datetime conversions

The conversions of datetime values were overhauled to use the `java.time` types wherever possible.

This results in some minor differences:

* `getString(...)` on a `TIME` field will now render fractional seconds if available
* `setString(...)` on a `TIME` field now has seconds optional and accepts fractional seconds
* `setTime(...)` on a `TIME` field will not set sub-second values (previously this could vary with the millisecond value wrapped by `java.sql.Time`)
* `getString(...)` on a `TIMESTAMP` field will now render without `.0` at the end if the value does not have fractional seconds (e.g. `2023-07-22 12:43:45` instead of `2023-07-22 12:43:45.0`)
* `setString(...)` on a `TIMESTAMP` field now has seconds optional
* `setString(...)` on a `TIMESTAMP` field now also accepts ISO 8601 datetime strings (that is, with a `T` as a separator instead of a space, for example, `2023-07-22 12:43:45` and `2023-07-22T12:43:45` are now both accepted)
* `setDate(...)` on a `TIMESTAMP` field now sets time to 00:00:00 (previously this could vary with the millisecond value wrapped by `java.sql.Date`)
* `setTime(...)` on a `TIMESTAMP` field will now always set at 1970-01-01, and will not set sub-second values (previously this could vary with the millisecond value wrapped by `java.sql.Time`)
* `setTimestamp(...)` on a `CHAR`/`VARCHAR`/`BLOB SUB_TYPE TEXT` field will now set the value without `.0` at the end if the value does not have fractional seconds (e.g. `2023-07-22 12:43:45` instead of `2023-07-22 12:43:45.0`)
* `getTimestamp(...)` on a `CHAR`/`VARCHAR`/`BLOB SUB_TYPE TEXT` field will now also parse ISO 8601 datetime strings (that is, with a `T` as a separator instead of a space, for example, `2023-07-22 12:43:45` and `2023-07-22T12:43:45` are now both accepted), and seconds are now optional
* `getTime(...)` on a `CHAR`/`VARCHAR`/`BLOB SUB_TYPE TEXT` field will now parse values without seconds and values with fractional seconds.
Though it can parse it, the resulting value will not include fractional seconds.
* `setDate(..., Calendar)` on a `CHAR`/`VARCHAR`/`BLOB SUB_TYPE TEXT` field will now use the `Calendar` to rebase the date, this can result in an off-by-one difference in the date compared to previous versions (depending on the time zone set on the `Calendar`)
* `getDate(..., Calendar)`  on a `CHAR`/`VARCHAR`/`BLOB SUB_TYPE TEXT` field will now use the `Calendar` to rebase the date, this can result in an off-by-one difference in the date compared to previous versions (depending on the time zone set on the `Calendar`)
* The `TypeConversionException` thrown by `getDate(...)`, `getTime(...)` and `getTimestamp(...)` on unsupported types may now report `java.time.LocalDate`, `java.time.LocalTime` or `java.time.LocalDateTime` as the type in its error message instead of `java.sql.Date`, `java.sql.Time`, or `java.sql.Timestamp`

// TODO Document compatibility issues

[#removal-of-classes-packages-and-methods-without-deprecation]
=== Removal of classes, packages and methods without deprecation

Below list of removals may look daunting, but if you use Jaybird only as a JDBC driver, through the JDBC API, you're likely unaffected.
Although we list them as removed without deprecation, some were marked as deprecated retroactively in Jaybird 5.0.3 or later.

This section does not include all changes to packages or classes considered internal API.

[#removal-of-packages-without-deprecation]
==== Removal of packages without deprecation

The following packages have been removed in Jaybird 6 without deprecation:

* `org.firebirdsql.logging`;
there is no replacement

Due to modularization, the following packages are no longer accessible when Jaybird is used from the modulepath:

===== `jaybird` dependency

* `org.firebirdsql.gds.ng.dbcrypt.simple`
* `org.firebirdsql.gds.ng.tz`
* `org.firebirdsql.gds.ng.wire.auth.legacy`
* `org.firebirdsql.gds.ng.wire.auth.srp`
* `org.firebirdsql.gds.ng.wire.crypt.arc4`
* `org.firebirdsql.gds.ng.wire.crypt.chacha`
* `org.firebirdsql.gds.ng.wire.version__NN__` (with _NN_, is `10`, `11`, `12`, `13`, `15`, `16` and `18`)
* `org.firebirdsql.jaybird`
* `org.firebirdsql.jaybird.parser`
* `org.firebirdsql.jaybird.props.internal`
* `org.firebirdsql.jaybird.util`
* `org.firebirdsql.jdbc.escape`
* `org.firebirdsql.jdbc.meta`

===== `jaybird-native` dependency

* `org.firebirdsql.gds.impl.jni`
* `org.firebirdsql.gds.ng.jna`
* `org.firebirdsql.jna.embedded`
* `org.firebirdsql.jna.fbclient`

[#removal-of-methods-without-deprecation]
==== Removal of methods without deprecation

The following methods have been removed in Jaybird 6 without deprecation:

* `FBConnection`
** `prepareMetaDataStatement(String, int, int)`;
use `prepareStatement(String, int, int, int, boolean, boolean)`
** `getStatementListener()`;
there is no replacement
** `inTransaction()`;
there is no replacement
* `JaybirdSystemProperties`
** `isForceConsoleLogger()`;
there is no replacement
** `isDisableLogging()`;
there is no replacement
** `getLoggerImplementation()`;
there is no replacement

The following methods had their visibility reduced:

* `FBPooledConnection`
** Constructor `FBPooledConnection(Connection)` to package-private
** Several protected methods were changed to package-private as this class is no longer extensible
* `FBXAConnection`
** Constructor `FBXAConnection(Connection)` to package-private
** Several protected methods were changed to package-private as this class is no longer extensible
* `PooledConnectionHandler`
** Constructor `PooledConnectionHandler(Connection, FBPooledConnection)` to package-private
** Several protected methods were changed to package-private as this class is no longer extensible
* `XAConnectionHandler`
** Constructor `XAConnectionHandler(Connection, FBXAConnection)` to package-private
** Several protected methods were changed to package-private as this class is no longer extensible

[#removal-of-classes-without-deprecation]
==== Removal of classes without deprecation

The following classes have been removed in Jaybird 6 without deprecation:

* `FbLocalDatabaseFactory` -- unused since removal of LOCAL protocol implementation in Jaybird 5
* `DatatypeCoder.RawDateTimeStruct` (semi-internal API) -- use one of the `java.time` types (`LocalDateTime`, `LocalDate` or `LocalTime`).
Though this class is publicly accessible through `ResultSet.getObject/updateObject` and `PreparedStatement.setObject`, it is internal API, and we expect it is unlikely to be actually used in user code.

The following classes are no longer accessible in Jaybird 6:

* `RowValueBuilder` is now package private.

The following classes are no longer extensible in Jaybird 6 as they are now `sealed` or `final`:

* `FBPooledConnection`
** Visibility was also reduced to package-private
* `FBXAConnection`
** Visibility was also reduced to package-private
* `PooledConnectionHandler`
* `XAConnectionHandler`
** Visibility was also reduced to package-private

[#removal-of-constants-without-deprecation]
==== Removal of constants without deprecation

The following constants have been removed in Jaybird 6 without deprecation:

* `JaybirdSystemProperties`
** `FORCE_CONSOLE_LOGGER_PROP`;
there is no replacement
** `DISABLE_LOGGING_PROP`;
there is no replacement
** `LOGGER_IMPLEMENTATION_PROP`;
there is no replacement
* `SQLStateConstants`
** `SQL_STATE_INVALID_CONN_ATTR` (`01S00`) -- it was unused;
there is no replacement
** `SQL_STATE_INVALID_COLUMN` (`HY002`);
replaced by `SQL_STATE_INVALID_DESC_FIELD_ID` (`HY091`)
** `SQL_STATE_INVALID_ARG_VALUE` (`HY009`);
used with wrong meaning, replaced by multiple other constants (`SQL_STATE_INVALID_USE_NULL` (`HY009`, same value), `SQL_STATE_ATT_CANNOT_SET_NOW` (`HY011`) , `SQL_STATE_INVALID_ATTR_VALUE` (`HY024`), `SQL_STATE_INVALID_STRING_LENGTH` (`HY090`))
** `SQL_STATE_INVALID_TRANSACTION_STATE` (`25S01`) -- it was unused;
there is no replacement
** `SQL_STATE_TRANSACTION_ACTIVE` (`25S02`) -- it was unused;
there is no replacement
** `SQL_STATE_TRANSACTION_ROLLED_BACK` (`25S03`) -- it was unused;
there is no replacement
** `SQL_STATE_CONNECTION_FAILURE_IN_TX` (`08007`) -- it was unused;
there is no replacement
** `SQL_STATE_COMM_LINK_FAILURE` (`08S01`) -- it was unused;
there is no replacement

[#removal-of-deprecated-classes-packages-and-methods]
=== Removal of deprecated classes, packages and methods

Below list of removals may look daunting, but if you use Jaybird only as a JDBC driver, through the JDBC API, you're likely unaffected.

[#removal-of-deprecated-packages]
==== Removal of deprecated packages

The following packages have been removed in Jaybird 6:

* `org.firebirdsql.gds.impl.oo`
* `org.firebirdsql.jdbc.oo`

[#removal-of-deprecated-methods]
==== Removal of deprecated methods

The following methods have been removed in Jaybird 6:

* `FirebirdConnectionProperties` +
Changes to the `FirebirdConnectionProperties` interface affect the data source implementations in `org.firebirdsql.ds`, and `FBManagedConnectionFactory`.
** `getDatabase()` and all its implementations, use `DatabaseConnectionProperties.getDatabaseName()`
** `setDatabase(String)` and all its implementations, use `DatabaseConnectionProperties.setDatabaseName(String)`
** `getNonStandardProperty(String)` and all its implementations, use `BaseProperties.getProperty(String)`
** `setNonStandardProperty(String,String)` and all its implementations, use `BaseProperties.setProperty(String,String)`
** `getBuffersNumber` and all its implementations, use `DatabaseConnectionProperties.getPageCacheSize`
** `setBuffersNumber` and all its implementations, use `DatabaseConnectionProperties.setPageCacheSize`
* `IConnectionProperties`
** `short getConnectionDialect()` and all its implementations, use `int DatabaseConnectionProperties.getSqlDialect()`
** `setConnectionDialect(short)`, and all its implementations, use `DatabaseConnectionProperties.setSqlDialect(int)`
* `FBSimpleDataSource.get/setBlobBufferLength`, use `get/setBlobBufferSize`
* `EventManager`
** `get/setHost`, use `get/setServerName`
** `get/setPort`, use `get/setPortNumber`
** `get/setDatabase`, use `get/setDatabaseName`
* `GDSFactory.getJdbcUrl(GDSType, String)`, use `GDSFactory.getJdbcUrl(GDSType, DatabaseConnectionProperties)`
* `FBManagedConnection.getDatabase()`, there is no direct replacement, but the information can be obtained from the connection properties
* `GDSHelper.getIscEncoding()`;
there is no replacement
* `FirebirdConnection.getIscEncoding`;
there is no replacement
* `FBBlob`
** constructors `FBBlob(GDSHelper)` and `FBBlob(GDSHelper, FBObjectListener.BlobListener)`;
use `FBBlob(GDSHelper, FBObjectListener.BlobListener, Config)`
** constructors `FBBlob(GDSHelper c, long blobId)` and `FBBlob(GDSHelper c, long blobId, FBObjectListener.BlobListener blobListener)`;
use `FBBlob(GDSHelper, long, FBObjectListener.BlobListener, Config)`
* `DatabaseConnectionProperties`
** `isTimestampUsesLocalTimezone`/`setTimestampUsesLocalTimezone(boolean)`;
there is no replacement
* `FBSQLException`
** constructor `FBSQLException(String, SQLException)`;
use `FBSQLException(String)` or `FBSQLException(String, String)` followed by `setNextException(SQLException)`
** `getInternalException()`;
use `getCause()`
** `executeServicesOperation(ServiceRequestBuffer)`;
use `executeServicesOperation(FbService, ServiceRequestBuffer)`
* `FirebirdDriver` (and `FBDriver`)
** `newConnectionProperties()` -- was not previously deprecated, see next method
** `connect(FirebirdConnectionProperties)`;
use `FBSimpleDataSource` for programmatic access to connection properties and connection creation

[#removal-of-deprecated-classes]
==== Removal of deprecated classes

The following classes have been removed in Jaybird 6:

* `org.firebirdsql.gds.ng.listeners.DefaultDatabaseListener` -- implementing `DatabaseListener` is now sufficient as all methods in the interface now have a default implementation that does nothing
* `org.firebirdsql.gds.ng.listeners.DefaultStatementListener` -- implementing `StatementListener` is now sufficient as all methods in the interface now have a default implementation that does nothing
* `org.firebirdsql.jdbc.FBConnectionDefaults`, its replacement, `org.firebirdsql.jaybird.props.PropertyConstants`, is considered internal API

[#removal-of-deprecated-constants]
==== Removal of deprecated constants

The following constants have been removed in Jaybird 6:

* All public String constants in `FBDriver`.
The replacement for most constants can be found in `org.firebirdsql.jaybird.props.PropertyNames`, though some will be removed without replacement.
* `ISCConstants.isc_dpb_{asterisk}` that are DPB items, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.DpbItems`.
* `ISCConstants.isc_tpb_{asterisk}` that are TPB items, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.TpbItems`.
* `ISCConstants.isc_spb_{asterisk}` that are SPB items, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.SpbItems`.
* `ISCConstants.isc_bpb_{asterisk}` that are BPB items, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.BpbItems`.
* `ISCConstants.isc_bpb_type_segmented` and `ISCConstants.isc_bpb_type_stream`, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.BpbItems.TypeValues`
* All constants in `DatabaseParameterBuffer`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.DpbItems`.
* All constants in `TransactionParameterBuffer`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.TpbItems`.
* All constants in `ServiceParameterBuffer`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.SpbItems`.
* All constants in `BlobParameterBuffer`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.BpbItems` and `org.firebirdsql.jaybird.fb.constants.BpbItems.TypeValues`.
* All `TPB_{asterisk}` constants in `FirebirdConnection`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.TpbItems`.
* All public String constants in `org.firebirdsql.jdbc.FBConnectionProperties`.
The replacement for most constants can be found in `org.firebirdsql.jaybird.props.PropertyNames`, though some will be removed without replacement.
* `GDSHelper.DEFAULT_BLOB_BUFFER_SIZE`, its replacement, `org.firebirdsql.jaybird.props.PropertyConstants.DEFAULT_BLOB_BUFFER_SIZE`, is considered internal API.
* All constants in `IConnectionProperties`, use the equivalent constant from `org.firebirdsql.jaybird.props.PropertyConstants`, though this class is considered internal API.
* All constants in `IServiceProperties`, use the equivalent constant from `org.firebirdsql.jaybird.props.PropertyConstants`, though this class is considered internal API.
* `PropertyNames.timestampUsesLocalTimezone`;
there is no replacement

[#breaking-changes-internal-api]
=== Breaking changes internal API

The following breaking changes were made to the internal API, like the GDS-ng API in `org.firebirdsql.gds.ng` and sub-packages.
These changes are primarily interesting for implementers of custom GDS-ng implementations or forks of Jaybird, or people using these low-level APIs directly.

[NOTE]
====
Only changes we think are relevant to driver implementers or (internal) API users are documented.
This means there may be undocumented changes to internal API.
If you are confronted with such a change, let us know on https://groups.google.com/g/firebird-java[firebird-java], so we can take this into account when documenting future changes.
====

* `AbstractFbAttachment`
** `getServerVersionInformation()` was changed from `protected` to package-private.
Given the returned type was already package-private, it wasn't really useful for subclasses outside the package anyway.
* `FbWireDatabase`
** `enqueueDeferredAction(DeferredAction)` now throws `SQLException` to be able to handle exceptions for sync actions if there are a lot of deferred packets
* `FbWireOperations`
** `enqueueDeferredAction(DeferredAction)` now throws `SQLException` (see also `FbWireDatabase` above)
* `AbstractFbStatement`
** `setCursorName(String)` is now final;
subclasses need to implement `setCursorNameImpl(String)` to provide the actual implementation.
These implementations do not need to take out the lock, nor notify the exception listener dispatcher, as that is already handled in the final `setCursorName(String)` method.
** The most recent cursor name is now accessible with `protected String getCursorName()`.
Its value is reset to `null` on each prepare.
* `AbstractFbWireStatement`
** `close()` is now final
** `wrapDeferredResponse` received an extra parameter, `boolean requiresSync`.
This parameter signals if the deferred response requires some form of synchronization action to instruct the server to send the response.
When in doubt, use `false` to communicate that no such synchronization is required.
* `DeferredAction`
** `wrapDeferredResponse` received an extra parameter, `boolean requiresSync`.
This parameter signals if the deferred response requires some form of synchronization action to instruct the server to send the response.
When in doubt, use `false` to communicate that no such synchronization is required.
* `AsynchronousChannelListener.Event` was converted to a record, so it is now final, and its getters (`getEventId()` and `getEventCount()`) have been replaced by accessor methods (`eventId()` and `eventCount()`)
* `DbAttachInfo` was converted to a record, so its getters (`getServerName()`, `getPortNumber()` and `getAttachObjectName()`) have been replaced by accessor methods (`serverName()`, `portNumber()`, `attachObjectName()`)
* `XdrInputStream`
** `skipPadding` return type was changed to `void` as the return values was never used in Jaybird code
** `skipFully` was removed, use standard Java `InputStream.skipNBytes` instead
** `readShort` was removed as it was unused
* The no-arg constructor of `FBXAException` was removed
* `FBResultSet.close(boolean)` was removed;
use `close(boolean, CompletionReason)`
* `UnixCrypt` was replaced by `LegacyHash`, which only performs the password hash specific to Firebird legacy authentication
* `GDSFactoryPlugin.getDatabasePath(String, Integer, String)` and `getDatabasePath(String)` no longer throw `GDSException`, but instead throw `SQLException`
* `GDSFactory.getDatabasePath(...)` no longer throw `GDSException`, but instead throw `SQLException`
* `GDSServerVersionException` no longer extends `GDSException`, but instead extends `SQLNonTransientException`
* `GDSException` was significantly modified and deprecated for future removal.
Most of its implementation was removed, and it now extends `SQLException`.
Only the constructors `GDSException(int)`, `GDSException(int, Throwable)` and `GDSException(String)` were retained.
All other constructors and methods have been removed.
* `WireGDSFactoryPlugin`, `NativeGDSFactoryPlugin` and `EmbeddedGDSFactoryPlugin` are now final
* `FbEmbeddedDatabaseFactory` is now final
* `FbClientDatabaseFactory` and `FbEmbeddedDatabaseFactory` now have a private constructor;
use their static `getInstance()` method to obtain an instance
* `DefaultDatatypeCoder.intToBytes(int)` was removed;
use `encodeInt(int)`
* `ChaChaEncryptionPlugin` and `ChaChaEncryptionPluginSpi` are now final
* `CryptSessionConfig`, the JavaBeans-style accessors have been replaced with record-style accessors:
** `getEncryptionIdentifier()` -> `encryptionIdentifier()`
** `getEncryptKey()` -> `encryptKey()`
** `getDecryptKey()` -> `decryptKey()`
** `getSpecificData()` -> `specificData()`
* `EncryptionIdentifier`, some JavaBeans-style accessors have been replaced with record-style accessors:
** `getType()` -> `type()`
** `getPluginName()` -> `pluginName()`
* `KnownServerKey.PluginSpecificData`, the JavaBeans-style accessors have been replaced with record-style accessors:
** `getEncryptionIdentifier()` -> `encryptionIdentifier()`
** `getSpecificData()` -> `specificData()`
* `EncryptionPlugin` and `EncryptionPluginSpi`, the JavaBeans-style accessor has been replaced with a record-style accessor:
** `getEncryptionIdentifier()` -> `encryptionIdentifier()`
* `StringArgument`
** constructor `StringArgument(int, ArgumentType, String)`;
use `StringArgument(int, ArgumentType, String, Encoding)`
* `FBConnection`
** `checkClientInfoSupport()` was removed;
there is no replacement
* `IEncodingFactory`
** `<T extends DatatypeCoder> T getOrCreateDatatypeCoder(Class<T>)` was removed;
its replacements is `<T extends DatatypeCoder> T getOrCreateDatatypeCoder(Class<T>, Function<IEncodingFactory, T>)` where the function is a factory for the desired `DatatypeCoder` instance if it doesn't already exist.
* The following classes in `org.firebirdsql.util` were moved to `org.firebirdsql.jaybird.util`.
The new package is not exported from the module.
** `ByteArrayHelper`
** `ExceptionHelper`
** `IOUtils`
** `Primitives`
** `ReflectionHelper`
** `SQLExceptionChainBuilder`
** `StringUtils`
* `DbMetadataMediator` was moved to package `org.firebirdsql.jdbc` for module accessibility reasons.
* `DatatypeCoder`
** `encodeTimestamp(Timestamp, Calendar, boolean)` was removed;
there is no replacement
** `decodeTimestamp(Timestamp, Calendar, boolean)` was removed;
there is no replacement
** `encodeTimestampCalendar(Timestamp, Calendar)` was removed;
use `encodeLocalDateTime(LocalDateTime)`
** `decodeTimestampCalendar(byte[], Calendar)` was removed;
use `decodeLocalDateTime(byte[])`
** `encodeTimestampRaw(DatatypeCoder.RawDateTimeStruct)` was removed;
use `encodeLocalDateTime(LocalDateTime)`
** `decodeTimestampRaw(byte[])` was removed;
use `decodeLocalDateTime(byte[])`
** `encodeTime(Time, Calendar, boolean)` was removed;
there is no replacement
** `decodeTime(Time, Calendar, boolean)` was removed;
there is no replacement
** `encodeTimeCalendar(Time, Calendar)` was removed;
use `encodeLocalTime(LocalTime)`
** `decodeTimeCalendar(byte[], Calendar)` was removed;
use `decodeLocalTime(byte[])`
** `encodeTimeRaw(DatatypeCoder.RawDateTimeStruct)` was removed;
use `encodeLocalTime(LocalTime)`
** `decodeTimeRaw(byte[])` was removed;
use `decodeLocalTime(byte[])`
** `encodeDate(Date, Calendar)` was removed;
there is no replacement
** `decodeDate(Date, Calendar)` was removed;
there is no replacement
** `encodeDateCalendar(Date, Calendar)` was removed;
use `encodeLocalDate(LocalDate)`
** `decodeDateCalendar(byte[], Calendar)` was removed;
use `decodeLocalDate(byte[])`
** `encodeDateRaw(DatatypeCoder.RawDateTimeStruct)` was removed;
use `encodeLocalDate(LocalDate)`
** `decodeDateRaw(byte[])` was removed;
use `decodeLocalDate(byte[])`

[#breaking-changes-unlikely]
=== Unlikely breaking changes

The following changes might cause issues, though we think this is unlikely:

[#breaking-finalization]
==== Removal of finalization

With the removal of finalization, the replacement cleanup has been simplified, and in some cases left out entirely.

Possible effects include:

* If a close/cleanup is performed by the `Cleaner`, listeners will not get notified.
Given it is unlikely there will not be strong reference to an object if something is still interested in its listener events, we think this is acceptable.
* The closing of a pure Java connection is now simply a socket close handled by the cleanup action of the socket itself.
Server-side this may result in delayed cleanup of a connection and its resources, and occurrences of "`connection reset by peer`" (e.g. error 10054 on Windows).
If you see an increase of these errors, we recommend you hunt for connection leaks in your application.

[#breaking-double-bigdecimal]
==== Conversion from double to BigDecimal

Conversions from `double` to `java.math.BigDecimal` now always use `BigDecimal.valueOf(double)`.
Previously, a combination of `new BigDecimal(double)` and `BigDecimal.valueOf(double)` was used.

This change may result in minor differences in precision or rounding of values.

[#breaking-changes-for-jaybird-7]
=== Breaking changes for Jaybird 7

With Jaybird 7 the following breaking changes will be introduced.

[#removal-of-deprecated-classes-packages-and-methods-7]
==== Removal of deprecated classes, packages and methods

[WARNING]
====
Some deprecations currently listed for removal -- especially of internal API -- may be removed without deprecation later during Jaybird 6 development.
====

[#removal-of-deprecated-methods-7]
===== Removal of deprecated methods

The following methods will be removed in Jaybird 7:

* `GDSFactoryPlugin` (semi-internal API)
** `getTypeAliases()` -- use `getTypeAliasList()`.
It may get removed in Jaybird 7 or later.
** `getSupportedProtocols` -- use `getSupportedProtocolList()`.
It may get removed in Jaybird 7 or later.

[#removal-of-deprecated-classes-7]
===== Removal of deprecated classes

The following classes have been deprecated and will be removed in Jaybird 7:

* `GDSException` -- use `SQLException` or one of its (normal) subclasses.
Previous versions of `GDSFactoryPlugin` declared `throws GDSException` for some methods, but now `throws SQLException`.
To retain some semblance of backwards-compatibility, this class was retrofitted to extend `SQLException`.
It may get removed in Jaybird 7 or later.

[#removal-of-deprecated-constants-7]
==== Removal of deprecated constants

The following constants have been deprecated and will be removed in Jaybird 7:

* `ISCConstants`
** `isc_isc_sql_dialect_conflict_num` (was already deprecated, now for removal);
use `isc_sql_dialect_conflict_num`
** `isc_err_max`;
there is no replacement
* `QuoteStrategy` -- due to addition of methods `appendLiteral` and `quoteLiteral` the original enum names no longer made sense
** `NO_QUOTES` -- use `DIALECT_1`
** `QUOTES` -- use `DIALECT_3`

[#compatibility-notes]
== Compatibility notes

[#type-2-native-and-embedded-driver]
=== Type 2 (native) and embedded driver

Since Jaybird 6, the native and embedded part of the driver has been moved to a separate artifact, `jaybird-native`.
The Jaybird Native GDS Factory plugin uses JNA to access the client library.
If you want to use the Type 2 driver, or Firebird embedded, then you need to include `jaybird-native-{version_example}` and `jna-jpms-{jna-version}.jar` on the classpath.

When using Maven, you need to specify the dependency on `jaybird-native`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird-native</artifactId>
    <version>{version_example}</version>
</dependency>
----

The `fbclient.dll`, `fbembed.dll`, `libfbclient.so`, or `libfbembed.so` need to be on the path, or the location needs to be specified in the system property `jna.library.path` (as an absolute or relative path to the directory/directories containing the library file(s)).

For Windows and Linux, you can add the `org.firebirdsql.jdbc:fbclient` dependency on your classpath to provide the native libraries for the `native` and `local` protocol.
Be aware that this dependency does not support `embedded`.

[source,xml]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>fbclient</artifactId>
    <version>4.0.2.0</artifactId>
</dependency>
----

In the future we may provide JARs with the embedded libraries of a specific Firebird version.
