= Jaybird {version_wo_target} Release Notes
:doctype: book
:docinfo:
:sectanchors:
:forceinclude: true
:keywords: jaybird, firebird, jdbc, sql, database, java
:source-highlighter: prettify
:toc: left
:icons: font
:sectnums:

ifeval::["{version_tag}" != ""]
[WARNING]
====
Jaybird {version_wo_target} is still in development, and intended for testing and evaluation purposes.
We do not recommend this version for use in production environments.

If you come across any issues when using this version, please report them on https://github.com/FirebirdSQL/jaybird/issues.
====
endif::[]

[#jaybird-6-0-x-changelog]
== Jaybird 6.0.x changelog

Changes per Jaybird 6 release.
See also <<whats-new-in-jaybird-6>>.
For known issues, consult <<known-issues>>.

[#known-issues]
== Known issues

* Using a native connection with a Firebird 3.0 or higher client library to a Firebird 2.5 or older server may be slow to connect.
+
Possible workarounds:
+
--
** Use a native URL with the Firebird INET4 protocol (e.g. for `DriverManager` `++jdbc:firebird:native:inet4://<serverName>[:<portNumber>/<databaseName>++`).
** Use the IPv4 address instead of the host name in the connection string
** Use a Firebird 2.5 or earlier `fbclient`.
--
+
This is caused by https://github.com/FirebirdSQL/firebird/issues/4971[firebird#4971]

[#support]
== Support

If you need support with Jaybird, join the https://groups.google.com/g/firebird-java[Firebird-Java Google Group] and mailing list.
You can subscribe by sending an email to link:mailto:firebird-java+subscribe@googlegroups.com[firebird-java+subscribe@googlegroups.com].

Looking for professional support of Jaybird?
Jaybird is now part of the https://tidelift.com/subscription/pkg/maven-org-firebirdsql-jdbc-jaybird?utm_source=maven-org-firebirdsql-jdbc-jaybird&utm_medium=referral&utm_campaign=docs[Tidelift subscription].

See also https://www.firebirdsql.org/file/documentation/drivers_documentation/java/faq.html#where-to-get-help[Where to get help]

[#general-notes]
== General Notes

Jaybird is a JDBC driver suite to connect to Firebird database servers from Java and other Java Virtual Machine (JVM) languages.

This driver does not work on Android, because it uses classes and features not available in Android.

[#about-this-version]
=== About this version

// TODO Describe Jaybird 6

The major changes and new features in Jaybird 5 are:

// TODO List Jaybird 6 changes

Upgrading from Jaybird 5 to 6 should be simple, but please make sure to read <<compatibility-changes>> before using Jaybird 6.
See also <<upgrading-from-jaybird-5-to-jaybird-6>>.

Bug reports about undocumented changes in behavior are appreciated.
Feedback can be sent to the https://groups.google.com/g/firebird-java[Firebird-java mailing list] or reported on the issue tracker https://github.com/FirebirdSQL/jaybird/issues.

[#supported-firebird-versions]
=== Supported Firebird versions

Jaybird {version_wo_target} was tested against Firebird 3.0.10, and 4.0.2 and a recent snapshot of Firebird 5.0, but should also support other Firebird versions from 3.0 and up.

This driver does not support InterBase servers due to Firebird-specific changes in the protocol and database attachment parameters that are sent to the server.

[#supported-java-versions]
=== Supported Java versions

Jaybird 6 supports Java 17 and higher (JDBC 4.3).
Support for earlier Java versions has been dropped.

Given the limited support period for Java 9 and higher versions, we limit support to Java 17 and the most recent LTS version after Java 17 and the latest Java release.
Currently, that means we support Java 17 and 20.

[NOTE]
====
Jaybird 5 will serve as a "`long-term support`" version for Java 8 and 11, with maintenance releases at least until the release of Jaybird 7.
====

Jaybird 6 provides libraries for Java Java 17.

Jaybird 6 is not modularized, but all versions declare the automatic module name `org.firebirdsql.jaybird`.

See also <<java-support>> in <<whats-new-in-jaybird-6>>.

[#specification-support]
=== Specification support

Jaybird supports the following specifications:

|===
| Specification | Notes

| JDBC 4.3
| All JDBC 4.3 methods for features supported by Firebird;
Java 9 and higher supported using the Java 17 driver.

| JTA 1.0.1
| Implementation of `javax.transaction.xa.XAResource` interface via `XADataSource` implementation.
|===

[#getting-jaybird-6]
== Getting Jaybird 6

[#jaybird-version_wo_target]
=== Jaybird {version_wo_target}

[#maven]
==== Maven

Jaybird {version_wo_target} is available on Maven Central:

groupId: `org.firebirdsql.jdbc`, +
artifactId: `jaybird`, +
version: `{version_wo_target}`

ifeval::["{version_tag}" == "-SNAPSHOT"]
NOTE: SNAPSHOT releases are only available from the Sonatype snapshot  repository, https://oss.sonatype.org/content/repositories/snapshots
endif::[]

For example:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>jaybird</artifactId>
    <version>{version_example}</version>
</dependency>
----

If you want to use Type 2 support (native or embedded), you need to explicitly include JNA 5.12.1 as a dependency:

[source,xml]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>5.12.1</version>
</dependency>
----

For Windows and Linux, you can add the `org.firebirdsql.jdbc:fbclient` dependency on your classpath to provide the native libraries for the `native` protocol.
Be aware that this dependency does not support `embedded`.

See also <<type-2-native-and-embedded-driver>>.

[#download]
==== Download

You can download the latest versions from https://www.firebirdsql.org/en/jdbc-driver/

At minimum Jaybird 6 requires `jaybird-{version_wo_target}.jar`.

For native or embedded support, you will need to include `jna-5.12.1.jar` on your classpath.
See also <<type-2-native-and-embedded-driver>>.

[#upgrading-from-jaybird-5-to-jaybird-6]
== Upgrading from Jaybird 5 to Jaybird 6

Please make sure to read <<compatibility-changes,Compatibility changes>> before upgrading to Jaybird 6.

[#maven-2]
=== Maven

Change the version of the dependency to `{version_wo_target}`.
If you're still using the artifact id `jaybird-jdkXX`, change it to `jaybird`.

When your Jaybird dependency defines the exclusion for `javax.resource:connector-api` (see below), you can remove it.

[source,xml]
----
<exclusions>
    <exclusion>
        <groupId>javax.resource</groupId>
        <artifactId>connector-api</artifactId>
    </exclusion>
</exclusions>
----

For more detailed instructions, see also the information on Maven in <<getting-jaybird-6>>.

If you use native or embedded, make sure to update your JNA dependency to version 5.12.1 (Jaybird 6 requires at least JNA 5.12).

[source,xml]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>5.12.1</version>
</dependency>
----

[#manual-install]
=== Manual install

If you manage your dependencies manually, you need to do the following:

. Replace the Jaybird 5 library with the Jaybird 6 version
** `jaybird-5.0.x.<java>.jar` with `jaybird-{version_wo_target}.jar`

[#gotchas]
=== Gotcha's

If you find a problem while upgrading, or other bugs: please report it on https://github.com/FirebirdSQL/jaybird/issues.

For known issues, consult <<known-issues>>.

[#whats-new-in-jaybird-6]
== What's new in Jaybird 6

For a full list of changes, see https://github.com/FirebirdSQL/jaybird/issues?q=label%3A%22fix-version%3A+Jaybird+6%22[Firebird tracker for Jaybird 6].

[#jaybird-version-numbering]
=== Changes in version numbering

Jaybird 6 uses Java 17 as the minimum supported version.
Our expectation is that Java version specific artifacts are no longer needed.
As a consequence, the Java version has been dropped from the version number.
The full version and naming convention is documented in https://github.com/FirebirdSQL/jaybird/blob/v5.0.0-beta-1/devdoc/jdp/jdp-2023-01-version-number-and-naming-scheme.md[jdp-2023-01: Version Number and Naming Scheme]

As a result of these new naming conventions, the following has been changed:

* Maven version: `6.0.0` (was `5.0.0.java8`)
* Distribution zip: `jaybird-6.0.0.zip` (was `jaybird-5.0.0.java8.zip`)
* Jaybird: `jaybird-6.0.0.jar` (was `jaybird-5.0.0.java8.jar`)
* Jaybird sources: `jaybird-6.0.0-sources.jar` (was `jaybird-5.0.0.java8-sources.jar`)
* Jaybird javadoc: `jaybird-6.0.0-javadoc.jar` (was `jaybird-5.0.0.java8-javadoc.jar`)

Furthermore, the client name reported to Firebird 2.5 and higher has been changed from `Jaybird jaybird-5.0.0.java8` to `Jaybird jaybird-6.0.0`.

[#java-support]
=== Java support

[#java-before-17]
==== Java version before 17 no longer supported

Support of Java versions before Java 17 was dropped.

See also https://github.com/FirebirdSQL/jaybird/blob/v5.0.0-beta-1/devdoc/jdp/jdp-2022-03-java-17-minimum-version.md[jdp-2022-03: Java 17 minimum version]

[#java-17-and-higher]
==== Java 17 and higher

Jaybird 6 supports Java 17 and higher (JDBC 4.3).
Most of the JDBC 4.3 features have been implemented (in as far as they are supported by Firebird).

Given the limited support period for Java 17 and higher versions, not all Java releases are supported, see <<supported-java-versions>> for details.

For compatibility with Java 9 modules, Jaybird defines the automatic module name `org.firebirdsql.jaybird`.
This guarantees a stable module name for Jaybird, and allows for future modularization of Jaybird.

[#firebird-support]
=== Firebird support

Support for Firebird 2.5 has been dropped.
See also <<support-for-firebird-25-dropped>>.

Jaybird 6 supports Firebird version 3.0, 4.0, and provides tentative support for Firebird 5.0.

[#ooremote-removed]
=== OOREMOTE (OpenOffice/LibreOffice driver) removed

The OOREMOTE protocol (JDBC URL prefix `jdbc:firebird:oo` and `jdbc:firebirdsql:oo`) has been removed in Jaybird 6.

See also https://github.com/FirebirdSQL/jaybird/tree/master/devdoc/jdp/jdp-2022-04-deprecate-ooremote.md[jdp-2022-04: Deprecate OOREMOTE (OpenOffice/LibreOffice driver) for removal^].

The recommended replacement is to use LibreOffice and the builtin "`Firebird External`" connection option in LibreOffice Base, instead of the "`JDBC`" option with Jaybird on the classpath of LibreOffice.

[#report-actual-pid]
=== Report actual process ID (pid)

The pure Java implementation will now report the actual process ID (pid) in connection property `isc_dpb_process_id`.
The native implementation already did this.

For pure Java connections, the reported process ID can be overridden using the connection property `processId` or the system property `org.firebirdsql.jdbc.pid`.
This feature is retained for backwards compatibility.

When a `SecurityManager` is installed, the entire call-chain needs to have the `RuntimePermission("manageProcess")` to obtain the process ID in pure Java connections.
If this permission check fails, Jaybird will silently ignore it and not set the `isc_dpb_process_id` based on the actual process ID.

[#wire-buffer-sizes]
=== Configurable buffer sizes for the wire protocol

The sizes of a number of buffers used in the wire protocol were increased from 512 bytes to 8192 bytes.
This specifically concerns:

* wire compression -- deflate (compression)
* wire compression -- inflate (decompression)
* wire encryption -- decrypt
+
There is no such buffer for the reverse (encryption), as this is already handled by the general output buffer.

This change might not be desirable in all situations (e.g. it increases the total amount of memory per connection), or there can be reasons to further increase these buffers.
To address this, we have added _system properties_ to configure a number of buffers which were previously not configurable:

`org.firebirdsql.wire.deflateBufferSize`::
Buffer size in bytes for deflate (compression).
Has a minimum size of 512 and a default value of 8192.

`org.firebirdsql.wire.inflateBufferSize`::
Buffer size in bytes for inflate (decompression).
Has a minimum size of 512 and a default value of 8192.

`org.firebirdsql.wire.decryptBufferSize`::
Buffer size in bytes for decryption.
Has a minimum size of 512 and a default value 8192.
+
[NOTE]
====
As the decryption input buffer determines the size of the decryption output buffer, the actual allocation is up to twice the specified value.
====

`org.firebirdsql.wire.inputBufferSize`::
Buffer size in bytes for reading data from the socket.
Has a minimum size of 1024 and a default value of 16384.
+
[CAUTION]
====
This property should not be confused with the socket buffer size (configurable with the `socketBufferSize` _connection property_).
Setting this value higher than `socketBufferSize` is unlikely to have any benefits.
====

`org.firebirdsql.wire.outputBufferSize`::
Buffer size in bytes for writing data.
Has a minimum size of 1024 and a default value of 32767.
+
[CAUTION]
====
This property should not be confused with the socket buffer size (configurable with the `socketBufferSize` _connection property_).
Contrary to the input buffer size, setting it higher than `socketBufferSize` might have performance benefits.
====

These properties need to be set before Jaybird is loaded and used (e.g. on the commandline with `-D<propertyName>=<propertyValue`).

[NOTE]
====
The minimum sizes and default values should be considered an implementation detail and might change in a future major version.

The "`deflate`" and "`inflate`" buffers are only used when wire compression is enabled.
The "`decrypt`" buffer is only applied when wire encryption is used (the default with Firebird 3.0 and higher).
====

The order of buffers for input is as follows:

[subs="normal"]
----
Jaybird <= [inflate <=] [decrypt <=] input <= socket
----

The order of buffers for output is as follows:

[subs="normal"]
----
Jaybird => output [=> deflate] => socket
----

A future version may introduce connection properties to control this per connection.

[#event-manager-broken-connection]
=== Broken connection detection for event manager

The event manager now attempts to detect if the underlying database connection is broken.
Once a broken connection is detected, the event manager will attempt to close or forcibly disconnect itself and report itself as not _connected_.

For proper detection of some types of network problems in a timely manner, it may be necessary to configure the `soTimeout` of the event manager _before_ connecting.
When the `createFor(Connection)` method has been used, this can be configured through the `soTimeout` connection property, or -- for pure Java connections only -- the `setNetworkTimeout` method of the `Connection` object.

This detection depends on actual activity, like an event posting a new count, or a new event registration.

[#unsupported-protocol]
=== Pure Java will no connect to unsupported Firebird version by default

The pure Java protocol will by default no longer try the wire protocol versions of unsupported Firebird versions.
This means that -- by default -- only protocol version 13 -- 18 are tried (if there is an implementation of such version).
Attempts to connect to Firebird 2.5 or earlier will result in error _"`connection rejected by remote interface`"_ (`335544421` or `isc_connect_reject`).

As a workaround, the connection property `enableProtocol` can enable unsupported protocols, assuming a suitable protocol implementation is available on the classpath.

This connection property can have the following values:

* A comma-separated list of additional protocol versions to try (e.g. `"11,12"`).
The listed versions are tried in addition to the supported protocol versions.
Non-integer values or unknown protocol versions are silently ignored.
+
It is possible to use the "`masked`" protocol version (e.g. `"32780"` for protocol version 12).
However, we recommend using the unmasked version (e.g. `"12"` for protocol version 12).
* `"*"` -- enable all available protocol versions
* `null` or empty string (`++""++`) -- default behaviour, only use supported protocols

[WARNING]
====
Given these protocol versions and their Firebird version are not supported, there is no guarantee that the driver will function correctly when an unsupported protocol is enabled this way.
Especially things like database metadata could use features that are not supported by older Firebird versions.
We recommend upgrading your Firebird version, or downgrading to a Jaybird version which still supports your Firebird version.

For maximum compatibility, it is recommended to either use `"*"`, or to make sure to include the maximum protocol version of your Firebird version.

Unsupported protocol versions may be removed in future releases of Jaybird.
====

.Firebird versions and protocol versions
[cols="1,1",options="header",]
|===
|Firebird version
|Maximum protocol

|1.0 -- 2.0
|10

|2.1
|11

|2.5
|12

|3.0
|15footnote:[since Firebird 3.0.2, version 13 for 3.0.0 and 3.0.1]footnote:[Jaybird has no protocol 14 implementation]

|4.0
|16footnote:[Jaybird no protocol 17 implementation]

|5.0
|18

|===

// TODO add major changes

[#potentially-breaking-changes]
=== Potentially breaking changes

Jaybird 6 contains a number of changes that might break existing applications.

See also <<compatibility-changes>> for details.

[#other-fixes-and-changes]
=== Other fixes and changes

* Improvement: Setting oversized strings on `CHAR` or `VARCHAR` parameters with character set UTF8 will now throw a `DataTruncation` exception on `setString` (and not set a value) instead of a `SQLException` with a "`string right truncation`" error on execute (https://github.com/FirebirdSQL/jaybird/issues/396[jaybird#396])
+
With this change, the behaviour for UTF8 is now consistent with that of single-byte character sets.
For UTF8, the `DataTruncation` reports the transfer size and data size in Unicode codepoints.
For other multibyte character sets, the `DataTruncation` reports those sizes in bytes.
This change is not applied to UNICODE_FSS, as Firebird 3.0 and earlier do not enforce character length limits for this character set, only byte length limits.
+
The `setBytes` method on `CHAR` and `VARCHAR` parameters only check the byte length limit.
* Changed: `DatabaseMetaData.getTypeInfo()` column `FIXED_PREC_SCALE` (column 11) now returns `false` for all data types except `NUMERIC` and `DECIMAL` (https://github.com/FirebirdSQL/jaybird/issues/551[jaybird#551])
+
This was done because of the stated requirement "`__can it be a money value__`".
Previously almost all types returned `true` (including -- for example -- `BOOLEAN` and `TIMESTAMP`, which are definitely not money types).
* Consistent use of `BigDecimal.valueOf(double)` instead of a combination of `new BigDecimal(double)` and `BigDecimal.valueOf(double)` (https://github.com/FirebirdSQL/jaybird/issues/553[jaybird#553])
* Removed `finalize()` methods and -- where it made sense -- replaced them with use of `Cleaner` (https://github.com/FirebirdSQL/jaybird/issues/727[jaybird#727])
* Fixed: `FBResultSetMetaData.getPrecision` would always estimate the precision of `NUMERIC` or `DEICMAL` columns instead of obtaining the actual precision if the column position was 71 or higher (https://github.com/FirebirdSQL/jaybird/issues/731[jaybird#731])
* Optimized the query to retrieve extended field info for `ResultSetMetaData.getPrecision` to only retrieve columns of type `NUMERIC` or `DECIMAL` (https://github.com/FirebirdSQL/jaybird/issues/732[jaybird#732])
* Added methods `List<String> getTypeAliasList()` and `List<String> getSupportedProtocolList()` to `GDSFactoryPlugin`, and deprecated `String[] getTypeAliases()` and `String[] getSupportedProtocols()` for removal in Jaybird 7 or later

[#removal-of-deprecated-classes-and-packages]
=== Removal of deprecated classes and packages

See <<removal-of-deprecated-classes-packages-and-methods,Removal of deprecated classes, packages and methods>> in <<compatibility-changes,Compatibility changes>> for more details.

[#compatibility-changes]
== Compatibility changes

Jaybird 6 introduces some changes in compatibility and announces future breaking changes.

*The list might not be complete, if you notice a difference in behavior that is not listed, please https://github.com/FirebirdSQL/jaybird/issues[report it as bug].*
It might have been a change we forgot to document, but it could just as well be an implementation bug.

[#support-for-firebird-25-dropped]
=== Support for Firebird 2.5 dropped

Jaybird 6 has dropped support for Firebird 2.5 (see also https://github.com/FirebirdSQL/jaybird/tree/master/devdoc/jdp/jdp-2021-03-drop-firebird-2-5-support.md[jdp-2021-03: Drop Firebird 2.5 support^]).
In general, we expect the driver to remain functional, but chances are certain metadata -- e.g. `DatabaseMetaData` -- will break if we use features introduced in newer versions.

[[unsupported-protocols-disabled]]
=== Unsupported protocol version disabled by default

The wire protocol versions for Firebird 2.5 and earlier are disabled by default to disallow connection for the pure Java protocol.
Attempts to connect to Firebird 2.5 or earlier will result in error _"`connection rejected by remote interface`"_ (`335544421` or `isc_connect_reject`).
You can use connection property `enableProtocol=*` or -- for example -- `enableProtocol=10,11,12` to re-enable these protocols, or use the native protocol to connect instead.

See also <<unsupported-protocol>>.

[#support-for-java-before-17-dropped]
=== Support for Java versions before Java 17 dropped

Jaybird 5 does not support Java versions before Java 17.
You will need to upgrade to Java 17 or higher, or remain on Jaybird 5.

Jaybird 5 will serve as a form of "`long-term support`" for Java 8 and 11, with maintenance releases at least until the release of Jaybird 7.

[#support-ooremote-dropped]
=== Support for jdbc:firebirdsql:oo: (OpenOffice/LibreOffice driver) dropped

The OOREMOTE protocol (JDBC URL prefix `jdbc:firebird:oo` and `jdbc:firebirdsql:oo`) has been removed in Jaybird 6.

The recommended replacement is to use LibreOffice and the builtin "`Firebird External`" connection option in LibreOffice Base, instead of the "`JDBC`" option with Jaybird on the classpath of LibreOffice.

// TODO Document compatibility issues

[#removal-of-classes-packages-and-methods-without-deprecation]
=== Removal of classes, packages and methods without deprecation

[#removal-of-packages-without-deprecation]
==== Removal of packages without deprecation

The following packages have been removed in Jaybird 6 without deprecation:

* `FbLocalDatabaseFactory` -- unused since removal of LOCAL protocol implementation in Jaybird 5.

[#removal-of-methods-without-deprecation]
==== Removal of methods without deprecation

The following methods have been removed in Jaybird 6 without deprecation:

* `FBConnection.prepareMetaDataStatement(String, int,int)`;
use `prepareStatement(String, int, int, int, boolean, boolean)`

[#removal-of-classes-without-deprecation]
==== Removal of classes without deprecation

The following classes have been removed in Jaybird 6 without deprecation:


The following classes are no longer accessible in Jaybird 6:

* `RowValueBuilder` is now package private.

[#removal-of-constants-without-deprecation]
==== Removal of constants without deprecation

The following constants have been removed in Jaybird 6 without deprecation:

[#removal-of-deprecated-classes-packages-and-methods]
=== Removal of deprecated classes, packages and methods

[#removal-of-deprecated-packages]
==== Removal of deprecated packages

The following packages have been removed in Jaybird 6:

* `org.firebirdsql.gds.impl.oo`
* `org.firebirdsql.jdbc.oo`

[#removal-of-deprecated-methods]
==== Removal of deprecated methods

The following methods have been removed in Jaybird 6:

* `FirebirdConnectionProperties` +
Changes to the `FirebirdConnectionProperties` interface affect the data source implementations in `org.firebirdsql.ds`, and `FBManagedConnectionFactory`.
** `getDatabase()` and all its implementations, use `DatabaseConnectionProperties.getDatabaseName()`
** `setDatabase(String)` and all its implementations, use `DatabaseConnectionProperties.setDatabaseName(String)`
** `getNonStandardProperty(String)` and all its implementations, use `BaseProperties.getProperty(String)`
** `setNonStandardProperty(String,String)` and all its implementations, use `BaseProperties.setProperty(String,String)`
** `getBuffersNumber` and all its implementations, use `DatabaseConnectionProperties.getPageCacheSize`
** `setBuffersNumber` and all its implementations, use `DatabaseConnectionProperties.setPageCacheSize`
* `IConnectionProperties`
** `short getConnectionDialect()` and all its implementations, use `int DatabaseConnectionProperties.getSqlDialect()`
** `setConnectionDialect(short)`, and all its implementations, use `DatabaseConnectionProperties.setSqlDialect(int)`
* `FBSimpleDataSource.get/setBlobBufferLength`, use `get/setBlobBufferSize`
* `EventManager`
** `get/setHost`, use `get/setServerName`
** `get/setPort`, use `get/setPortNumber`
** `get/setDatabase`, use `get/setDatabaseName`
* `GDSFactory.getJdbcUrl(GDSType, String)`, use `GDSFactory.getJdbcUrl(GDSType, DatabaseConnectionProperties)`
* `FBManagedConnection.getDatabase()`, there is no direct replacement, but the information can be obtained from the connection properties
* `GDSHelper.getIscEncoding()`;
there is no replacement
* `FirebirdConnection.getIscEncoding`;
there is no replacement

[#removal-of-deprecated-classes]
==== Removal of deprecated classes

The following classes have been removed in Jaybird 6:

* `org.firebirdsql.gds.ng.listeners.DefaultDatabaseListener` -- implementing `DatabaseListener` is now sufficient as all methods in the interface now have a default implementation that does nothing
* `org.firebirdsql.gds.ng.listeners.DefaultStatementListener` -- implementing `StatementListener` is now sufficient as all methods in the interface now have a default implementation that does nothing
* `org.firebirdsql.jdbc.FBConnectionDefaults`, its replacement, `org.firebirdsql.jaybird.props.PropertyConstants`, is considered internal API

[#removal-of-deprecated-constants]
==== Removal of deprecated constants

The following constants have been removed in Jaybird 6:

* All public String constants in `FBDriver`.
The replacement for most constants can be found in `org.firebirdsql.jaybird.props.PropertyNames`, though some will be removed without replacement.
* `ISCConstants.isc_dpb_{asterisk}` that are DPB items, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.DpbItems`.
* `ISCConstants.isc_tpb_{asterisk}` that are TPB items, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.TpbItems`.
* `ISCConstants.isc_spb_{asterisk}` that are SPB items, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.SpbItems`.
* `ISCConstants.isc_bpb_{asterisk}` that are BPB items, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.BpbItems`.
* `ISCConstants.isc_bpb_type_segmented` and `ISCConstants.isc_bpb_type_stream`, the replacement is the constant with the same name in `org.firebirdsql.jaybird.fb.constants.BpbItems.TypeValues`
* All constants in `DatabaseParameterBuffer`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.DpbItems`.
* All constants in `TransactionParameterBuffer`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.TpbItems`.
* All constants in `ServiceParameterBuffer`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.SpbItems`.
* All constants in `BlobParameterBuffer`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.BpbItems` and `org.firebirdsql.jaybird.fb.constants.BpbItems.TypeValues`.
* All `TPB_{asterisk}` constants in `FirebirdConnection`, use the equivalent constant from `org.firebirdsql.jaybird.fb.constants.TpbItems`.
* All public String constants in `org.firebirdsql.jdbc.FBConnectionProperties`.
The replacement for most constants can be found in `org.firebirdsql.jaybird.props.PropertyNames`, though some will be removed without replacement.
* `GDSHelper.DEFAULT_BLOB_BUFFER_SIZE`, its replacement, `org.firebirdsql.jaybird.props.PropertyConstants.DEFAULT_BLOB_BUFFER_SIZE`, is considered internal API.
* All constants in `IConnectionProperties`, use the equivalent constant from `org.firebirdsql.jaybird.props.PropertyConstants`, though this class is considered internal API.

[#breaking-changes-internal-api]
=== Breaking changes internal API

The following breaking changes were made to the internal API, like the GDS-ng API in `org.firebirdsql.gds.ng` and sub-packages.
These changes are primarily interesting for implementers of custom GDS-ng implementations or forks of Jaybird, or people using these low-level APIs directly.

[NOTE]
====
Only changes we think are relevant to driver implementers or (internal) API users are documented.
This means there may be undocumented changes to internal API.
If you are confronted with such a change, let us know on https://groups.google.com/g/firebird-java[firebird-java], so we can take this into account when documenting future changes.
====

* `AbstractFbWireStatement.close()` is now final
* `AsynchronousChannelListener.Event` was converted to a record, so it is now final, and its getters (`getEventId()` and `getEventCount()`) have been replaced by accessor methods (`eventId()` and `eventCount()`)
* `DbAttachInfo` was converted to a record, so its getters (`getServerName()`, `getPortNumber()` and `getAttachObjectName()`) have been replaced by accessor methods (`serverName()`, `portNumber()`, `attachObjectName()`)
* `XdrInputStream`
** `skipPadding` return type was changed to `void` as the return values was never used in Jaybird code
** `skipFully` was removed, use standard Java `InputStream.skipNBytes` instead
** `readShort` was removed as it was unused
* The no-arg constructor of `FBXAException` was removed
* `FBResultSet.close(boolean)` was removed;
use `close(boolean, CompletionReason)`
* `UnixCrypt` was replaced by `LegacyHash`, which only performs the password hash specific to Firebird legacy authentication
* `GDSFactoryPlugin.getDatabasePath(String, Integer, String)` and `getDatabasePath(String)` no longer throw `GDSException`, but instead throw `SQLException`
* `GDSFactory.getDatabasePath(...)` no longer throw `GDSException`, but instead throw `SQLException`
* `GDSServerVersionException` no longer extends `GDSException`, but instead extends `SQLNonTransientException`
* `GDSException` was significantly modified and deprecated for future removal.
Most of its implementation was removed, and it now extends `SQLException`.
Only the constructors `GDSException(int)`, `GDSException(int, Throwable)` and `GDSException(String)` were retained.
All other constructors and methods have been removed.
* `WireGDSFactoryPlugin`, `NativeGDSFactoryPlugin` and `EmbeddedGDSFactoryPlugin` are now final
* `DefaultDatatypeCoder.intToBytes(int)` was removed;
use `encodeInt(int)`

[#breaking-changes-unlikely]
=== Unlikely breaking changes

The following changes might cause issues, though we think this is unlikely:

[#breaking-finalization]
==== Removal of finalization

With the removal of finalization, the replacement cleanup has been simplified, and in some cases left out entirely.

Possible effects include:

* If a close/cleanup is performed by the `Cleaner`, listeners will not get notified.
Given it is unlikely there will not be strong reference to an object if something is still interested in its listener events, we think this is acceptable.
* The closing of a pure Java connection is now simply a socket close handled by the cleanup action of the socket itself.
Server-side this may result in delayed cleanup of a connection and its resources, and occurrences of "`connection reset by peer`" (e.g. error 10054 on Windows).
If you see an increase of these errors, we recommend you hunt for connection leaks in your application.

[#breaking-double-bigdecimal]
==== Conversion from double to BigDecimal

Conversions from `double` to `java.math.BigDecimal` now always use `BigDecimal.valueOf(double)`.
Previously, a combination of `new BigDecimal(double)` and `BigDecimal.valueOf(double)` was used.

This change may result in minor differences in precision or rounding of values.

[#breaking-changes-for-jaybird-7]
=== Breaking changes for Jaybird 7

With Jaybird 7 the following breaking changes will be introduced.

[#removal-of-deprecated-classes-packages-and-methods-7]
==== Removal of deprecated classes, packages and methods

[#removal-of-deprecated-methods-7]
===== Removal of deprecated methods

The following methods will be removed in Jaybird 7:

* `GDSFactoryPlugin`
** `getTypeAliases()` -- use `getTypeAliasList()`.
It may get removed in Jaybird 7 or later.
** `getSupportedProtocols` -- use `getSupportedProtocolList()`.
It may get removed in Jaybird 7 or later.

[#removal-of-deprecated-classes-7]
===== Removal of deprecated classes

The following classes have been deprecated and will be removed in Jaybird 7:

* `GDSException` -- use `SQLException` or one of its (normal) subclasses.
Previous versions of `GDSFactoryPlugin` declared `throws GDSException` for some methods, but now `throws SQLException`.
To retain some semblance of backwards-compatibility, this class was retrofitted to extend `SQLException`.
It may get removed in Jaybird 7 or later.

[#removal-of-deprecated-constants-7]
==== Removal of deprecated constants

The following constants have been deprecated and will be removed in Jaybird 7:


[#compatibility-notes]
== Compatibility notes

[#type-2-native-and-embedded-driver]
=== Type 2 (native) and embedded driver

Jaybird uses JNA to access the client library.
If you want to use the Type 2 driver, or Firebird embedded, then you need to include `jna-5.12.1.jar` on the classpath.

When using Maven, you need to specify the dependency on JNA yourself, as we don't depend on it by default (it is specified as an optional dependency):

[source,xml]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>5.12.1</artifactId>
</dependency>
----

The `fbclient.dll`, `fbembed.dll`, `libfbclient.so`, or `libfbembed.so` need to be on the path, or the location needs to be specified in the system property `jna.library.path` (as an absolute or relative path to the directory/directories containing the library file(s)).

For Windows and Linux, you can add the `org.firebirdsql.jdbc:fbclient` dependency on your classpath to provide the native libraries for the `native` and `local` protocol.
Be aware that this dependency does not support `embedded`.

[source,xml]
----
<dependency>
    <groupId>org.firebirdsql.jdbc</groupId>
    <artifactId>fbclient</artifactId>
    <version>4.0.2.0</artifactId>
</dependency>
----

In the future we will move the Type 2 support to a separate library and provide JNA-compatible jars that provide the embedded libraries of a specific Firebird version.
