package org.firebirdsql.jdbc.oo;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.firebirdsql.gds.impl.GDSHelper;
import org.firebirdsql.jdbc.*;
import org.firebirdsql.jdbc.FBObjectListener.StatementListener;

public class OOStatement extends FBStatement {

    public OOStatement(GDSHelper c, int rsType, int rsConcurrency,
            int rsHoldability, StatementListener statementListener)
            throws SQLException {
        super(c, rsType, rsConcurrency, rsHoldability, statementListener);
    }

    public void completeStatement() throws SQLException {
        if (!completed) notifyStatementCompleted();
    }

    public boolean execute(String sql, int autoGeneratedKeys)
            throws SQLException {
        throw new FBDriverNotCapableException();
    }

    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        throw new FBDriverNotCapableException();
    }

    public boolean execute(String sql, String[] columnNames)
            throws SQLException {
        throw new FBDriverNotCapableException();
    }

    public int executeUpdate(String sql, int autoGeneratedKeys)
            throws SQLException {
        throw new FBDriverNotCapableException();
    }

    public int executeUpdate(String sql, int[] columnIndexes)
            throws SQLException {
        throw new FBDriverNotCapableException();
    }

    public int executeUpdate(String sql, String[] columnNames)
            throws SQLException {
        throw new FBDriverNotCapableException();
    }

    public ResultSet getGeneratedKeys() throws SQLException {
        throw new FBDriverNotCapableException();
    }

}
