package org.firebirdsql.gds.ng;


import org.firebirdsql.gds.BlobParameterBuffer;
import org.firebirdsql.gds.ng.fields.RowValue;
import org.firebirdsql.gds.ng.listeners.ExceptionListenable;

import java.io.IOException;
import java.sql.SQLException;

/**
 * Interface for batch operations.
 * <p>
 * All methods defined in this interface are required to notify all {@code SQLException} thrown from the methods
 * defined in this interface.
 * </p>
 *
 * @author <a href="mailto:vasiliy.yashkov@red-soft.ru">Vasiliy Yashkov</a>
 * @since 4.0
 */
public interface FbBatch extends ExceptionListenable {

    /**
     * @return Transaction currently associated with this batch.
     */
    FbTransaction getTransaction();

    /**
     * @return The database connection that created this batch.
     */
    FbDatabase getDatabase();

    /**
     * Add data to this batch.
     */
    void addBatch() throws SQLException;

    /**
     * Add a row to this batch.
     */
    void addBatch(RowValue rowValue) throws SQLException;

    /**
     * Add existing blob in this batch.
     */
    void addBlob(int index, long blobId) throws SQLException;

    /**
     * Add blob in this batch and ID will be generated by engine.
     */
    FbBlob addBlob(int index, byte[] inBuffer, BlobParameterBuffer buffer) throws SQLException;

    /**
     * Add blob in this batch.
     */
    FbBlob addBlob(int index, byte[] inBuffer, long blobId, BlobParameterBuffer buffer) throws SQLException;

    /**
     * Add blob in this batch.
     */
    void addSegmentedBlob(int index, long blobId, BlobParameterBuffer buffer) throws SQLException, IOException;

    /**
     * Append blob data.
     */
    void appendBlobData(byte[] inBuffer) throws SQLException;

    /**
     * Add data to existing blob.
     */
    void appendBlobData(byte[] data, long blobId) throws IOException;

    /**
     * Add data to segmented blob.
     */
    void addBlobSegment(byte[] data, boolean lastSegment) throws IOException, SQLException;

    /**
     * Add blob stream.
     */
    void addBlobStream(byte[] inBuffer) throws SQLException;

    /**
     * Register existing blob.
     */
    void registerBlob(int index, long existingBlob, long blobId) throws SQLException;

    /**
     * Execute tis batch and
     * @return {@link FbBatchCompletionState} completion state.
     */
    FbBatchCompletionState execute() throws SQLException;

    /**
     * Cancel the batch execution.
     */
    void cancel() throws SQLException;

    /**
     * @return Blob alignment.
     */
    int getBlobAlignment() throws SQLException;

    /**
     * @return The metadata that contained in this batch.
     */
    FbMessageMetadata getMetadata() throws SQLException;

    /**
     * Set default batch parameters buffer.
     */
    void setDefaultBpb(int parLength, byte[] par) throws SQLException;

    /**
     * @return The statement that contains prepared fields info.
     */
    FbStatement getStatement() throws SQLException;

    void release() throws SQLException;
}
