package org.firebirdsql.jna.fbclient;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 * @since 4.0
 */
public class FB_DEC16 extends Structure {

	public long[] fb_data = new long[1];
	public FB_DEC16() {
		super();
	}

	protected List getFieldOrder() {
		return Arrays.asList("fb_data");
	}
	public FB_DEC16(long fb_data[]) {
		super();
		if ((fb_data.length != this.fb_data.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.fb_data = fb_data;
	}

	public FB_DEC16(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends FB_DEC16 implements Structure.ByReference {

	};
	public static class ByValue extends FB_DEC16 implements Structure.ByValue {
		
	};
}
