// SPDX-FileCopyrightText: Copyright 2014-2024 Mark Rotteveel
// SPDX-License-Identifier: LGPL-2.1-or-later
package org.firebirdsql.jna.fbclient;

import com.sun.jna.Structure;

/**
 * JNA wrapper for ISC_ARRAY_BOUND.
 * <p>
 * This file was initially autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>, a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.
 * </p>
 * <p>
 * This file was modified manually, <strong>do not automatically regenerate!</strong>
 * </p>
 * @since 3.0
 */
@Structure.FieldOrder({ "array_bound_lower", "array_bound_upper" })
@SuppressWarnings({ "unused", "java:S101", "java:S116", "java:S117", "java:S1104", "java:S2160" })
public class ISC_ARRAY_BOUND extends Structure {
	public short array_bound_lower;
	public short array_bound_upper;

	public ISC_ARRAY_BOUND() {
		super();
	}

	public ISC_ARRAY_BOUND(short array_bound_lower, short array_bound_upper) {
		super();
		this.array_bound_lower = array_bound_lower;
		this.array_bound_upper = array_bound_upper;
	}

	public static class ByReference extends ISC_ARRAY_BOUND implements Structure.ByReference {
	}
	
	public static class ByValue extends ISC_ARRAY_BOUND implements Structure.ByValue {
	}
}
