/*
 * Firebird Open Source J2ee connector - jdbc driver
 *
 * Distributable under LGPL license.
 * You may obtain a copy of the License at http://www.gnu.org/copyleft/lgpl.html
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * LGPL License for more details.
 *
 * This file was created by members of the firebird development team.
 * All individual contributions remain the Copyright (C) of those
 * individuals.  Contributors to this file are either listed here or
 * can be obtained from a CVS history command.
 *
 * All rights reserved.
 */

package org.firebirdsql.jdbc;
import java.sql.ResultSet;

/**
 * This interface defines set of listeners that will be called in different
 * situations.
 * 
 * @author <a href="mailto:rrokytskyy@users.sourceforge.net">Roman Rokytskyy</a>
 */
public interface FBObjectListener {
    
    /**
     * Listener for the events generated by the result set.
     */
    interface ResultSetListener {
        
        /**
         * Notify listener that result set was closed.
         * 
         * @param rs result set that was closed.
         */
        void resultSetClosed(ResultSet rs);
    }
    
}