name: build-only
on: [push,pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Ant
        run: ./build.sh jars
      - name: build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: output/lib
          retention-days: 1
