name: build-only
on: [push,pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808
      - name: Build with Gradle
        run: ./gradlew assemble -PbuildProfile=java11
      - name: build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs
          compression-level: 0
          retention-days: 1
