name: run-tests
on: [push,pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        java:
          - version: 8
            javaInstall: |
              8
              17
            buildProfile: 8
            testProfile: 8
          - version: 11
            javaInstall: |
              11
              17
            buildProfile: 11
            testProfile: 11
          - version: 11-test-17
            javaInstall: |
              11
              17
            buildProfile: 11
            testProfile: 17
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: juarezr/firebirdsql-github-action@v2.3.0
        with:
          version: '5.0.4'
          firebird_root_password: 'masterkey'
          firebird_conf: 'WireCrypt=Enabled,AuthServer=Srp256;Srp;Legacy_Auth;Srp224;Srp384;Srp512,UserManager=Srp;Legacy_UserManager'
      - uses: actions/checkout@v6
      - name: Set up Java ${{ matrix.java.version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java.javaInstall }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c
        with:
          gradle-version: '8.14.3'
          cache-read-only: ${{ github.ref != 'refs/heads/Branch_5_0' }}
      - name: Build with Gradle
        run: ./gradlew test -PbuildProfile=${{ matrix.java.buildProfile }} -PtestProfile=${{ matrix.java.testProfile }} -Ptest.dbondocker=true -Ptest.db.dir=/var/lib/firebird/data
      - name: Store Report Artifact
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: report-artifacts-${{ matrix.java.version }}
          path: build/reports
          compression-level: 9
          retention-days: 7
